In [1]:
# Основной файл.
#Скачивает данные через модули inputfpl1.py и inputUnderstat
#Преобразовывет их в таблицы таблицы через конструктор класса Source
#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.
import yagmail
import requests
import os
from dotenv import load_dotenv
from time import time
import runpy
import sys
from traceback import format_exc

from Source import Source
import constti

# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source
def program():
    start_program = time()
    
    sys.argv = ['', 'full']
    #Loading Data from FPL and Understat
    runpy.run_module('inputFPL', run_name='smth')
    runpy.run_module('inputUnderstat', run_name='smth')

    
    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average
    FPL = Source('FPL', ma_num=7)
    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average
    Understat = Source('Understat', ma_num=7)
    #Tests for the Final tables
    FPL.test()
    Understat.test()
    
    print(f'The whole program working time is  {time() - start_program}')
    #display(FPL.PlayerThreatAd)
    print('End')

#send mail or not
with_mail = 1

# Если отправлять ошибки на почту
if with_mail:
    try:
        program()
    except Exception as e:
        
        err = format_exc()
        
        #Reading passwords from .env
        load_dotenv()
        telegram_API = os.getenv('telegram')
        mail_pass = os.getenv('imonyapa_mail')
        
        #Sending Error message to mail
        FROM = 'imonyapa@gmail.com'
        TO = 'constti@gmail.com'
        SUBJECT = '1stpy'
        TEXT=f'{e} \n\n\n {err}'
        yag = yagmail.SMTP(FROM, mail_pass)
        yag.send(TO, SUBJECT, TEXT)
        
        #Sending Error message with telegram
        url = f'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text='+TEXT

        http_proxy  = "http://10.10.1.10:3128"
        https_proxy = "https://51.178.59.37:3128"
        ftp_proxy   = "ftp://10.10.1.10:3128"

        proxyDict = { 
                      "http"  : http_proxy, 
                      "https" : https_proxy, 
                      "ftp"   : ftp_proxy
                    }
        
        #Proxy is dead(((
        p=requests.get(url)#, proxies=proxyDict)
        
        print(TEXT)
# Без отправки ошибок на почту        
else: program()

Start inputFPL:
System var is - full
HTTPSConnectionPool(host='fantasy.premierleague.com', port=443): Max retries exceeded with url: /api/element-summary/75/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002607201CD30>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
HTTPSConnectionPool(host='fantasy.premierleague.com', port=443): Max retries exceeded with url: /api/element-summary/450/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026072262E10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
	Downloading FPL tables is over.	 It takes 203.481751203537 sec

	Checking equalities is over.	 It takes 0.5727443695068359 sec

	data_collection_type = full

	Creating tables is over.	 It takes 36.69809436798096 sec

inputFPL is over.	 It takes 240.75258994102478 sec

Start inputUnderstat:
	 All Data Downloaded.	 It takes 58.1134569644928 sec
	 All Columns Added.	 It takes 0.6349284648895264 sec
inputUnderstat is over.	 It takes 58.748385429382324 sec

Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.12109184265136719 sec
	 2. Constants and Functions are over.	 It takes 0.001998424530029297 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.42281198501586914 sec
		 3.2. Team_xA is over.	 It takes 0.413815975189209 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.44180846214294434 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.021985769271850586 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.019997119903564453 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.020989656448364258 sec
		 3.7. TableTeams is over.	 It takes 0.0049839019775390625 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 11.942750453948975 sec
		 4.2. Player_xA is over.	 It takes 11.81123423576355 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.4268181324005127 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.39782094955444336 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.514885425567627 sec
		 5.2. Visualizing futures.	 It takes 0.01900506019592285 sec
	 6. Writing to files is over.	 It takes 23.505264282226562 sec
FPL is created./t It takes 51.09125328063965 sec
Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.14793848991394043 sec
	 2. Constants and Functions are over.	 It takes 0.0019893646240234375 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.40481996536254883 sec
		 3.2. Team_xA is over.	 It takes 0.3868279457092285 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.3958151340484619 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.021999120712280273 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.01999044418334961 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.01999187469482422 sec
		 3.7. TableTeams is over.	 It takes 0.002989530563354492 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 11.288822650909424 sec
		 4.2. Player_xA is over.	 It takes 11.226113080978394 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.3723294734954834 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.3569371700286865 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.53505277633667 sec
		 5.2. Visualizing futures.	 It takes 0.010081052780151367 sec
	 6. Writing to files is over.	 It takes 22.477651596069336 sec
Understat is created./t It takes 48.673338651657104 sec
	 FPL Testing is over.	 It takes 0.20990681648254395 sec

                       player  element  fixture  minutes  FPL_minutes
0      Daniel Castelo Podence    469.0       89       80           69
1                 Fabio Silva    504.0       89       74           63
2  David Luiz Moreira Marinho      3.0       89       56           45
3     Willian Borges Da Silva    478.0       89       75           64
4                 Rob Holding     16.0       89       34           45

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 5.501719951629639 sec


The whole program working time is  404.9821720123291
End

In [1]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['', 'globals()'],
 '_oh': {},
 '_dh': ['C:\\Users\\const\\Documents\\GitHub\\tikeve.github.io'],
 'In': ['', 'globals()'],
 'Out': {},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000001EFD7324470>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x1efd7b4ad68>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x1efd7b4ad68>,
 '_': '',
 '__': '',
 '___': '',
 '_i': '',
 '_ii': '',
 '_iii': '',
 '_i1': 'globals()'}

In [14]:
import inputFPL
import runpy
a = runpy.run_module('inputFPL', run_name='smth')

Start inputFPL:
	 Downloads FPL is over.	 It takes 166.40240502357483 sec
	 Fixtures are over.	 It takes 59.91786503791809 sec
inputFPL is over.	 It takes 226.9049255847931 sec