In [2]:
''' Main file

    Main module. Runs program() which does pretty much everything + sends mistakes on mail and telegram
    
    
    Uses 3 modules: inputFPL, inputUnderstat, Source
    
    inputFPL downloads data from https://fantasy.premierleague.com/
    inputUnderstat downloads data from https://understat.com/
    Source converts data to suitable pandas tables correctness by running source.test function.
    
    
    Uses no data

'''
import yagmail
import requests
import os
from dotenv import load_dotenv
from time import time
import runpy
import sys
from traceback import format_exc
from Source import Source
import constti

# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source
def program():
    
    start_program = time()    
    sys.argv = ['', 'full']
    #Loading Data from FPL and Understat
    runpy.run_module('inputFPL', run_name='smth')
    print(f'Data Collection Type (sys.argv[1]) is {sys.argv[1]}\n\n')
    
    if sys.argv[1] != 'nothing':
        
        runpy.run_module('inputUnderstat', run_name='smth')
        #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average
        FPL = Source('FPL', ma_num=7)
        #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average
        Understat = Source('Understat', ma_num=7)
        #Tests for the Final tables
        FPL.test()
        Understat.test()
    
    print(f'The whole program working time is  {time() - start_program}')
    print('End')

    
    
    
    
    
    
#send mail or not
with_mail = 1

# Если отправлять ошибки на почту
if with_mail:
    try:
        program()
    except Exception as e:
        
        err = format_exc()
        
        #Reading passwords from .env
        load_dotenv()
        telegram_API = os.getenv('telegram')
        mail_pass = os.getenv('imonyapa_mail')
        
        #Sending Error message to mail
        FROM = 'imonyapa@gmail.com'
        TO = 'constti@gmail.com'
        SUBJECT = '1stpy'
        TEXT=f'{e} \n\n\n {err}'
        yag = yagmail.SMTP(FROM, mail_pass)
        yag.send(TO, SUBJECT, TEXT)
        
        #Sending Error message with telegram
        url = f'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text='+TEXT

        http_proxy  = "http://10.10.1.10:3128"
        https_proxy = "https://51.178.59.37:3128"
        ftp_proxy   = "ftp://10.10.1.10:3128"

        proxyDict = { 
                      "http"  : http_proxy, 
                      "https" : https_proxy, 
                      "ftp"   : ftp_proxy
                    }
        
        #Proxy is dead(((
        p=requests.get(url)#, proxies=proxyDict)
        
        print(TEXT)
# Без отправки ошибок на почту        
else: program()

Start inputFPL:
		Data Collection Type = full

	Downloading FPL tables is over.	 It takes 174.4850730895996 sec

	Creating tables is over.	 It takes 91.18747067451477 sec

inputFPL is over.	 It takes 265.6735439300537 sec

Data Collection Type (sys.argv[1]) is full


Start inputUnderstat:
	 All Data Downloaded.	 It takes 38.27026557922363 sec
	 All Columns Added.	 It takes 0.33381104469299316 sec
inputUnderstat is over.	 It takes 38.60507535934448 sec

Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.15291309356689453 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.8135349750518799 sec
		 3.2. Team_xA is over.	 It takes 0.915477991104126 sec
		 3.3. Team_Opponent_xG is over.	 It takes 1.0009517669677734 sec
		 3.3.99 Creating coeffitients is over.	 It takes 0.07419085502624512 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.06564688682556152 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.06550860404968262 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.06849980354309082 sec
		 3.7. TableTeams is over.	 It takes 0.0049974918365478516 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 27.25094723701477 sec
		 4.2. Player_xA is over.	 It takes 25.552257299423218 sec
		 4.2.99 Creating coeffitients is over.	 It takes 0.683192253112793 sec
		 4.3. Player_xG_Ad is over.	 It takes 1.0639317035675049 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.8781342506408691 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.0193419456481934 sec
		 5.2. Visualizing futures.	 It takes 0.9582548141479492 sec
	 6. Writing to files is over.	 It takes 74.50391840934753 sec
FPL is created./t It takes 135.07767343521118 sec
Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.08695626258850098 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.7604119777679443 sec
		 3.2. Team_xA is over.	 It takes 0.7642228603363037 sec
		 3.3. Team_Opponent_xG is over.	 It takes 1.077216386795044 sec
		 3.3.99 Creating coeffitients is over.	 It takes 0.08458733558654785 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.07671666145324707 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.07801699638366699 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.07018852233886719 sec
		 3.7. TableTeams is over.	 It takes 0.0069963932037353516 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 23.70807147026062 sec
		 4.2. Player_xA is over.	 It takes 23.06938147544861 sec
		 4.2.99 Creating coeffitients is over.	 It takes 0.5697181224822998 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.899538516998291 sec
		 4.4. Player_xA_Ad is over.	 It takes 1.0042414665222168 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.072256088256836 sec
		 5.2. Visualizing futures.	 It takes 0.8255283832550049 sec
	 6. Writing to files is over.	 It takes 73.84645342826843 sec
Understat is created./t It takes 128.00849509239197 sec
	 FPL Testing is over.	 It takes 0.395313024520874 sec

                       player  element  fixture  minutes  FPL_minutes
0  David Luiz Moreira Marinho      3.0       89       56           45
1     Willian Borges Da Silva    478.0       89       75           64
2                 Rob Holding     16.0       89       34           45
3      Daniel Castelo Podence    469.0       89       80           69
4                 Fabio Silva    504.0       89       74           63

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 11.489313125610352 sec


The whole program working time is  579.264404296875
End

In [3]:
globals()

{'__name__': '__main__',
 '__doc__': ' Main file\n\n    Main module. Runs program(), does some testing, sends mistakes on mail and telegram\n    \n    \n    Uses 3 modules: inputFPL, inputUnderstat, Source\n    \n    inputFPL downloads data from https://fantasy.premierleague.com/\n    inputUnderstat downloads data from https://understat.com/\n    Source converts data to suitable pandas tables correctness by running source.test function.\n    \n    \n    Uses no data\n\n',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  '\'\'\' Main file\n\n    Main module. Runs program(), does some testing, sends mistakes on mail and telegram\n    \n    \n    Uses 3 modules: inputFPL, inputUnderstat, Source\n    \n    inputFPL downloads data from https://fantasy.premierleague.com/\n    inputUnderstat downloads data from https://understat.com/\n    Source converts data to suitable pandas tables correctness by running source.test function.\n    \n    \n    Uses no data\n\n\'\'\'\n\n\n# Основной файл.\n#Скачивает данные через модули inputfpl1.py и inputUnderstat\n#Преобразовывет их в таблицы таблицы через конструктор класса Source\n#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.\nimport yagmail\nimport requests\nimport os\nfrom dotenv import load_dotenv\nfrom time import time\nimport runpy\nimport sys\nfrom traceback import format_exc\n\nfrom Source import Source\nimport constti\n\n# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source\ndef program():\n    start_program = time()\n    \n    sys.argv = [\'\', \'*\']\n    #Loading Data from FPL and Understat\n    runpy.run_module(\'inputFPL\', run_name=\'smth\')\n    runpy.run_module(\'inputUnderstat\', run_name=\'smth\')\n    print(f\' sys.argv is {sys.argv[1]}\')\n\n    \n    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average\n    FPL = Source(\'FPL\', ma_num=7)\n    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average\n    Understat = Source(\'Understat\', ma_num=7)\n    #Tests for the Final tables\n    FPL.test()\n    Understat.test()\n    \n    print(f\'The whole program working time is  {time() - start_program}\')\n    #display(FPL.PlayerThreatAd)\n    print(\'End\')\n\n#send mail or not\nwith_mail = 1\n\n# Если отправлять ошибки на почту\nif with_mail:\n    try:\n        program()\n    except Exception as e:\n        \n        err = format_exc()\n        \n        #Reading passwords from .env\n        load_dotenv()\n        telegram_API = os.getenv(\'telegram\')\n        mail_pass = os.getenv(\'imonyapa_mail\')\n        \n        #Sending Error message to mail\n        FROM = \'imonyapa@gmail.com\'\n        TO = \'constti@gmail.com\'\n        SUBJECT = \'1stpy\'\n        TEXT=f\'{e} \\n\\n\\n {err}\'\n        yag = yagmail.SMTP(FROM, mail_pass)\n        yag.send(TO, SUBJECT, TEXT)\n        \n        #Sending Error message with telegram\n        url = f\'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text=\'+TEXT\n\n        http_proxy  = "http://10.10.1.10:3128"\n        https_proxy = "https://51.178.59.37:3128"\n        ftp_proxy   = "ftp://10.10.1.10:3128"\n\n        proxyDict = { \n                      "http"  : http_proxy, \n                      "https" : https_proxy, \n                      "ftp"   : ftp_proxy\n                    }\n        \n        #Proxy is dead(((\n        p=requests.get(url)#, proxies=proxyDict)\n        \n        print(TEXT)\n# Без отправки ошибок на почту        \nelse: program()',
  'globals()\nsys.argv',
  'globals()'],
 '_oh': {2: ['', '*']},
 '_dh': ['c:\\Users\\const\\Documents\\GitHub\\tikeve.github.io'],
 'In': ['',
  '\'\'\' Main file\n\n    Main module. Runs program(), does some testing, sends mistakes on mail and telegram\n    \n    \n    Uses 3 modules: inputFPL, inputUnderstat, Source\n    \n    inputFPL downloads data from https://fantasy.premierleague.com/\n    inputUnderstat downloads data from https://understat.com/\n    Source converts data to suitable pandas tables correctness by running source.test function.\n    \n    \n    Uses no data\n\n\'\'\'\n\n\n# Основной файл.\n#Скачивает данные через модули inputfpl1.py и inputUnderstat\n#Преобразовывет их в таблицы таблицы через конструктор класса Source\n#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.\nimport yagmail\nimport requests\nimport os\nfrom dotenv import load_dotenv\nfrom time import time\nimport runpy\nimport sys\nfrom traceback import format_exc\n\nfrom Source import Source\nimport constti\n\n# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source\ndef program():\n    start_program = time()\n    \n    sys.argv = [\'\', \'*\']\n    #Loading Data from FPL and Understat\n    runpy.run_module(\'inputFPL\', run_name=\'smth\')\n    runpy.run_module(\'inputUnderstat\', run_name=\'smth\')\n    print(f\' sys.argv is {sys.argv[1]}\')\n\n    \n    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average\n    FPL = Source(\'FPL\', ma_num=7)\n    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average\n    Understat = Source(\'Understat\', ma_num=7)\n    #Tests for the Final tables\n    FPL.test()\n    Understat.test()\n    \n    print(f\'The whole program working time is  {time() - start_program}\')\n    #display(FPL.PlayerThreatAd)\n    print(\'End\')\n\n#send mail or not\nwith_mail = 1\n\n# Если отправлять ошибки на почту\nif with_mail:\n    try:\n        program()\n    except Exception as e:\n        \n        err = format_exc()\n        \n        #Reading passwords from .env\n        load_dotenv()\n        telegram_API = os.getenv(\'telegram\')\n        mail_pass = os.getenv(\'imonyapa_mail\')\n        \n        #Sending Error message to mail\n        FROM = \'imonyapa@gmail.com\'\n        TO = \'constti@gmail.com\'\n        SUBJECT = \'1stpy\'\n        TEXT=f\'{e} \\n\\n\\n {err}\'\n        yag = yagmail.SMTP(FROM, mail_pass)\n        yag.send(TO, SUBJECT, TEXT)\n        \n        #Sending Error message with telegram\n        url = f\'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text=\'+TEXT\n\n        http_proxy  = "http://10.10.1.10:3128"\n        https_proxy = "https://51.178.59.37:3128"\n        ftp_proxy   = "ftp://10.10.1.10:3128"\n\n        proxyDict = { \n                      "http"  : http_proxy, \n                      "https" : https_proxy, \n                      "ftp"   : ftp_proxy\n                    }\n        \n        #Proxy is dead(((\n        p=requests.get(url)#, proxies=proxyDict)\n        \n        print(TEXT)\n# Без отправки ошибок на почту        \nelse: program()',
  'globals()\nsys.argv',
  'globals()'],
 'Out': {2: ['', '*']},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000001303366E748>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x13035372748>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x13035372748>,
 '_': ['', '*'],
 '__': '',
 '___': '',
 '_i': 'globals()\nsys.argv',
 '_ii': '\'\'\' Main file\n\n    Main module. Runs program(), does some testing, sends mistakes on mail and telegram\n    \n    \n    Uses 3 modules: inputFPL, inputUnderstat, Source\n    \n    inputFPL downloads data from https://fantasy.premierleague.com/\n    inputUnderstat downloads data from https://understat.com/\n    Source converts data to suitable pandas tables correctness by running source.test function.\n    \n    \n    Uses no data\n\n\'\'\'\n\n\n# Основной файл.\n#Скачивает данные через модули inputfpl1.py и inputUnderstat\n#Преобразовывет их в таблицы таблицы через конструктор класса Source\n#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.\nimport yagmail\nimport requests\nimport os\nfrom dotenv import load_dotenv\nfrom time import time\nimport runpy\nimport sys\nfrom traceback import format_exc\n\nfrom Source import Source\nimport constti\n\n# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source\ndef program():\n    start_program = time()\n    \n    sys.argv = [\'\', \'*\']\n    #Loading Data from FPL and Understat\n    runpy.run_module(\'inputFPL\', run_name=\'smth\')\n    runpy.run_module(\'inputUnderstat\', run_name=\'smth\')\n    print(f\' sys.argv is {sys.argv[1]}\')\n\n    \n    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average\n    FPL = Source(\'FPL\', ma_num=7)\n    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average\n    Understat = Source(\'Understat\', ma_num=7)\n    #Tests for the Final tables\n    FPL.test()\n    Understat.test()\n    \n    print(f\'The whole program working time is  {time() - start_program}\')\n    #display(FPL.PlayerThreatAd)\n    print(\'End\')\n\n#send mail or not\nwith_mail = 1\n\n# Если отправлять ошибки на почту\nif with_mail:\n    try:\n        program()\n    except Exception as e:\n        \n        err = format_exc()\n        \n        #Reading passwords from .env\n        load_dotenv()\n        telegram_API = os.getenv(\'telegram\')\n        mail_pass = os.getenv(\'imonyapa_mail\')\n        \n        #Sending Error message to mail\n        FROM = \'imonyapa@gmail.com\'\n        TO = \'constti@gmail.com\'\n        SUBJECT = \'1stpy\'\n        TEXT=f\'{e} \\n\\n\\n {err}\'\n        yag = yagmail.SMTP(FROM, mail_pass)\n        yag.send(TO, SUBJECT, TEXT)\n        \n        #Sending Error message with telegram\n        url = f\'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text=\'+TEXT\n\n        http_proxy  = "http://10.10.1.10:3128"\n        https_proxy = "https://51.178.59.37:3128"\n        ftp_proxy   = "ftp://10.10.1.10:3128"\n\n        proxyDict = { \n                      "http"  : http_proxy, \n                      "https" : https_proxy, \n                      "ftp"   : ftp_proxy\n                    }\n        \n        #Proxy is dead(((\n        p=requests.get(url)#, proxies=proxyDict)\n        \n        print(TEXT)\n# Без отправки ошибок на почту        \nelse: program()',
 '_iii': '',
 '_i1': '\'\'\' Main file\n\n    Main module. Runs program(), does some testing, sends mistakes on mail and telegram\n    \n    \n    Uses 3 modules: inputFPL, inputUnderstat, Source\n    \n    inputFPL downloads data from https://fantasy.premierleague.com/\n    inputUnderstat downloads data from https://understat.com/\n    Source converts data to suitable pandas tables correctness by running source.test function.\n    \n    \n    Uses no data\n\n\'\'\'\n\n\n# Основной файл.\n#Скачивает данные через модули inputfpl1.py и inputUnderstat\n#Преобразовывет их в таблицы таблицы через конструктор класса Source\n#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.\nimport yagmail\nimport requests\nimport os\nfrom dotenv import load_dotenv\nfrom time import time\nimport runpy\nimport sys\nfrom traceback import format_exc\n\nfrom Source import Source\nimport constti\n\n# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source\ndef program():\n    start_program = time()\n    \n    sys.argv = [\'\', \'*\']\n    #Loading Data from FPL and Understat\n    runpy.run_module(\'inputFPL\', run_name=\'smth\')\n    runpy.run_module(\'inputUnderstat\', run_name=\'smth\')\n    print(f\' sys.argv is {sys.argv[1]}\')\n\n    \n    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average\n    FPL = Source(\'FPL\', ma_num=7)\n    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average\n    Understat = Source(\'Understat\', ma_num=7)\n    #Tests for the Final tables\n    FPL.test()\n    Understat.test()\n    \n    print(f\'The whole program working time is  {time() - start_program}\')\n    #display(FPL.PlayerThreatAd)\n    print(\'End\')\n\n#send mail or not\nwith_mail = 1\n\n# Если отправлять ошибки на почту\nif with_mail:\n    try:\n        program()\n    except Exception as e:\n        \n        err = format_exc()\n        \n        #Reading passwords from .env\n        load_dotenv()\n        telegram_API = os.getenv(\'telegram\')\n        mail_pass = os.getenv(\'imonyapa_mail\')\n        \n        #Sending Error message to mail\n        FROM = \'imonyapa@gmail.com\'\n        TO = \'constti@gmail.com\'\n        SUBJECT = \'1stpy\'\n        TEXT=f\'{e} \\n\\n\\n {err}\'\n        yag = yagmail.SMTP(FROM, mail_pass)\n        yag.send(TO, SUBJECT, TEXT)\n        \n        #Sending Error message with telegram\n        url = f\'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text=\'+TEXT\n\n        http_proxy  = "http://10.10.1.10:3128"\n        https_proxy = "https://51.178.59.37:3128"\n        ftp_proxy   = "ftp://10.10.1.10:3128"\n\n        proxyDict = { \n                      "http"  : http_proxy, \n                      "https" : https_proxy, \n                      "ftp"   : ftp_proxy\n                    }\n        \n        #Proxy is dead(((\n        p=requests.get(url)#, proxies=proxyDict)\n        \n        print(TEXT)\n# Без отправки ошибок на почту        \nelse: program()',
 'yagmail': <module 'yagmail' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\yagmail\\__init__.py'>,
 'requests': <module 'requests' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\__init__.py'>,
 'os': <module 'os' from 'C:\\ProgramData\\Anaconda3\\lib\\os.py'>,
 'load_dotenv': <function dotenv.main.load_dotenv(dotenv_path=None, stream=None, verbose=False, override=False, interpolate=True, **kwargs)>,
 'time': <function time.time>,
 'runpy': <module 'runpy' from 'C:\\ProgramData\\Anaconda3\\lib\\runpy.py'>,
 'sys': <module 'sys' (built-in)>,
 'format_exc': <function traceback.format_exc(limit=None, chain=True)>,
 'Source': Source.Source,
 'constti': <module 'constti' from 'c:\\Users\\const\\Documents\\GitHub\\tikeve.github.io\\constti.py'>,
 'program': <function __main__.program()>,
 'with_mail': 1,
 '_i2': 'globals()\nsys.argv',
 '_2': ['', '*'],
 '_i3': 'globals()'}

In [14]:
import inputFPL
import runpy
a = runpy.run_module('inputFPL', run_name='smth')

Start inputFPL:
	 Downloads FPL is over.	 It takes 166.40240502357483 sec
	 Fixtures are over.	 It takes 59.91786503791809 sec
inputFPL is over.	 It takes 226.9049255847931 sec