In [1]:
''' Main file

    Main module. Runs program(), does some testing, sends mistakes on mail and telegram
    
    
    Uses 3 modules: inputFPL, inputUnderstat, Source
    
    inputFPL downloads data from https://fantasy.premierleague.com/
    inputUnderstat downloads data from https://understat.com/
    Source converts data to suitable pandas tables correctness by running source.test function.
    
    
    Uses no data

'''


# Основной файл.
#Скачивает данные через модули inputfpl1.py и inputUnderstat
#Преобразовывет их в таблицы таблицы через конструктор класса Source
#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.
import yagmail
import requests
import os
from dotenv import load_dotenv
from time import time
import runpy
import sys
from traceback import format_exc

from Source import Source
import constti

# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source
def program():
    start_program = time()
    
    sys.argv = ['', '*']
    #Loading Data from FPL and Understat
    runpy.run_module('inputFPL', run_name='smth')
    runpy.run_module('inputUnderstat', run_name='smth')

    
    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average
    FPL = Source('FPL', ma_num=7)
    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average
    Understat = Source('Understat', ma_num=7)
    #Tests for the Final tables
    FPL.test()
    Understat.test()
    
    print(f'The whole program working time is  {time() - start_program}')
    #display(FPL.PlayerThreatAd)
    print('End')

#send mail or not
with_mail = 1

# Если отправлять ошибки на почту
if with_mail:
    try:
        program()
    except Exception as e:
        
        err = format_exc()
        
        #Reading passwords from .env
        load_dotenv()
        telegram_API = os.getenv('telegram')
        mail_pass = os.getenv('imonyapa_mail')
        
        #Sending Error message to mail
        FROM = 'imonyapa@gmail.com'
        TO = 'constti@gmail.com'
        SUBJECT = '1stpy'
        TEXT=f'{e} \n\n\n {err}'
        yag = yagmail.SMTP(FROM, mail_pass)
        yag.send(TO, SUBJECT, TEXT)
        
        #Sending Error message with telegram
        url = f'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text='+TEXT

        http_proxy  = "http://10.10.1.10:3128"
        https_proxy = "https://51.178.59.37:3128"
        ftp_proxy   = "ftp://10.10.1.10:3128"

        proxyDict = { 
                      "http"  : http_proxy, 
                      "https" : https_proxy, 
                      "ftp"   : ftp_proxy
                    }
        
        #Proxy is dead(((
        p=requests.get(url)#, proxies=proxyDict)
        
        print(TEXT)
# Без отправки ошибок на почту        
else: program()

Start inputFPL:
System var is - *
Indexes are not equal: {640, 639}
Players teams list has changed:

     team
0       1
1       1
2       1
3       1
4       1
..    ...
636    20
637    20
638    20
639    20
640    20

[641 rows x 1 columns]

	Checking equalities is over.	 It takes 4.3148651123046875 sec

	data_collection_type = full

		data_collection_type = full

	Downloading FPL tables is over.	 It takes 163.49254155158997 sec

	Creating tables is over.	 It takes 51.358333110809326 sec

inputFPL is over.	 It takes 219.16573977470398 sec

Start inputUnderstat:
HTTPSConnectionPool(host='understat.com', port=443): Max retries exceeded with url: /match/14506 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000209545EE5F8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
	 All Data Downloaded.	 It takes 90.43351793289185 sec
	 All Columns Added.	 It takes 0.8485333919525146 sec
inputUnderstat is over.	 It takes 91.28303599357605 sec

Start Creating FPL Tables:
Index(['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8', 'GW9', 'GW10',
       'GW11', 'GW12', 'GW13', 'GW14', 'GW15', 'GW16', 'GW17', 'GW18', 'GW19',
       'GW19*', 'GW20', 'GW21', 'GW22', 'GW23', 'GW24', 'GW25', 'GW26', 'GW27',
       'GW28', 'GW29', 'GW30', 'GW31', 'GW32', 'GW33', 'GW34', 'GW35', 'GW36',
       'GW37', 'GW38'],
      dtype='object')
	 1. Reading files from FPL is over.	 It takes 0.45374107360839844 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.5047106742858887 sec
		 3.2. Team_xA is over.	 It takes 0.49571752548217773 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.5221059322357178 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.025986433029174805 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.0229947566986084 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.024985551834106445 sec
		 3.7. TableTeams is over.	 It takes 0.0039882659912109375 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 13.653885841369629 sec
		 4.2. Player_xA is over.	 It takes 13.638077020645142 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.4199662208557129 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.4480254650115967 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.502016305923462 sec
		 5.2. Visualizing futures.	 It takes 0.019995450973510742 sec
	 6. Writing to files is over.	 It takes 28.575459718704224 sec
FPL is created./t It takes 60.314663887023926 sec
Start Creating Understat Tables:
Index(['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8', 'GW9', 'GW10',
       'GW11', 'GW12', 'GW13', 'GW14', 'GW15', 'GW16', 'GW17', 'GW18', 'GW19',
       'GW19*', 'GW20', 'GW21', 'GW22', 'GW23', 'GW24', 'GW25', 'GW26', 'GW27',
       'GW28', 'GW29', 'GW30', 'GW31', 'GW32', 'GW33', 'GW34', 'GW35', 'GW36',
       'GW37', 'GW38'],
      dtype='object')
	 1. Reading files from Understat is over.	 It takes 0.37456536293029785 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.439739465713501 sec
		 3.2. Team_xA is over.	 It takes 0.44890570640563965 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.4630746841430664 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.023990154266357422 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.023991107940673828 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.022856473922729492 sec
		 3.7. TableTeams is over.	 It takes 0.003997802734375 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 12.854493141174316 sec
		 4.2. Player_xA is over.	 It takes 13.362029314041138 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.41536879539489746 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.4740180969238281 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.4900412559509277 sec
		 5.2. Visualizing futures.	 It takes 0.019993066787719727 sec
	 6. Writing to files is over.	 It takes 28.290706396102905 sec
Understat is created./t It takes 58.70976758003235 sec
	 FPL Testing is over.	 It takes 0.23848390579223633 sec

                       player  element  fixture  minutes  FPL_minutes
0      Daniel Castelo Podence    469.0       89       80           69
1                 Fabio Silva    504.0       89       74           63
2  David Luiz Moreira Marinho      3.0       89       56           45
3     Willian Borges Da Silva    478.0       89       75           64
4                 Rob Holding     16.0       89       34           45

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 6.411449670791626 sec


The whole program working time is  436.1431164741516
End

In [1]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['', 'globals()'],
 '_oh': {},
 '_dh': ['C:\\Users\\const\\Documents\\GitHub\\tikeve.github.io'],
 'In': ['', 'globals()'],
 'Out': {},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000001EFD7324470>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x1efd7b4ad68>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x1efd7b4ad68>,
 '_': '',
 '__': '',
 '___': '',
 '_i': '',
 '_ii': '',
 '_iii': '',
 '_i1': 'globals()'}

In [14]:
import inputFPL
import runpy
a = runpy.run_module('inputFPL', run_name='smth')

Start inputFPL:
	 Downloads FPL is over.	 It takes 166.40240502357483 sec
	 Fixtures are over.	 It takes 59.91786503791809 sec
inputFPL is over.	 It takes 226.9049255847931 sec