In [1]:
# Основной файл.
#Скачивает данные через модули inputfpl1.py и inputUnderstat
#Преобразовывет их в таблицы таблицы через конструктор класса Source
#Ф-ция program делает все необходомое, нужна чтобы использовать её по желанию с почтой(telegram) и без.
import yagmail
import requests
import os
from dotenv import load_dotenv
from time import time
import runpy
from traceback import format_exc

from Source import Source
import constti

# Скачаивает и записывает в таблицы все данные. Выводит в файоы папки input и output/Source
def program():
    start_program = time()

    #Loading Data from FPL and Understat
    runpy.run_module('inputFPL', run_name='smth')
    runpy.run_module('inputUnderstat', run_name='smth')

    
    #Берет данные fantasy.premierleague.com(FPl) и делает из них финальные таблицы. ma_num - gameweeks to average
    FPL = Source('FPL', ma_num=7)
    #Takes data from understat.com(Understat) and builds table out of them. ma_num - gameweeks to average
    Understat = Source('Understat', ma_num=7)
    #Tests for the Final tables
    FPL.test()
    Understat.test()
    
    print(f'The whole program working time is  {time() - start_program}')
    #display(FPL.PlayerThreatAd)
    print('End')

#send mail or not
with_mail = 0

# Если отправлять ошибки на почту
if with_mail:
    try:
        program()
    except Exception as e:
        
        err = format_exc()
        
        #Reading passwords from .env
        load_dotenv()
        telegram_API = os.getenv('telegram')
        mail_pass = os.getenv('imonyapa_mail')
        
        #Sending Error message to mail
        FROM = 'imonyapa@gmail.com'
        TO = 'constti@gmail.com'
        SUBJECT = '1stpy'
        TEXT=f'{e} \n\n\n {err}'
        yag = yagmail.SMTP(FROM, mail_pass)
        yag.send(TO, SUBJECT, TEXT)
        
        #Sending Error message with telegram
        url = f'https://api.telegram.org/bot1182664319:{telegram_API}/sendMessage?chat_id=108651591&text='+TEXT

        http_proxy  = "http://10.10.1.10:3128"
        https_proxy = "https://51.178.59.37:3128"
        ftp_proxy   = "ftp://10.10.1.10:3128"

        proxyDict = { 
                      "http"  : http_proxy, 
                      "https" : https_proxy, 
                      "ftp"   : ftp_proxy
                    }
        
        #Proxy is dead(((
        p=requests.get(url)#, proxies=proxyDict)
        
        print(TEXT)
# Без отправки ошибок на почту        
else: program()

Start inputFPL:
HTTPSConnectionPool(host='fantasy.premierleague.com', port=443): Max retries exceeded with url: /api/element-summary/153/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000278E9762550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
	 Downloads FPL is over.	 It takes 158.68236589431763 sec
	 Fixtures are over.	 It takes 2.0588290691375732 sec
inputFPL is over.	 It takes 160.80414199829102 sec

Start inputUnderstat:
	 All Data Downloaded.	 It takes 8.027275800704956 sec
	 All Columns Added.	 It takes 0.09195089340209961 sec
inputUnderstat is over.	 It takes 8.119226694107056 sec

Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.03697824478149414 sec
	 2. Constants and Functions are over.	 It takes 0.001999378204345703 sec
	 3. Calculating team tables
		 3.1. TeamThreat is over.	 It takes 0.06996011734008789 sec
		 3.2. TeamCreativity is over.	 It takes 0.09470868110656738 sec
		 3.3. TeamDefence is over.	 It takes 0.05896615982055664 sec
		 3.4. TeamThreatAd is over.	 It takes 0.0029981136322021484 sec
		 3.5. TeamCreativityAd is over.	 It takes 0.003997325897216797 sec
		 3.6. TeamDefenceAd is over.	 It takes 0.0030002593994140625 sec
		 3.7. TableTeams is over.	 It takes 0.0029964447021484375 sec
	 4. Calculating player tables
		 4.1. PlayerThreat is over.	 It takes 1.3092737197875977 sec
		 4.2. PlayerCreativity is over.	 It takes 1.268082618713379 sec
		 4.3. PlayerThreatAd is over.	 It takes 0.05795025825500488 sec
		 4.4. PlayerCreativityAd is over.	 It takes 0.051969289779663086 sec

c:\Users\const\Documents\GitHub\tikeve.github.io\Source.py:396: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 396 of the file c:\Users\const\Documents\GitHub\tikeve.github.io\Source.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  tag_to_replace = str(BeautifulSoup(old_file)('table')[0])

	 5. Writing to files is over.	 It takes 6.722340106964111 sec
FPL is created./t It takes 9.687219858169556 sec

Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.023010730743408203 sec
	 2. Constants and Functions are over.	 It takes 0.0019986629486083984 sec
	 3. Calculating team tables
		 3.1. TeamThreat is over.	 It takes 0.055077552795410156 sec
		 3.2. TeamCreativity is over.	 It takes 0.05397534370422363 sec
		 3.3. TeamDefence is over.	 It takes 0.05301785469055176 sec
		 3.4. TeamThreatAd is over.	 It takes 0.0030112266540527344 sec
		 3.5. TeamCreativityAd is over.	 It takes 0.00299835205078125 sec
		 3.6. TeamDefenceAd is over.	 It takes 0.00298309326171875 sec
		 3.7. TableTeams is over.	 It takes 0.00299835205078125 sec
	 4. Calculating player tables
		 4.1. PlayerThreat is over.	 It takes 1.1409425735473633 sec
		 4.2. PlayerCreativity is over.	 It takes 1.1692028045654297 sec
		 4.3. PlayerThreatAd is over.	 It takes 0.050960540771484375 sec
		 4.4. PlayerCreativityAd is over.	 It takes 0.04997134208679199 sec
	 5. Writing to files is over.	 It takes 6.26019549369812 sec
Understat is created./t It takes 8.874346733093262 sec

	 FPL Testing is over.	 It takes 0.14697670936584473 sec

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 0.869013786315918 sec
The whole program working time is  188.50589060783386
End

In [2]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'from bs4 import BeautifulSoup\nimport requests\nimport pandas as pd\nimport json\nimport numpy as np\nfrom pathlib import Path\n\nimport constti\nfrom inputFPL1 import inputFPL\nfrom outputFPL1 import outputFPL\n\n\n#inputFPL скачивает данные, создавая переиенные d1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers\n\nd1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers = inputFPL()\n\n\n#outputFPL берет данные inputFPl и делает из них финальные таблицы\n\nTeamThreat, TeamCreativity, TableDefence, TeamThreatAd, TeamCreativityAd, TableDefenceAd, \\\nTableTeams, PlayerThreat, PlayerCreativity, PlayerThreatAd, PlayerCreativityAd \\\n= outputFPL(d1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers)\n\n\nPlayerThreatAd',
  'globals()'],
 '_oh': {1:                    Name           Team  Threat per fixture adj  \
  1       Raheem Sterling       Man City               55.648125
  2         Mohamed Salah      Liverpool               52.979526
  3       Roberto Firmino      Liverpool               49.514304
  4          Raúl Jiménez         Wolves               48.012609
  5       Marcus Rashford        Man Utd               42.305767
  ..                  ...            ...                     ...
  588    Richard Stearman  Sheffield Utd                0.000000
  589  Ruben Loftus-Cheek        Chelsea                0.000000
  590     Willy Caballero        Chelsea                0.000000
  591       Jake Eastwood  Sheffield Utd                0.000000
  592          Oskar Buur         Wolves                0.000000

       Threat per game adj        Threat GW21adj       Threat GW20adj  \
  1              58.430531                 [0.0]  [21.92909265145849]
  2              62.328854  [109.64546325729243]  [34.89677016442538]
  3              49.514304   [70.66040965469956]  [27.01685432084545]
  4              48.012609   [24.39279123068062]  [33.26399480944935]
  5              42.305767   [26.21471880099247]  [71.05624489607754]
  ..                   ...                   ...                  ...
  588             0.000000                 [0.0]                [0.0]
  589             0.000000                 [0.0]                [0.0]
  590             0.000000                 [0.0]                [0.0]
  591             0.000000                 [0.0]                [0.0]
  592             0.000000                 [0.0]                [0.0]

             Threat GW19adj        Threat GW18adj        Threat GW17adj  \
  1     [67.54213580211362]   [85.14413233901514]  [44.565021961687194]
  2     [30.84932331123737]                    []  [117.27303476288758]
  3     [77.74029474431818]                    []   [35.65100256791783]
  4     [162.0789886839102]  [49.162350660238936]  [33.169192424242425]
  5    [28.380282528030975]   [30.02189689929922]   [46.31921857874937]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

             Threat GW16adj  ...        Threat GW10adj         Threat GW9adj  \
  1     [86.40810808677256]  ...  [55.549696755692516]   [33.81927402494413]
  2       [77.386845210903]  ...   [88.13528272727271]                 [0.0]
  3     [48.47307886836781]  ...  [107.08910696969697]   [54.31366794025703]
  4    [11.709528980080876]  ...  [10.248435357344519]  [20.904953208556147]
  5     [38.66104317230886]  ...  [60.335612173929604]   [39.91679377133922]
  ..                    ...  ...                   ...                   ...
  588                 [0.0]  ...                 [0.0]                 [0.0]
  589                 [0.0]  ...                 [0.0]                 [0.0]
  590                 [0.0]  ...                 [0.0]                 [0.0]
  591                 [0.0]  ...                 [0.0]                 [0.0]
  592                    []  ...                    []                    []

              Threat GW8adj         Threat GW7adj         Threat GW6adj  \
  1     [55.15941090505945]    [88.0065152996238]                 [0.0]
  2    [115.99345565025253]   [82.84323890550985]   [47.26202941867885]
  3     [50.59289023042929]  [12.182829250810272]   [76.14438073009369]
  4    [44.608895968048685]   [12.19639561534031]    [25.3644555187081]
  5    [1.5766823626683875]   [33.20531048125712]  [5.6380360319215415]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

              Threat GW5adj         Threat GW4adj         Threat GW3adj  \
  1     [70.76398958670757]   [9.757940816734063]   [55.27631800778785]
  2     [57.54890623739614]   [59.72843773873185]  [58.546205322216515]
  3    [22.861894258691617]   [74.14564684808091]   [86.50857204327515]
  4     [17.06684395674514]   [62.53094508131166]  [44.281427978714994]
  5      [24.6794586489899]  [107.25149906998372]  [27.243304075649434]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

              Threat GW2adj         Threat GW1adj
  1    [115.61832787878787]   [69.53577772703234]
  2    [26.358419262962098]   [29.05047993559574]
  3    [29.085152290165073]  [49.162350660238936]
  4    [27.156833970128513]   [37.01918797348485]
  5    [10.131320370317043]   [76.14438073009369]
  ..                    ...                   ...
  588                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]
  592                    []                    []

  [592 rows x 25 columns]},
 '_dh': ['c:\\Users\\const\\Documents\\GitHub\\tikeve.github.io'],
 'In': ['',
  'from bs4 import BeautifulSoup\nimport requests\nimport pandas as pd\nimport json\nimport numpy as np\nfrom pathlib import Path\n\nimport constti\nfrom inputFPL1 import inputFPL\nfrom outputFPL1 import outputFPL\n\n\n#inputFPL скачивает данные, создавая переиенные d1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers\n\nd1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers = inputFPL()\n\n\n#outputFPL берет данные inputFPl и делает из них финальные таблицы\n\nTeamThreat, TeamCreativity, TableDefence, TeamThreatAd, TeamCreativityAd, TableDefenceAd, \\\nTableTeams, PlayerThreat, PlayerCreativity, PlayerThreatAd, PlayerCreativityAd \\\n= outputFPL(d1,team_number,bigTable,Fixtures,lastGW,Gameweeks,teams,players,teamplayers)\n\n\nPlayerThreatAd',
  'globals()'],
 'Out': {1:                    Name           Team  Threat per fixture adj  \
  1       Raheem Sterling       Man City               55.648125
  2         Mohamed Salah      Liverpool               52.979526
  3       Roberto Firmino      Liverpool               49.514304
  4          Raúl Jiménez         Wolves               48.012609
  5       Marcus Rashford        Man Utd               42.305767
  ..                  ...            ...                     ...
  588    Richard Stearman  Sheffield Utd                0.000000
  589  Ruben Loftus-Cheek        Chelsea                0.000000
  590     Willy Caballero        Chelsea                0.000000
  591       Jake Eastwood  Sheffield Utd                0.000000
  592          Oskar Buur         Wolves                0.000000

       Threat per game adj        Threat GW21adj       Threat GW20adj  \
  1              58.430531                 [0.0]  [21.92909265145849]
  2              62.328854  [109.64546325729243]  [34.89677016442538]
  3              49.514304   [70.66040965469956]  [27.01685432084545]
  4              48.012609   [24.39279123068062]  [33.26399480944935]
  5              42.305767   [26.21471880099247]  [71.05624489607754]
  ..                   ...                   ...                  ...
  588             0.000000                 [0.0]                [0.0]
  589             0.000000                 [0.0]                [0.0]
  590             0.000000                 [0.0]                [0.0]
  591             0.000000                 [0.0]                [0.0]
  592             0.000000                 [0.0]                [0.0]

             Threat GW19adj        Threat GW18adj        Threat GW17adj  \
  1     [67.54213580211362]   [85.14413233901514]  [44.565021961687194]
  2     [30.84932331123737]                    []  [117.27303476288758]
  3     [77.74029474431818]                    []   [35.65100256791783]
  4     [162.0789886839102]  [49.162350660238936]  [33.169192424242425]
  5    [28.380282528030975]   [30.02189689929922]   [46.31921857874937]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

             Threat GW16adj  ...        Threat GW10adj         Threat GW9adj  \
  1     [86.40810808677256]  ...  [55.549696755692516]   [33.81927402494413]
  2       [77.386845210903]  ...   [88.13528272727271]                 [0.0]
  3     [48.47307886836781]  ...  [107.08910696969697]   [54.31366794025703]
  4    [11.709528980080876]  ...  [10.248435357344519]  [20.904953208556147]
  5     [38.66104317230886]  ...  [60.335612173929604]   [39.91679377133922]
  ..                    ...  ...                   ...                   ...
  588                 [0.0]  ...                 [0.0]                 [0.0]
  589                 [0.0]  ...                 [0.0]                 [0.0]
  590                 [0.0]  ...                 [0.0]                 [0.0]
  591                 [0.0]  ...                 [0.0]                 [0.0]
  592                    []  ...                    []                    []

              Threat GW8adj         Threat GW7adj         Threat GW6adj  \
  1     [55.15941090505945]    [88.0065152996238]                 [0.0]
  2    [115.99345565025253]   [82.84323890550985]   [47.26202941867885]
  3     [50.59289023042929]  [12.182829250810272]   [76.14438073009369]
  4    [44.608895968048685]   [12.19639561534031]    [25.3644555187081]
  5    [1.5766823626683875]   [33.20531048125712]  [5.6380360319215415]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

              Threat GW5adj         Threat GW4adj         Threat GW3adj  \
  1     [70.76398958670757]   [9.757940816734063]   [55.27631800778785]
  2     [57.54890623739614]   [59.72843773873185]  [58.546205322216515]
  3    [22.861894258691617]   [74.14564684808091]   [86.50857204327515]
  4     [17.06684395674514]   [62.53094508131166]  [44.281427978714994]
  5      [24.6794586489899]  [107.25149906998372]  [27.243304075649434]
  ..                    ...                   ...                   ...
  588                 [0.0]                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]                 [0.0]
  592                    []                    []                    []

              Threat GW2adj         Threat GW1adj
  1    [115.61832787878787]   [69.53577772703234]
  2    [26.358419262962098]   [29.05047993559574]
  3    [29.085152290165073]  [49.162350660238936]
  4    [27.156833970128513]   [37.01918797348485]
  5    [10.131320370317043]   [76.14438073009369]
  ..                    ...                   ...
  588                 [0.0]                 [0.0]
  589                 [0.0]                 [0.0]
  590                 [0.0]                 [0.0]
  591                 [0.0]                 [0.0]
  592                    []                    []

  [592 rows x 25 columns]},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000001A8F55FAFD0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x1a8f7348358>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x1a8f7348358>,
 '_':                    Name           Team  Threat per fixture adj  \
 1       Raheem Sterling       Man City               55.648125
 2         Mohamed Salah      Liverpool               52.979526
 3       Roberto Firmino      Liverpool               49.514304
 4          Raúl Jiménez         Wolves               48.012609
 5       Marcus Rashford        Man Utd               42.305767
 ..                  ...            ...                     ...
 588    Richard Stearman  Sheffield Utd                0.000000
 589  Ruben Loftus-Cheek        Chelsea                0.000000
 590     Willy Caballero        Chelsea                0.000000
 591       Jake Eastwood  Sheffield Utd                0.000000
 592          Oskar Buur         Wolves                0.000000

      Threat per game adj        Threat GW21adj       Threat GW20adj  \
 1              58.430531                 [0.0]  [21.92909265145849]
 2              62.328854  [109.64546325729243]  [34.89677016442538]
 3              49.514304   [70.66040965469956]  [27.01685432084545]
 4              48.012609   [24.39279123068062]  [33.26399480944935]
 5              42.305767   [26.21471880099247]  [71.05624489607754]
 ..                   ...                   ...                  ...
 588             0.000000                 [0.0]                [0.0]
 589             0.000000                 [0.0]                [0.0]
 590             0.000000                 [0.0]                [0.0]
 591             0.000000                 [0.0]                [0.0]
 592             0.000000                 [0.0]                [0.0]

            Threat GW19adj        Threat GW18adj        Threat GW17adj  \
 1     [67.54213580211362]   [85.14413233901514]  [44.565021961687194]
 2     [30.84932331123737]                    []  [117.27303476288758]
 3     [77.74029474431818]                    []   [35.65100256791783]
 4     [162.0789886839102]  [49.162350660238936]  [33.169192424242425]
 5    [28.380282528030975]   [30.02189689929922]   [46.31921857874937]
 ..                    ...                   ...                   ...
 588                 [0.0]                 [0.0]                 [0.0]
 589                 [0.0]                 [0.0]                 [0.0]
 590                 [0.0]                 [0.0]                 [0.0]
 591                 [0.0]                 [0.0]                 [0.0]
 592                    []                    []                    []

            Threat GW16adj  ...        Threat GW10adj         Threat GW9adj  \
 1     [86.40810808677256]  ...  [55.549696755692516]   [33.81927402494413]
 2       [77.386845210903]  ...   [88.13528272727271]                 [0.0]
 3     [48.47307886836781]  ...  [107.08910696969697]   [54.31366794025703]
 4    [11.709528980080876]  ...  [10.248435357344519]  [20.904953208556147]
 5     [38.66104317230886]  ...  [60.335612173929604]   [39.91679377133922]
 ..                    ...  ...                   ...                   ...
 588                 [0.0]  ...                 [0.0]                 [0.0]
 589                 [0.0]  ...                 [0.0]                 [0.0]
 590                 [0.0]  ...                 [0.0]                 [0.0]
 591                 [0.0]  ...                 [0.0]                 [0.0]
 592                    []  ...                    []                    []

             Threat GW8adj         Threat GW7adj         Threat GW6adj  \
 1     [55.15941090505945]    [88.0065152996238]                 [0.0]
 2    [115.99345565025253]   [82.84323890550985]   [47.26202941867885]
 3     [50.59289023042929]  [12.182829250810272]   [76.14438073009369]
 4    [44.608895968048685]   [12.19639561534031]    [25.3644555187081]
 5    [1.5766823626683875]   [33.20531048125712]  [5.6380360319215415]
 ..                    ...                   ...                   ...
 588                 [0.0]                 [0.0]                 [0.0]
 589                 [0.0]                 [0.0]                 [0.0]
 590                 [0.0]                 [0.0]                 [0.0]
 591                 [0.0]                 [0.0]                 [0.0]
 592                    []                    []                    []

             Threat GW5adj         Threat GW4adj         Threat GW3adj  \
 1     [70.76398958670757]   [9.757940816734063]   [55.27631800778785]
 2     [57.54890623739614]   [59.72843773873185]  [58.546205322216515]
 3    [22.861894258691617]   [74.14564684808091]   [86.50857204327515]
 4     [17.06684395674514]   [62.53094508131166]  [44.281427978714994]
 5      [24.6794586489899]  [107.25149906998372]  [27.243304075649434]
 ..                    ...                   ...                   ...
 588                 [0.0]                 [0.0]                 [0.0]
 589                 [0.0]                 [0.0]                 [0.0]
 590                 [0.0]                 [0.0]                 [0.0]
 591                 [0.0]                 [0.0]                 [0.0]
 592                    []                    []                    []

             Threat GW2adj         Threat GW1adj
 1    [115.61832787878787]   [69.53577772703234]
 2    [26.358419262962098]   [29.05047993559574]
 3    [29.085152290165073]  [49.162350660238936]
 4    [27.156833970128513]   [37.01918797348485]
 5    [10.131320370317043]   [76.14438073009369]
 ..                    ...                   ...
 588                 [0.0]                 [0.0]
 589                 [0.0]                 [0.0]
 590                 [0.0]                 [0.0]
 591                 [0.0]                 [0.0]
 592                    []                    []

 [592 rows x 25 columns],
 '__': '',
 '___': '',

In [14]:
import inputFPL
import runpy
a = runpy.run_module('inputFPL', run_name='smth')

Start inputFPL:
	 Downloads FPL is over.	 It takes 166.40240502357483 sec
	 Fixtures are over.	 It takes 59.91786503791809 sec
inputFPL is over.	 It takes 226.9049255847931 sec