In [3]:
#Downloadting Data from fantasy.premierleague.com(FPL)
print('Start inputFPL:')
from time import time
start_module = time()
start = start_module

import constti
import Brr_functions
from bs4 import BeautifulSoup
import pandas as pd
import json
import numpy as np
from pathlib import Path

#List of useful links
url1 = "https://fantasy.premierleague.com/api/bootstrap-static/" #Each line is for the player with aggregate Data
url2 = "https://fantasy.premierleague.com/api/entry/698498/history/" #Data for FPL manager history
url3 = "https://fantasy.premierleague.com/api/event/6/live/" #Not used
url4 = "https://fantasy.premierleague.com/api/fixtures" #Fixtures Table
url5 = 'https://fantasy.premierleague.com/api/element-summary/191/' #Data for fixture 191

#Downloading the Table Which is Used for Players and Teams Lists only
p1 = constti.long_request(url1)  
data1 = p1.text
d1 = json.loads(data1)
bigTable = pd.DataFrame(d1['elements'])
bigTable['full_name'] = bigTable['first_name'] + ' ' + bigTable['second_name']

#Creating the Lists of Teams, Players and the Dictionary of Correspondence
teams = dict(zip(pd.DataFrame(d1['teams'])['id'],pd.DataFrame(d1['teams'])['name']))
players = dict(zip(bigTable['id'],bigTable['full_name']))
teamplayers = dict(zip(bigTable['id'],bigTable['team']))
team_number = len(teams)

#Downloading the Fixtures Table
p4 = constti.long_request(url4) 
d4 = json.loads(p4.text)
Fixtures = pd.DataFrame(d4)

#Calculating Last Gameweek which has already started
firstr = len(Fixtures)+1
lastr = 0
for i in range(len(Fixtures)):
    if Fixtures.at[i,'finished']==True:
        firstr = min(firstr, i)
        lastr = i
if firstr < len(Fixtures)+1:
    lastGW = int(Fixtures.at[lastr,'event'])
else: lastGW = 0
if lastr == len(Fixtures):
    lastGW = int(Fixtures.at[lastr,'event'])

#Creating the Main Table for FPL Source
Table = pd.DataFrame()
for i in bigTable['id']:
    url = 'https://fantasy.premierleague.com/api/element-summary/'+str(i)+'/'
    p = constti.long_request(url)
    d = json.loads(p.text)
    dd = pd.DataFrame(d['history'])
    Table = Table.append(dd, ignore_index=True)
if 'threat' in Table.columns:
    Table['name'] = [players[Table.at[i, 'element']] for i in Table.index]
    Table['threat'] = pd.to_numeric(Table['threat'])
    Table['creativity'] = pd.to_numeric(Table['creativity'])
    #Table['team'] = [teamplayers[Table.at[i,'element']] for i in Table.index]
    Table['team'] = [Fixtures[Fixtures['id']==Table.at[i,'fixture']]['team_h'].values[0] if Table.at[i,'was_home']\
    else Fixtures[Fixtures['id']==Table.at[i,'fixture']]['team_a'].values[0] for i in Table.index]
    
#Deleteting double gameweeks for players changeg one PL cloub for another during GW ("Walcott case")
#And matches from the current GW that are not played yet
indexes_to_drop = []
#Deleting 'Walcott case'
for i in Table.index:#[:-1]:
    if i!= len(Table) - 1:
        if (Table['element'][i]==Table['element'][i+1])&(Table['round'][i]==Table['round'][i+1])&\
        (Table['team'][i]!=Table['team'][i+1]):
            if Table['minutes'][i] ==  0:
                indexes_to_drop.append(i)
            elif Table['minutes'][i+1] ==  0:
                indexes_to_drop.append(i+1)
if indexes_to_drop != []:
    '''
        Large_Table is needed only for inputUndersat. To get FPL names when Understat data is already calculated
        but FPL data is not. So players played are not excluded from the table but have zero data.
    '''
    Large_Table = Table.drop(indexes_to_drop).reset_index()
#Deleting not played
for i in Table.index:
    if (Fixtures[Fixtures['id'] == Table.at[i,'fixture']]['finished'].values[0] == False)&(not i in indexes_to_drop):
        indexes_to_drop.append(i)
if indexes_to_drop != []:
    Table = Table.drop(indexes_to_drop).reset_index()
            
            
            
            

#Making Teams Template Table
Teams = pd.DataFrame()
Teams['id'] = pd.DataFrame(d1['teams'])['id']
Teams['Teams'] = pd.DataFrame(d1['teams'])['name']
Teams['XXX Target number XXX'] = np.zeros(team_number)
Teams['Matches'] = [len(Fixtures[Fixtures['finished']&((Fixtures['team_a']==i)|(Fixtures['team_h']==i))]) \
                              for i in range(1,team_number+1)]

#Making Players Template Table
Players = pd.DataFrame()
Players['id'] = bigTable['id']
Players['Name'] = constti.strip_accents_pdlist(pd.DataFrame(bigTable['full_name']))
Players['web_name'] = constti.strip_accents_pdlist(pd.DataFrame(bigTable['web_name']))
Players['Team number'] = [bigTable[bigTable['id'] == i]['team'].sum() for i in Players['id']]
Players['Team'] = [dict(zip(pd.DataFrame(d1['teams'])['id'],pd.DataFrame(d1['teams'])['name']))\
                   [Players.at[i,'Team number']] for i in Players.index]
#Players['Team games'] = [Teams.at[Players.at[i,'Team number']-1,'Matches'] for i in Players.index]



if  not Table.empty:
    Players['Team games'] = [len(Table[(Table['element']==i) ]) for i in Players['id']]
    Players['Played'] = [len(Table[(Table['element']==i)&(Table['minutes']>0)]) \
                        for i in Players['id']]


print('\t Downloads FPL is over.\t It takes ' + str(time() - start) + ' sec')
start = time()


#Calculating Fixtures and Opponents
            
Team_all = pd.DataFrame()
#Team_fixtures = pd.DataFrame()
Team_played_fixtures = pd.DataFrame()
Team_upcoming_fixtures = pd.DataFrame()
Team_opponent_team = pd.DataFrame()
for j in range(lastGW,0,-1): 
    '''
        Team_all - contains [number of fixture, home team id, away team id]
        Team_fixtures - contains [number of fixture]
        Team_opponent_team - [opponent team id]
    '''
    Team_all['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&\
    (Fixtures['event']==j)][['id', 'team_h', 'team_a']].values for i in range(1, team_number+1)]

    #Team_fixtures['GW'+str(j)] = [list(pd.DataFrame(Team_all.at[i,'GW'+str(j)])[0]) for i in Team_all.index]
    
    
    Team_played_fixtures['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&\
    (Fixtures['event']==j)&Fixtures['finished']][['id']].values for i in range(1, team_number+1)]

    Team_opponent_team['GW'+str(j)] = [[pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0]\
    if pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0] != i+1\
    else pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][1]\
    for v in range(len(pd.DataFrame(Team_all.at[i,'GW'+str(j)])))] for i in Team_all.index]
    
for j in range(lastGW,int(Fixtures['event'].max()+1)): 
    Team_upcoming_fixtures['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&\
    (Fixtures['event']==j)&(Fixtures['finished']==False)][['id']].values for i in range(1, team_number+1)]
               
'''
    Player_all - contains [number of fixture, opponent team id]
    Team_opponent_team - [opponent team id]
'''
Player_all = pd.DataFrame()
Player_played_fixtures = pd.DataFrame()
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_opponent_team = pd.DataFrame()
Player_all['id'] = Players['id']
Player_all['name'] = [players[Player_all.at[i, 'id']] for i in Player_all.index]
if  not Table.empty:
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team']].values for i in Players['id']]

        Player_played_fixtures['GW'+str(j)] = [list(pd.DataFrame(Player_all.at[i,'GW'+str(j)])[0])\
        for i in Player_all.index]

        Player_opponent_team['GW'+str(j)] = [list(pd.DataFrame(Player_all.at[i,'GW'+str(j)])[1])\
        for i in Player_all.index]
for i in Players.index:
    Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)
        
        
        
        
print('\t Fixtures are over.\t It takes ' + str(time() - start) + ' sec')


#Writing Tables to csv
Table.to_csv(Path('in/Table_FPL.csv'), index=False)
Large_Table.to_csv(Path('in/LTable_FPL.csv'), index=False)
Fixtures.to_csv(Path('in/Fixtures.csv'), index=False)
Teams.to_csv(Path('in/Teams.csv'), index=False)
Players.to_csv(Path('in/Players.csv'), index=False)


#Team_fixtures.to_json(Path('in/Team_fixtures.txt'))
Team_played_fixtures.to_json(Path('in/Team_played_fixtures.txt'))
Team_upcoming_fixtures.to_json(Path('in/Team_upcoming_fixtures.txt'))
Team_opponent_team.to_json(Path('in/Team_opponent_team.txt'))
#Player_fixtures.to_json(Path('in/Player_fixtures.txt'))
Player_played_fixtures.to_json(Path('in/Player_played_fixtures.txt'))
Player_upcoming_fixtures.to_json(Path('in/Player_upcoming_fixtures.txt'))
Player_opponent_team.to_json(Path('in/Player_opponent_team.txt'))


# Team_fixtures.to_csv(Path('in/Team_fixtures.csv'), index=False)
# Team_opponent_team.to_csv(Path('in/Team_opponent_team.csv'), index=False)
# Player_fixtures.to_csv(Path('in/Player_fixtures.csv'), index=False)
# Player_opponent_team.to_csv(Path('in/Player_opponent_team.csv'), index=False)

print('inputFPL is over.\t It takes ' + str(time() - start_module) + ' sec\n')

if __name__ == '__main__':
    display(Table)

Start inputFPL:
	 Downloads FPL is over.	 It takes 231.84000420570374 sec
	 Fixtures are over.	 It takes 31.968642950057983 sec
inputFPL is over.	 It takes 264.4421181678772 sec

,index,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,name,team
0,0,0,0,0,0,0.0,1,2,0,0,...,0.0,0,0,0,0,70,False,0,Mesut Özil,1
1,1,0,0,0,0,0.0,1,9,0,0,...,0.0,0,-16828,995,17823,69,True,0,Mesut Özil,1
2,2,0,0,0,0,0.0,1,23,0,0,...,0.0,0,-11451,675,12126,69,False,0,Mesut Özil,1
3,3,0,0,0,0,0.0,1,29,0,0,...,0.0,0,-5324,647,5971,68,True,0,Mesut Özil,1
4,4,0,0,0,0,0.0,1,44,0,0,...,0.0,0,-4224,616,4840,68,False,0,Mesut Özil,1
5,5,0,0,0,0,0.0,1,49,0,0,...,0.0,0,-3184,276,3460,68,True,0,Mesut Özil,1
6,6,0,0,0,0,0.0,2,2,0,0,...,0.0,0,0,0,0,50,False,0,Sokratis Papastathopoulos,1
7,7,0,0,0,0,0.0,2,9,0,0,...,0.0,0,-4015,51,4066,50,True,0,Sokratis Papastathopoulos,1
8,8,0,0,0,0,0.0,2,23,0,0,...,0.0,0,-1641,9673,11314,49,False,0,Sokratis Papastathopoulos,1
9,9,0,0,0,0,0.0,2,29,0,0,...,0.0,0,-739,38,777,49,True,0,Sokratis Papastathopoulos,1
10,10,0,0,0,0,0.0,2,44,0,0,...,0.0,0,-167,233,400,49,False,0,Sokratis Papastathopoulos,1
11,11,0,0,0,0,0.0,2,49,0,0,...,0.0,0,-392,182,574,49,True,0,Sokratis Papastathopoulos,1
12,12,0,0,0,0,0.0,3,2,0,0,...,0.0,0,0,0,0,55,False,0,David Luiz Moreira Marinho,1
13,13,0,0,3,0,0.0,3,9,0,0,...,0.0,1,-23455,1738,25193,55,True,0,David Luiz Moreira Marinho,1
14,14,0,0,11,0,3.2,3,23,3,0,...,0.0,1,711,7407,6696,55,False,0,David Luiz Moreira Marinho,1
15,15,0,0,13,0,0.8,3,29,1,0,...,0.0,2,1264,6180,4916,55,True,0,David Luiz Moreira Marinho,1
16,16,0,0,12,0,3.3,3,44,1,0,...,19.0,2,-1132,5063,6195,55,False,0,David Luiz Moreira Marinho,1
17,17,0,0,12,0,2.5,3,49,0,0,...,2.0,1,2396,6821,4425,55,True,0,David Luiz Moreira Marinho,1
18,18,0,0,19,1,15.3,4,2,0,1,...,54.0,7,0,0,0,120,False,1,Pierre-Emerick Aubameyang,1
19,19,1,0,20,0,36.4,4,9,1,0,...,15.0,5,-76570,146991,223561,120,True,0,Pierre-Emerick Aubameyang,1
20,20,0,0,5,0,0.9,4,23,3,0,...,4.0,2,-967555,50656,1018211,119,False,0,Pierre-Emerick Aubameyang,1
21,21,0,0,10,0,4.6,4,29,1,0,...,30.0,2,-120167,106551,226718,119,True,0,Pierre-Emerick Aubameyang,1
22,22,0,0,7,0,29.9,4,44,1,0,...,2.0,2,-582811,29415,612226,118,False,0,Pierre-Emerick Aubameyang,1
23,23,0,0,12,0,15.8,4,49,1,0,...,12.0,2,-235512,14819,250331,118,True,0,Pierre-Emerick Aubameyang,1
24,24,0,0,0,0,0.0,5,2,0,0,...,0.0,0,0,0,0,50,False,0,Cédric Soares,1
25,25,0,0,0,0,0.0,5,9,0,0,...,0.0,0,-11854,901,12755,49,True,0,Cédric Soares,1
26,26,0,0,0,0,0.0,5,23,0,0,...,0.0,0,-8218,449,8667,49,False,0,Cédric Soares,1
27,27,0,0,0,0,0.0,5,29,0,0,...,0.0,0,-3849,218,4067,48,True,0,Cédric Soares,1
28,28,0,0,0,0,0.0,5,44,0,0,...,0.0,0,-1444,518,1962,48,False,0,Cédric Soares,1
29,29,0,0,0,0,0.0,5,49,0,0,...,0.0,0,-1068,280,1348,48,True,0,Cédric Soares,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3105,3223,0,0,0,0,0.0,504,42,0,0,...,0.0,0,-10723,2051,12774,53,False,0,Fabio Silva,20
3106,3224,0,0,0,0,0.0,504,58,0,0,...,0.0,0,-4447,1840,6287,53,True,0,Fabio Silva,20
3107,3225,0,0,21,1,1.5,505,8,0,0,...,0.0,5,0,0,0,50,False,1,Fernando Marçal,20
3108,3226,0,0,3,0,0.3,505,18,0,0,...,0.0,1,3066,8299,5233,50,True,0,Fernando Marçal,20
3109,3227,0,0,0,0,0.0,505,28,0,0,...,0.0,0,-3629,9868,13497,50,False,0,Fernando Marçal,20
3110,3228,0,0,0,0,0.0,505,38,0,0,...,0.0,0,-5488,397,5885,49,True,0,Fernando Marçal,20
3111,3229,0,0,2,0,0.0,505,42,0,0,...,0.0,1,-1646,2066,3712,49,False,0,Fernando Marçal,20
3112,3230,0,0,3,0,11.0,505,58,1,0,...,10.0,1,-277,1271,1548,49,True,0,Fernando Marçal,20
3113,3231,0,0,4,0,0.8,515,8,0,0,...,0.0,1,0,0,0,50,False,0,Vitor Ferreira,20
3114,3232,0,0,0,0,0.0,515,18,0,0,...,0.0,0,-276,288,564,50,True,0,Vitor Ferreira,20
3115,3233,0,0,4,0,12.1,515,28,1,0,...,0.0,1,-475,190,665,50,False,0,Vitor Ferreira,20
3116,3234,0,0,0,0,0.0,515,38,0,0,...,0.0,0,-257,180,437,50,True,0,Vitor Ferreira,20
3117,3235,0,0,0,0,0.0,515,42,0,0,...,0.0,0,-314,106,420,49,False,0,Vitor Ferreira,20
3118,3236,0,0,0,0,0.0,515,58,0,0,...,0.0,0,-164,55,219,49,True,0,Vitor Ferreira,20
3119,3237,0,0,5,0,15.2,545,28,1,0,...,2.0,1,463,699,236,45,False,0,Ki-Jana Hoever,20
3120,3238,0,0,4,0,0.0,545,38,0,0,...,0.0,1,411,689,278,45,True,0,Ki-Jana Hoever,20
3121,3239,0,0,0,0,0.0,545,42,0,0,...,0.0,0,171,510,339,45,False,0,Ki-Jana Hoever,20
3122,3240,0,0,0,0,0.0,545,58,0,0,...,0.0,0,23,300,277,45,True,0,Ki-Jana Hoever,20
3123,3241,0,0,14,0,3.4,546,28,3,0,...,6.0,1,29089,36050,6961,55,False,0,Nélson Cabral Semedo,20
3124,3242,0,0,21,1,9.5,546,38,0,0,...,20.0,6,29218,41228,12010,55,True,0,Nélson Cabral Semedo,20
3125,3243,0,0,24,1,0.2,546,42,0,0,...,0.0,6,36935,55747,18812,55,False,0,Nélson Cabral Semedo,20
3126,3244,0,0,13,0,28.3,546,58,1,0,...,2.0,2,29411,39596,10185,55,True,0,Nélson Cabral Semedo,20
3127,3245,0,0,0,0,0.0,553,28,0,0,...,0.0,0,0,0,0,45,False,0,Meritan Shabani,20
3128,3246,0,0,0,0,0.0,553,38,0,0,...,0.0,0,725,991,266,45,True,0,Meritan Shabani,20
3129,3247,0,0,0,0,0.0,553,42,0,0,...,0.0,0,249,644,395,45,False,0,Meritan Shabani,20
3130,3248,0,0,0,0,0.0,553,58,0,0,...,0.0,0,97,392,295,45,True,0,Meritan Shabani,20
3131,3249,0,0,0,0,0.0,563,42,0,0,...,0.0,0,714,1266,552,50,False,0,Rayan Ait Nouri,20
3132,3250,0,0,0,0,0.0,563,58,0,0,...,0.0,0,-8,304,312,50,True,0,Rayan Ait Nouri,20
3133,3251,0,0,0,0,0.0,581,42,0,0,...,0.0,0,0,0,0,45,False,0,Owen Otasowie,20
3134,3252,0,0,0,0,0.0,581,58,0,0,...,0.0,0,171,221,50,45,True,0,Owen Otasowie,20

In [37]:
Players[Players['web_name']=='Walcott']
#Table[Table['element']==148]
Team_played_fixtures
Player_upcoming_fixtures
#Player_fixtures#.iloc[148]
#Fixtures['event'].max()
#Players
Fixtures

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,pulse_id,started,stats,team_a,team_a_difficulty,team_a_score,team_h,team_h_difficulty,team_h_score
0,2128286,NaN,False,False,379,None,0,False,58896,None,[],13,2,NaN,4,4,NaN
1,2128290,NaN,False,False,380,None,0,False,58900,None,[],2,5,NaN,12,3,NaN
2,2128288,1.0,True,True,2,2020-09-12T11:30:00Z,90,False,58898,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",1,2,3.0,8,4,0.0
3,2128287,1.0,True,True,1,2020-09-12T14:00:00Z,90,False,58897,True,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",16,3,0.0,6,2,1.0
4,2128289,1.0,True,True,3,2020-09-12T16:30:00Z,90,False,58899,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",10,5,3.0,11,2,4.0
5,2128293,1.0,True,True,6,2020-09-12T19:00:00Z,90,False,58903,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",14,3,2.0,19,2,0.0
6,2128292,1.0,True,True,5,2020-09-13T13:00:00Z,90,False,58902,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",9,2,3.0,18,3,0.0
7,2128291,1.0,True,True,4,2020-09-13T15:30:00Z,90,False,58901,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",7,4,1.0,17,3,0.0
8,2128295,1.0,True,True,8,2020-09-14T17:00:00Z,90,False,58905,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",20,3,2.0,15,3,0.0
9,2128294,1.0,True,True,7,2020-09-14T19:15:00Z,90,False,58904,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",5,3,3.0,3,4,1.0
10,2128299,2.0,True,True,12,2020-09-19T11:30:00Z,90,False,58909,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",18,3,2.0,7,2,5.0
11,2128300,2.0,True,True,13,2020-09-19T14:00:00Z,90,False,58910,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",8,3,3.0,10,2,4.0
12,2128302,2.0,True,True,15,2020-09-19T16:30:00Z,90,False,58912,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",6,4,3.0,13,2,1.0
13,2128296,2.0,True,True,9,2020-09-19T19:00:00Z,90,False,58906,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",19,4,1.0,1,3,2.0
14,2128304,2.0,True,True,17,2020-09-20T11:00:00Z,90,False,58914,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",17,3,5.0,16,4,2.0
15,2128303,2.0,True,True,16,2020-09-20T13:00:00Z,90,False,58913,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,3.0,14,2,0.0
16,2128298,2.0,True,True,11,2020-09-20T15:30:00Z,90,False,58908,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",11,4,2.0,5,4,0.0
17,2128301,2.0,True,True,14,2020-09-20T18:00:00Z,90,False,58911,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",4,4,2.0,9,2,4.0
18,2128297,2.0,True,True,10,2020-09-21T17:00:00Z,90,False,58907,True,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",15,3,0.0,2,3,1.0
19,2128305,2.0,True,True,18,2020-09-21T19:15:00Z,90,False,58915,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",12,3,3.0,20,4,1.0
20,2128306,3.0,True,True,19,2020-09-26T11:30:00Z,90,False,58916,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",13,3,3.0,3,4,2.0
21,2128308,3.0,True,True,21,2020-09-26T14:00:00Z,90,False,58918,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",7,3,2.0,6,3,1.0
22,2128314,3.0,True,True,27,2020-09-26T16:30:00Z,90,False,58924,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",5,2,3.0,18,4,3.0
23,2128307,3.0,True,True,20,2020-09-26T19:00:00Z,90,False,58917,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",16,2,1.0,4,2,0.0
24,2128312,3.0,True,True,25,2020-09-27T11:00:00Z,90,False,58922,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",10,3,1.0,15,2,0.0
25,2128313,3.0,True,True,26,2020-09-27T13:00:00Z,90,False,58923,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",14,4,1.0,17,2,1.0
26,2128311,3.0,True,True,24,2020-09-27T15:30:00Z,90,False,58921,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",9,5,5.0,12,3,2.0
27,2128315,3.0,True,True,28,2020-09-27T18:00:00Z,90,False,58925,True,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",20,3,0.0,19,3,4.0
28,2128309,3.0,True,True,22,2020-09-28T16:45:00Z,90,False,58919,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,3.0,8,3,0.0
29,2128310,3.0,True,True,23,2020-09-28T19:00:00Z,90,False,58920,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",1,5,1.0,11,4,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,2128636,36.0,False,False,349,2021-05-11T18:45:00Z,0,False,59246,False,[],19,3,NaN,3,3,NaN
351,2128637,36.0,False,False,350,2021-05-11T18:45:00Z,0,False,59247,False,[],10,2,NaN,4,2,NaN
352,2128638,36.0,False,False,351,2021-05-11T18:45:00Z,0,False,59248,False,[],15,3,NaN,7,3,NaN
353,2128639,36.0,False,False,352,2021-05-11T19:00:00Z,0,False,59249,False,[],9,4,NaN,13,3,NaN
354,2128640,36.0,False,False,353,2021-05-11T19:00:00Z,0,False,59250,False,[],11,2,NaN,18,4,NaN
355,2128641,36.0,False,False,354,2021-05-12T18:45:00Z,0,False,59251,False,[],1,4,NaN,5,4,NaN
356,2128643,36.0,False,False,356,2021-05-12T18:45:00Z,0,False,59253,False,[],12,3,NaN,14,4,NaN
357,2128644,36.0,False,False,357,2021-05-12T18:45:00Z,0,False,59254,False,[],8,3,NaN,16,2,NaN
358,2128645,36.0,False,False,358,2021-05-12T18:45:00Z,0,False,59255,False,[],20,4,NaN,17,3,NaN
359,2128642,36.0,False,False,355,2021-05-12T19:00:00Z,0,False,59252,False,[],2,3,NaN,6,3,NaN
360,2128646,37.0,False,False,359,2021-05-15T14:00:00Z,0,False,59256,False,[],12,3,NaN,3,4,NaN
361,2128647,37.0,False,False,360,2021-05-15T14:00:00Z,0,False,59257,False,[],11,2,NaN,4,4,NaN
362,2128648,37.0,False,False,361,2021-05-15T14:00:00Z,0,False,59258,False,[],9,4,NaN,5,3,NaN
363,2128649,37.0,False,False,362,2021-05-15T14:00:00Z,0,False,59259,False,[],1,3,NaN,6,4,NaN
364,2128650,37.0,False,False,363,2021-05-15T14:00:00Z,0,False,59260,False,[],20,3,NaN,7,3,NaN
365,2128651,37.0,False,False,364,2021-05-15T14:00:00Z,0,False,59261,False,[],8,4,NaN,13,2,NaN
366,2128652,37.0,False,False,365,2021-05-15T14:00:00Z,0,False,59262,False,[],15,3,NaN,14,3,NaN
367,2128653,37.0,False,False,366,2021-05-15T14:00:00Z,0,False,59263,False,[],10,3,NaN,16,2,NaN
368,2128654,37.0,False,False,367,2021-05-15T14:00:00Z,0,False,59264,False,[],2,4,NaN,17,3,NaN
369,2128655,37.0,False,False,368,2021-05-15T14:00:00Z,0,False,59265,False,[],19,2,NaN,18,3,NaN
370,2128656,38.0,False,False,369,2021-05-23T15:00:00Z,0,False,59266,False,[],3,4,NaN,1,2,NaN
371,2128657,38.0,False,False,370,2021-05-23T15:00:00Z,0,False,59267,False,[],5,3,NaN,2,4,NaN
372,2128658,38.0,False,False,371,2021-05-23T15:00:00Z,0,False,59268,False,[],14,2,NaN,8,2,NaN
373,2128659,38.0,False,False,372,2021-05-23T15:00:00Z,0,False,59269,False,[],18,3,NaN,10,2,NaN
374,2128660,38.0,False,False,373,2021-05-23T15:00:00Z,0,False,59270,False,[],17,4,NaN,9,4,NaN
375,2128661,38.0,False,False,374,2021-05-23T15:00:00Z,0,False,59271,False,[],6,5,NaN,11,2,NaN
376,2128662,38.0,False,False,375,2021-05-23T15:00:00Z,0,False,59272,False,[],7,5,NaN,12,3,NaN
377,2128663,38.0,False,False,376,2021-05-23T15:00:00Z,0,False,59273,False,[],4,3,NaN,15,2,NaN
378,2128664,38.0,False,False,377,2021-05-23T15:00:00Z,0,False,59274,False,[],16,3,NaN,19,2,NaN
379,2128665,38.0,False,False,378,2021-05-23T15:00:00Z,0,False,59275,False,[],13,3,NaN,20,4,NaN

In [28]:
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[33,'Team number']])
Player_upcoming_fixtures

,GW6,GW7,GW8,GW9,GW10,GW11,GW12,GW13,GW14,GW15,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
2,[[51]],[[67]],[[70]],[[79]],[[90]],[[100]],[[114]],[[121]],[[129]],[[147]],...,[[279]],[[295]],[[299]],[[311]],[[326]],[[329]],[[348]],[[349]],[[359]],[[369]]

In [6]:
#Table = Table.drop(2001)
Table[Table['element']==148].columns
#Table.index[100]
#indexes_to_drop = []
#print(len(indexes_to_drop))

Index(['index', 'assists', 'bonus', 'bps', 'clean_sheets', 'creativity',
       'element', 'fixture', 'goals_conceded', 'goals_scored', 'ict_index',
       'influence', 'kickoff_time', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'name', 'team'],
      dtype='object')

In [21]:
Player_all.iloc[445]
Table['name'] = [players[Table.at[i, 'element']] for i in Table.index]
Player_all
Table.columns

Index(['assists', 'bonus', 'bps', 'clean_sheets', 'creativity', 'element',
       'fixture', 'goals_conceded', 'goals_scored', 'ict_index', 'influence',
       'kickoff_time', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'name', 'team'],
      dtype='object')

In [44]:
import psycopg2
conn=psycopg2.connect("dbname=FPLinNumbers user=postgres host=localhost password=mmmm57")
cur = conn.cursor()


df = pd.DataFrame([[1,2,3,]])

from sqlalchemy import create_engine

#cur.execute("DROP TABLE Table_FPL;")
conn.commit()
engine = create_engine('postgresql+psycopg2://postgres:mmmm57@localhost:5432/FPLinNumbers')
Table.to_sql('table_fpl', engine)
conn.commit()

In [49]:
cur.execute("SELECT * FROM Table_FPL")
cur.fetchall()

[(0,
  1,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  70,
  0,
  76656,
  0,
  0,
  1),
 (1,
  1,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  69,
  -16828,
  68335,
  995,
  17823,
  1),
 (2,
  1,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  69,
  -11451,
  59793,
  675,
  12126,
  1),
 (3,
  1,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  68,
  -5324,
  56403,
  647,
  5971,
  1),
 (4,
  2,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  12184,
  0,
  0,
  1),
 (5,
  2,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  -4015,
  8234,
  51,
  4066,
  1),
 (6,
  2,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -1641,
  6874,
  9673,
  11314,
  1),
 (7,
  2,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -739,
  6274,
  38,
  777,
  1),
 (8,
  3,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  55,
  0,
  69564,
  0,
  0,
  1),
 (9,
  3,
  9,
  19,
  1,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  '0.0',
  0.0,
  0.0,
  '0.0',
  55,
  -23455,
  49797,
  1738,
  25193,
  1),
 (10,
  3,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  11,
  '20.2',
  3.2,
  0.0,
  '2.3',
  55,
  711,
  61983,
  7407,
  6696,
  1),
 (11,
  3,
  29,
  15,
  2,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  13,
  '23.0',
  0.8,
  0.0,
  '2.4',
  55,
  1264,
  69592,
  6180,
  4916,
  1),
 (12,
  4,
  2,
  8,
  7,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  19,
  '36.6',
  15.3,
  54.0,
  '10.6',
  120,
  0,
  2823465,
  0,
  0,
  1),
 (13,
  4,
  9,
  19,
  5,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  20,
  '28.0',
  36.4,
  15.0,
  '7.9',
  120,
  -76570,
  3002806,
  146991,
  223561,
  1),
 (14,
  4,
  23,
  11,
  2,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  '4.2',
  0.9,
  4.0,
  '0.9',
  119,
  -967555,
  2046859,
  50656,
  1018211,
  1),
 (15,
  4,
  29,
  15,
  2,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  10,
  '9.4',
  4.6,
  30.0,
  '4.4',
  119,
  -120167,
  2000213,
  106551,
  226718,
  1),
 (16,
  5,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  35774,
  0,
  0,
  1),
 (17,
  5,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -11854,
  27448,
  901,
  12755,
  1),
 (18,
  5,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -8218,
  20173,
  449,
  8667,
  1),
 (19,
  5,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  48,
  -3849,
  16771,
  218,
  4067,
  1),
 (20,
  6,
  2,
  8,
  7,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  86,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  29,
  '38.6',
  12.7,
  48.0,
  '9.9',
  85,
  0,
  196064,
  0,
  0,
  1),
 (21,
  6,
  9,
  19,
  7,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  76,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  29,
  '33.0',
  5.7,
  31.0,
  '7.0',
  85,
  59951,
  342387,
  93434,
  33483,
  1),
 (22,
  6,
  23,
  11,
  7,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  73,
  1,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  22,
  '40.4',
  11.4,
  55.0,
  '10.7',
  85,
  -21852,
  340935,
  47809,
  69661,
  1),
 (23,
  6,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  85,
  29347,
  395242,
  65917,
  36570,
  1),
 (24,
  7,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  899,
  0,
  0,
  1),
 (25,
  7,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  -153,
  1016,
  41,
  194,
  1),
 (26,
  7,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  -102,
  1030,
  9679,
  9781,
  1),
 (27,
  7,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  -79,
  1016,
  51,
  130,
  1),
 (28,
  8,
  2,
  8,
  7,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  1,
  29,
  '14.0',
  0.0,
  0.0,
  '1.4',
  50,
  0,
  400285,
  0,
  0,
  1),
 (29,
  8,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  18,
  '18.0',
  0.0,
  0.0,
  '1.8',
  50,
  71268,
  614046,
  112820,
  41552,
  1),
 (30,
  8,
  23,
  11,
  3,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  5,
  1,
  22,
  '35.8',
  0.0,
  0.0,
  '3.6',
  50,
  -33085,
  605224,
  57089,
  90174,
  1),
 (31,
  8,
  29,
  15,
  2,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  12,
  '11.2',
  0.0,
  0.0,
  '1.1',
  50,
  32333,
  675971,
  67684,
  35351,
  1),
 (32,
  9,
  2,
  8,
  3,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  77,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  11,
  '6.8',
  17.2,
  21.0,
  '4.5',
  55,
  0,
  42909,
  0,
  0,
  1),
 (33,
  9,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  10,
  '16.4',
  6.7,
  0.0,
  '2.3',
  55,
  670,
  58116,
  9879,
  9209,
  1),
 (34,
  9,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  59,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  8,
  '6.8',
  3.4,
  0.0,
  '1.0',
  55,
  -8902,
  53341,
  3582,
  12484,
  1),
 (35,
  9,
  29,
  15,
  1,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  9,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  '1.4',
  0.0,
  0.0,
  '0.1',
  55,
  -3370,
  53027,
  3893,
  7263,
  1),
 (36,
  10,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  0,
  769,
  0,
  0,
  1),
 (37,
  10,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -153,
  740,
  38,
  191,
  1),
 (38,
  10,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -83,
  705,
  69,
  152,
  1),
 (39,
  10,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -55,
  667,
  31,
  86,
  1),
 (40,
  11,
  2,
  8,
  5,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  23,
  '9.8',
  26.4,
  4.0,
  '4.0',
  50,
  0,
  240975,
  0,
  0,
  1),
 (41,
  11,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  10,
  '7.6',
  6.9,
  2.0,
  '1.7',
  50,
  23037,
  326713,
  54450,
  31413,
  1),
 (42,
  11,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  12,
  '15.6',
  1.5,
  2.0,
  '1.9',
  50,
  -19029,
  323391,
  39377,
  58406,
  1),
 (43,
  11,
  29,
  15,
  11,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  90,
  0,
  2,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  36,
  '44.8',
  26.0,
  4.0,
  '7.5',
  50,
  -9896,
  326848,
  23203,
  33099,
  1),
 (44,
  13,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  0,
  1043,
  0,
  0,
  1),
 (45,
  13,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -177,
  1100,
  75,
  252,
  1),
 (46,
  13,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -117,
  1040,
  83,
  200,
  1),
 (47,
  13,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -94,
  989,
  49,
  143,
  1),
 (48,
  14,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  17088,
  0,
  0,
  1),
 (49,
  14,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  9,
  '3.6',
  5.4,
  4.0,
  '1.3',
  49,
  -4572,
  15419,
  492,
  5064,
  1),
 (50,
  14,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -427,
  17142,
  2149,
  2576,
  1),
 (51,
  14,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -1375,
  16501,
  764,
  2139,
  1),
 (52,
  15,
  2,
  8,
  6,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  21,
  '10.2',
  2.8,
  4.0,
  '1.7',
  50,
  0,
  112927,
  0,
  0,
  1),
 (53,
  15,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  13143,
  152759,
  27762,
  14619,
  1),
 (54,
  15,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  10,
  '6.0',
  1.5,
  3.0,
  '1.1',
  50,
  -30409,
  123510,
  5689,
  36098,
  1),
 (55,
  15,
  29,
  15,
  1,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  '4.0',
  0.0,
  0.0,
  '0.4',
  50,
  -9240,
  119317,
  4867,
  14107,
  1),
 (56,
  16,
  2,
  8,
  6,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  28,
  '20.6',
  1.2,
  0.0,
  '2.2',
  45,
  0,
  71148,
  0,
  0,
  1),
 (57,
  16,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  16,
  '13.6',
  0.3,
  0.0,
  '1.4',
  45,
  46375,
  148466,
  72351,
  25976,
  1),
 (58,
  16,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  14,
  '32.0',
  0.1,
  0.0,
  '3.2',
  45,
  14874,
  171240,
  51839,
  36965,
  1),
 (59,
  16,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  10811,
  189724,
  26789,
  15978,
  1),
 (60,
  17,
  2,
  8,
  6,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  90,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  25,
  '12.8',
  2.5,
  2.0,
  '1.7',
  55,
  0,
  686005,
  0,
  0,
  1),
 (61,
  17,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  55,
  659,
  777005,
  56372,
  55713,
  1),
 (62,
  17,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  90,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  16,
  '28.2',
  0.7,
  0.0,
  '2.9',
  55,
  -248129,
  518268,
  7001,
  255130,
  1),
 (63,
  17,
  29,
  15,
  2,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  90,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  14,
  '15.6',
  21.3,
  0.0,
  '3.7',
  54,
  -46465,
  493590,
  10701,
  57166,
  1),
 (64,
  18,
  2,
  8,
  1,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  15,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  '2.0',
  15.3,
  6.0,
  '2.3',
  80,
  0,
  132947,
  0,
  0,
  1),
 (65,
  18,
  9,
  19,
  1,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  26,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  '1.0',
  2.3,
  8.0,
  '1.1',
  79,
  -46967,
  95969,
  2864,
  49831,
  1),
 (66,
  18,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  22,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  '0.0',
  1.3,
  0.0,
  '0.1',
  78,
  -31642,
  69956,
  1751,
  33393,
  1),
 (67,
  18,
  29,
  15,
  6,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  32,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  22,
  '34.4',
  1.1,
  19.0,
  '5.5',
  78,
  -10151,
  63489,
  2000,
  12151,
  1),
 (68,
  19,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  15039,
  0,
  0,
  1),
 (69,
  19,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -3347,
  14793,
  811,
  4158,
  1),
 (70,
  19,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -2285,
  13789,
  1248,
  3533,
  1),
 (71,
  19,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  48,
  -1210,
  13254,
  751,
  1961,
  1),
 (72,
  20,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  0,
  7504,
  0,
  0,
  1),
 (73,
  20,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  50,
  -1555,
  6935,
  261,
  1816,
  1),
 (74,
  20,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -943,
  6446,
  528,
  1471,
  1),
 (75,
  20,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  49,
  -637,
  6061,
  277,
  914,
  1),
 (76,
  21,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  55,
  0,
  5478,
  0,
  0,
  1),
 (77,
  21,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  54,
  -1235,
  5332,
  225,
  1460,
  1),
 (78,
  21,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  54,
  -913,
  4712,
  193,
  1106,
  1),
 (79,
  21,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  53,
  -370,
  4571,
  242,
  612,
  1),
 (80,
  22,
  2,
  8,
  1,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  '0.0',
  0.0,
  0.0,
  '0.0',
  60,
  0,
  112190,
  0,
  0,
  1),
 (81,
  22,
  9,
  19,
  8,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  13,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  31,
  '34.0',
  0.1,
  21.0,
  '5.5',
  59,
  -34641,
  83645,
  3801,
  38442,
  1),
 (82,
  22,
  23,
  11,
  1,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  17,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '0.0',
  0.1,
  2.0,
  '0.1',
  59,
  -11025,
  80665,
  11733,
  22758,
  1),
 (83,
  22,
  29,
  15,
  1,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  57,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  '5.4',
  3.0,
  19.0,
  '2.7',
  58,
  -11704,
  72091,
  6127,
  17831,
  1),
 (84,
  23,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  0,
  17820,
  0,
  0,
  1),
 (85,
  23,
  9,
  19,
  0,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -3896,
  13976,
  302,
  4198,
  1),
 (86,
  23,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -2114,
  12195,
  485,
  2599,
  1),
 (87,
  23,
  29,
  15,
  0,
  True,
  '2020-10-04T13:00:00Z',
  2,
  1,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  45,
  -1287,
  11046,
  215,
  1502,
  1),
 (88,
  24,
  2,
  8,
  0,
  False,
  '2020-09-12T11:30:00Z',
  0,
  3,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  55,
  0,
  491508,
  0,
  0,
  1),
 (89,
  24,
  9,
  19,
  2,
  True,
  '2020-09-19T19:00:00Z',
  2,
  1,
  2,
  88,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  8,
  '7.4',
  20.3,
  30.0,
  '5.8',
  54,
  -145334,
  357292,
  7716,
  153050,
  1),
 (90,
  24,
  23,
  11,
  0,
  False,
  '2020-09-28T19:00:00Z',
  3,
  1,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '0.0',
  0.0,
  0.0,
  '0.0',
  54,
  -81091,
  286264,
  14805,
  95896,
  1),
 (91,
  24,
  29,
  15,
  8,
  True,

In [35]:
cur.close()
conn.close()

In [48]:
cur.execute("""SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public'""")
for table in cur.fetchall():
    print(table)

('Table_FPL',)
('Table_FPLL',)
('table_fpl',)
('test',)

In [47]:
import psycopg2
conn=psycopg2.connect("dbname=FPLinNumbers user=postgres host=localhost password=mmmm57")
cur = conn.cursor()

In [25]:
cur.execute("DROP TABLE Table_FPL;")

UndefinedTable: ОШИБКА:  таблица "table_fpl" не существует