In [4]:
#Downloadting Data from fantasy.premierleague.com(FPL)
print('Start inputFPL:')
from time import time
start_module = time()
start = start_module

import constti
import Brr_functions
from bs4 import BeautifulSoup
import pandas as pd
import json
import numpy as np
from pathlib import Path

#List of useful links
url1 = "https://fantasy.premierleague.com/api/bootstrap-static/" #Data for line per PLayers with aggregate Data
url2 = "https://fantasy.premierleague.com/api/entry/698498/history/" #Data for FPL manager history
url3 = "https://fantasy.premierleague.com/api/event/6/live/" #Not used
url4 = "https://fantasy.premierleague.com/api/fixtures" #Fixtures Table
url5 = 'https://fantasy.premierleague.com/api/element-summary/191/' #Data for fixture 191

#Downloading the Table Which is Used for Players and Teams Lists only
p1 = constti.long_request(url1)  
data1 = p1.text
d1 = json.loads(data1)
bigTable = pd.DataFrame(d1['elements'])
bigTable['full_name'] = bigTable['first_name'] + ' ' + bigTable['second_name']

#Creating the Lists of Teams, Players and the Dictionary of Correspondence
teams = dict(zip(pd.DataFrame(d1['teams'])['id'],pd.DataFrame(d1['teams'])['name']))
players = dict(zip(bigTable['id'],bigTable['full_name']))
teamplayers = dict(zip(bigTable['id'],bigTable['team']))
team_number = len(teams)

#Downloading the Fixtures Table
p4 = constti.long_request(url4) 
d4 = json.loads(p4.text)
Fixtures = pd.DataFrame(d4)

#Calculating Last Gameweek which has already started
firstr = len(Fixtures)+1
lastr = 0
for i in range(len(Fixtures)):
    if Fixtures.at[i,'finished']==True:
        firstr = min(firstr, i)
        lastr = i
if firstr < len(Fixtures)+1:
    lastGW = int(Fixtures.at[lastr,'event'])
else: lastGW = 0
if lastr == len(Fixtures):
    lastGW = int(Fixtures.at[lastr,'event'])

#Creating the Main Table for FPL Source
Table = pd.DataFrame()
for i in bigTable['id']:
    url = 'https://fantasy.premierleague.com/api/element-summary/'+str(i)+'/'
    p = constti.long_request(url)
    d = json.loads(p.text)
    dd = pd.DataFrame(d['history'])
    Table = Table.append(dd, ignore_index=True)
if 'threat' in Table.columns:
    Table['threat'] = pd.to_numeric(Table['threat'])
    Table['creativity'] = pd.to_numeric(Table['creativity'])
    Table['team'] = [teamplayers[Table.at[i,'element']] for i in Table.index]

#Making Teams Template Table
Teams = pd.DataFrame()
Teams['id'] = pd.DataFrame(d1['teams'])['id']
Teams['Teams'] = pd.DataFrame(d1['teams'])['name']
Teams['XXX Target number XXX'] = np.zeros(team_number)
Teams['Matches'] = [len(Fixtures[Fixtures['finished']&((Fixtures['team_a']==i)|(Fixtures['team_h']==i))]) \
                              for i in range(1,team_number+1)]

#Making Players Template Table
Players = pd.DataFrame()
Players['id'] = bigTable['id']
Players['Name'] = constti.strip_accents_pdlist(pd.DataFrame(bigTable['full_name']))
Players['web_name'] = constti.strip_accents_pdlist(pd.DataFrame(bigTable['web_name']))
Players['Team number'] = [bigTable[bigTable['id'] == i]['team'].sum() for i in Players['id']]
Players['Team'] = [dict(zip(pd.DataFrame(d1['teams'])['id'],pd.DataFrame(d1['teams'])['name']))\
                   [Players.at[i,'Team number']] for i in Players.index]
Players['Team games'] = [Teams.at[Players.at[i,'Team number']-1,'Matches'] for i in Players.index]
if  not Table.empty:
    Players['Played'] = [len(Table[(Table['element']==i)&(Table['minutes']>0)]) \
                        for i in Players['id']]


print('\t Downloads FPL is over.\t It takes ' + str(time() - start) + ' sec')
start = time()


#Calculating Fixtures and Opponents
            
Team_all = pd.DataFrame()
Team_fixtures = pd.DataFrame()
Team_opponent_team = pd.DataFrame()
for j in range(lastGW,0,-1): 

    Team_all['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&\
    (Fixtures['event']==j)][['id', 'team_h', 'team_a']].values for i in range(1, team_number+1)]

    Team_fixtures['GW'+str(j)] = [list(pd.DataFrame(Team_all.at[i,'GW'+str(j)])[0]) for i in Team_all.index]

    Team_opponent_team['GW'+str(j)] = [[pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0]\
    if pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0] != i+1\
    else pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][1]\
    for v in range(len(pd.DataFrame(Team_all.at[i,'GW'+str(j)])))] for i in Team_all.index]

Player_all = pd.DataFrame()
Player_fixtures = pd.DataFrame()
Player_opponent_team = pd.DataFrame()
if  not Table.empty:
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team']].values for i in Players['id']]

        Player_fixtures['GW'+str(j)] = [list(pd.DataFrame(Player_all.at[i,'GW'+str(j)])[0]) for i in Player_all.index]

        Player_opponent_team['GW'+str(j)] = [list(pd.DataFrame(Player_all.at[i,'GW'+str(j)])[1])\
        for i in Player_all.index]

print('\t Fixtures are over.\t It takes ' + str(time() - start) + ' sec')


#Writing Tables to csv
Table.to_csv(Path('in/Table_FPL.csv'), index=False)
Fixtures.to_csv(Path('in/Fixtures.csv'), index=False)
Teams.to_csv(Path('in/Teams.csv'), index=False)
Players.to_csv(Path('in/Players.csv'), index=False)


Team_fixtures.to_json('in/Team_fixtures.txt')
Team_opponent_team.to_json('in/Team_opponent_team.txt')
Player_fixtures.to_json('in/Player_fixtures.txt')
Player_opponent_team.to_json('in/Player_opponent_team.txt')


# Team_fixtures.to_csv(Path('in/Team_fixtures.csv'), index=False)
# Team_opponent_team.to_csv(Path('in/Team_opponent_team.csv'), index=False)
# Player_fixtures.to_csv(Path('in/Player_fixtures.csv'), index=False)
# Player_opponent_team.to_csv(Path('in/Player_opponent_team.csv'), index=False)

print('inputFPL is over.\t It takes ' + str(time() - start_module) + ' sec\n')

if __name__ == '__main__':
    display(Table)

Start inputFPL:
	 Downloads FPL is over.	 It takes 128.16315031051636 sec
	 Fixtures are over.	 It takes 2.3335254192352295 sec
inputFPL is over.	 It takes 130.5436131954193 sec

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,...,influence,creativity,threat,ict_index,value,transfers_balance,selected,transfers_in,transfers_out,team
0,1,2,8,0,False,2020-09-12T11:30:00Z,0,3,1,0,...,0.0,0.0,0.0,0.0,70,0,76656,0,0,1
1,1,9,19,0,True,2020-09-19T19:00:00Z,2,1,2,0,...,0.0,0.0,0.0,0.0,69,-16828,68335,995,17823,1
2,2,2,8,0,False,2020-09-12T11:30:00Z,0,3,1,0,...,0.0,0.0,0.0,0.0,50,0,12184,0,0,1
3,2,9,19,0,True,2020-09-19T19:00:00Z,2,1,2,0,...,0.0,0.0,0.0,0.0,50,-4015,8234,51,4066,1
4,3,2,8,0,False,2020-09-12T11:30:00Z,0,3,1,0,...,0.0,0.0,0.0,0.0,55,0,69564,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,504,18,12,0,True,2020-09-21T19:15:00Z,NaN,NaN,2,0,...,0.0,0.0,0.0,0.0,55,-8462,81758,10433,18895,20
956,505,8,15,5,False,2020-09-14T17:00:00Z,0,2,1,90,...,15.2,1.5,0.0,1.7,50,0,15739,0,0,20
957,505,18,12,0,True,2020-09-21T19:15:00Z,NaN,NaN,2,0,...,0.0,0.0,0.0,0.0,50,3066,23118,8299,5233,20
958,515,8,15,1,False,2020-09-14T17:00:00Z,0,2,1,4,...,1.2,0.8,0.0,0.2,50,0,2432,0,0,20
959,515,18,12,0,True,2020-09-21T19:15:00Z,NaN,NaN,2,0,...,0.0,0.0,0.0,0.0,50,-276,2901,288,564,20

In [2]:
Teams

    id           Teams  XXX Target number XXX  Matches
0    1         Arsenal                    0.0        2
1    2     Aston Villa                    0.0        0
2    3        Brighton                    0.0        1
3    4         Burnley                    0.0        0
4    5         Chelsea                    0.0        1
5    6  Crystal Palace                    0.0        2
6    7         Everton                    0.0        2
7    8          Fulham                    0.0        2
8    9       Leicester                    0.0        1
9   10           Leeds                    0.0        2
10  11       Liverpool                    0.0        1
11  12        Man City                    0.0        0
12  13         Man Utd                    0.0        1
13  14       Newcastle                    0.0        1
14  15   Sheffield Utd                    0.0        1
15  16     Southampton                    0.0        1
16  17           Spurs                    0.0        1
17  18       West Brom                    0.0        2
18  19        West Ham                    0.0        2
19  20          Wolves                    0.0        1

In [10]:
bigTable[bigTable['team']==2]

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,full_name
31,NaN,NaN,98980,0,0,0,0,0,1,0.0,...,29,348,46,NaN,,NaN,,NaN,,Emiliano Martínez
32,0.0,0.0,21205,0,0,0,0,0,1,0.0,...,16,319,35,NaN,,NaN,,NaN,,Tom Heaton
33,NaN,NaN,37339,0,0,0,0,0,2,0.0,...,96,322,118,NaN,,NaN,,NaN,,Ahmed El Mohamady
34,NaN,NaN,40564,0,0,0,0,0,3,0.0,...,96,325,131,NaN,,NaN,,NaN,,Henri Lansbury
35,NaN,NaN,47390,0,0,0,0,0,2,0.0,...,101,331,122,NaN,,NaN,,NaN,,Neil Taylor
36,NaN,NaN,79852,0,0,0,0,0,1,0.0,...,6,280,25,NaN,,NaN,,NaN,,Jed Steer
37,NaN,NaN,85242,0,0,0,0,0,3,0.0,...,196,507,201,1.0,,1.0,,NaN,,Conor Hourihane
38,NaN,NaN,89274,0,0,0,0,0,3,0.0,...,197,508,202,NaN,,NaN,,NaN,,José Ignacio Peleteiro Romallo
39,NaN,NaN,98770,0,0,0,0,0,1,0.0,...,7,282,26,NaN,,NaN,,NaN,,Ørjan Nyland
40,0.0,0.0,108156,0,0,0,0,0,2,0.0,...,118,354,134,NaN,,NaN,,NaN,,Bjorn Engels
41,NaN,NaN,114283,0,0,0,0,0,3,0.0,...,210,527,212,2.0,,7.0,,3.0,,Jack Grealish
42,NaN,NaN,122806,0,0,0,0,0,3,0.0,...,179,485,192,3.0,,6.0,,NaN,,John McGinn
43,NaN,NaN,123354,0,0,0,0,0,2,0.0,...,121,358,137,NaN,,NaN,,NaN,,Kortney Hause
44,NaN,NaN,148508,0,0,0,0,0,3,0.0,...,180,487,193,6.0,,3.0,,NaN,,Mahmoud Ahmed Ibrahim Hassan
45,NaN,NaN,149484,0,0,0,0,0,2,0.0,...,171,445,174,NaN,,NaN,,NaN,,Tyrone Mings
46,NaN,NaN,169359,0,0,0,0,0,2,0.0,...,128,365,143,4.0,,5.0,,NaN,,Matt Targett
47,0.0,0.0,184386,0,0,0,0,0,2,0.0,...,134,372,148,NaN,,NaN,,NaN,,James Bree
48,NaN,NaN,184704,0,0,0,0,0,3,0.0,...,107,373,138,NaN,,NaN,,NaN,,Marvelous Nakamba
49,NaN,NaN,193488,0,0,0,0,0,3,0.0,...,200,517,205,5.0,,2.0,,2.0,,Anwar El Ghazi
50,NaN,NaN,199798,0,0,0,0,0,2,0.0,...,138,377,150,NaN,,NaN,,NaN,,Ezri Konsa Ngoyo
51,NaN,NaN,203368,0,0,0,0,0,2,0.0,...,139,378,151,NaN,,NaN,,NaN,,Frédéric Guilbert
52,0.0,0.0,213345,0,0,0,0,0,4,0.0,...,61,518,61,NaN,,NaN,,1.0,,Wesley Moraes
53,NaN,NaN,217487,0,0,0,0,0,4,0.0,...,62,519,62,NaN,,NaN,,NaN,,Mbwana Samatta
54,NaN,NaN,221239,0,0,0,0,0,4,0.0,...,40,385,40,NaN,,NaN,,NaN,,Keinan Davis
55,0.0,0.0,223349,0,0,0,0,0,4,0.0,...,41,388,41,NaN,,NaN,,NaN,,Indiana Vassilev
56,NaN,NaN,230046,0,0,0,0,0,3,0.0,...,161,458,180,NaN,,4.0,,NaN,,Douglas Luiz Soares de Paulo
57,NaN,NaN,199796,0,0,0,0,0,2,0.0,...,173,454,176,NaN,,NaN,,NaN,,Matthew Cash
58,NaN,NaN,178301,0,0,0,0,0,4,0.0,...,60,516,60,NaN,,NaN,,NaN,,Ollie Watkins