In [3]:
''' Rarely needed calculations (Optional)

    Calculate tables if Fixtures changes(sys.argv[1] == 'full')
    
    Sources:    '{folder}in/Fixtures.csv'
                '{folder}in/Teams.csv'
                f'{folder}in/Table_FPL.csv'
                f'{folder}in/Players.csv'
                
    Writes:    'in/Team_fixtures.csv'
                'in/Team_opponent_team.csv'
                'in/Team_played_fixtures.csv'
                'in/Team_upcoming_fixtures.csv'
                'mid/Team_home.csv'
                'mid/Team_scored.csv'
                'mid/Team_scores.txt'
                

    
'''



import pandas as pd
import numpy as np
from pathlib import Path
from Brr_functions import no_lists,to_lists, del_empty_col
import constti

# DATA input
year = ''
if year=='': folder = ''
else: folder = f'history/{year}/'

Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv'))
Teams = pd.read_csv(Path(f'{folder}in/Teams.csv'))
Table = pd.read_csv(Path(f'{folder}in/Table_FPL.csv'))
Players = pd.read_csv(Path(f'{folder}in/Players.csv'))


# Team_all, 
Team_all = pd.DataFrame()
Team_opponent_team = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    '''
        Team_all - contains [number of fixture, home team id, away team id]
        Team_fixtures - contains [number of fixture]
        Team_played_fixtures - contains [number of future fixture], future or empty GW deleted
        Team_upcoming_fixtures - contains [number of played fixture], played or empty GW deleted
        Team_opponent_team - [opponent team id]
    '''

    Team_all['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['id', 'team_h', 'team_a']].values for i in range(1, len(Teams)+1)]

    Team_opponent_team['GW'+str(j)] = [[pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0]\
    if pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0] != i+1\
    else pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][1]\
    for v in range(len(pd.DataFrame(Team_all.at[i,'GW'+str(j)])))] for i in Team_all.index]
    

Team_opponent_team = no_lists(Team_opponent_team[Team_opponent_team.columns[::-1]])

Team_fixtures = Team_all.applymap(lambda x: [x[i][0] for i in range(len(x))])
Team_fixtures = no_lists(Team_fixtures[Team_fixtures.columns[::-1]])
    
#calculating home/away table with 1/0 and NaN
Team_home = no_lists(Team_all.applymap(lambda x: list(x))).applymap(lambda x: np.nan if type(x)==float else x[1]-1).\
apply(lambda x: x==list(range(len(Team_all)))).applymap(lambda x: 1 if x else 0)\
+no_lists(Team_fixtures)-no_lists(Team_fixtures)#to add NaN

Team_home = Team_home[Team_home.columns[::-1]]#making right order



Team_scores = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    Team_scores['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['team_h_score','team_a_score']].values for i in range(1, len(Teams)+1)]
Team_scores = Team_scores[Team_scores.columns[::-1]]

#TSS = Team_scores

Team_scored = (no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[0])*Team_home) +\
(no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[1])*(1-Team_home))
    
del_empty_col(Team_fixtures)

no_lists(Team_fixtures)

del_empty_col(Team_scored)

#Same as in "medium"
Team_played_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
if Fixtures[Fixtures['id']==x]['finished'].iloc[0] else np.nan)
Team_upcoming_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
if Fixtures[Fixtures['id']==x]['finished'].iloc[0]==False else np.nan)








Player_all = pd.DataFrame()
Player_fixtures = pd.DataFrame(columns = Team_fixtures.columns)
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_opponent_team = pd.DataFrame(columns = Team_opponent_team.columns)
if  not Table.empty:
    lastGW = Table['round'].max()
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team']].values for i in Players['id']]
Player_all = no_lists(Player_all[Player_all.columns[::-1]])

for i in Players.index:
    Player_fixtures = Player_fixtures.append(Team_fixtures.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)
    Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)
    Player_opponent_team = Player_opponent_team.append(Team_opponent_team.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)

Player_played_fixtures = Player_all.applymap(lambda x: x[0] if type(x) in {list, np.ndarray} else np.nan)
Pot = Player_all.applymap(lambda x: x[1] if type(x) in {list, np.ndarray} else np.nan) #Opponents played against (Player Opponent Team)
for i in Player_opponent_team.index:
    for j in Player_opponent_team.columns:
        if j in Player_all.columns:
            if int(j[2:])!=lastGW:
                Player_opponent_team.at[i,j] = Pot.at[i,j]
                Player_fixtures.at[i,j] = Player_played_fixtures.at[i,j]

def Phome(col):
    '''Function for apply to get home/away for players based on home/away of opposed team'''
    return [np.nan if np.isnan(col[i]) else 1 if Team_home.at[int(col[i])-1, col.name]==0 else 0 for i in range(len(col))]
Player_home = Player_opponent_team.apply(Phome, axis=0)




#Writing
Team_fixtures.to_csv(Path('in/Team_fixtures.csv'), index=False)
Team_opponent_team.to_csv(Path('in/Team_opponent_team.csv'), index=False)
Team_played_fixtures.to_csv(Path('in/Team_played_fixtures.csv'), index=False)
Team_upcoming_fixtures.to_csv(Path('in/Team_upcoming_fixtures.csv'), index=False)
Team_home.to_csv(Path('mid/Team_home.csv'), index=False)
Team_scored.to_csv(Path('mid/Team_scored.csv'), index=False)


Team_scores.to_json(Path('mid/Team_scores.txt'))

'End'
# Team_played_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
# if Fixtures[Fixtures['id']==x]['finished'].iloc[0] else np.nan)
# Team_upcoming_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
# if Fixtures[Fixtures['id']==x]['finished'].iloc[0]==False else np.nan)

# Team_played_fixtures

Player_played_fixtures
Team_opponent_team['GW18']
#Player_all

0      6.0
1      NaN
2     12.0
3     13.0
4      NaN
5      1.0
6     20.0
7     17.0
8      NaN
9      NaN
10     NaN
11     3.0
12     4.0
13    15.0
14    14.0
15     NaN
16     8.0
17     NaN
18     NaN
19     7.0
Name: GW18, dtype: float64

In [77]:
# for i in Players.index:
#     Player_fixtures = Player_fixtures.append(Team_fixtures.iloc[Players.at[i,'Team number']-1],\
#     ignore_index=True)
#     Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[i,'Team number']-1],\
#     ignore_index=True)
#     Player_opponent_team = Player_opponent_team.append(Team_opponent_team.iloc[Players.at[i,'Team number']-1],\
#     ignore_index=True)

# Player_played_fixtures = Player_all.applymap(lambda x: x[0] if type(x) in {list, np.ndarray} else np.nan)
# Pot = Player_all.applymap(lambda x: x[1] if type(x) in {list, np.ndarray} else np.nan) #Opponents played against (Player Opponent Team)
# for i in Player_opponent_team.index:
#     for j in Player_opponent_team.columns:
#         if j in Player_all.columns:
#             if int(j[2:])!=lastGW:
#                 Player_opponent_team.at[i,j] = Pot.at[i,j]
#                 Player_fixtures.at[i,j] = Player_played_fixtures.at[i,j]
                
x = pd.DataFrame(np.nan, index=Player_all.index, columns=Team_fixtures.columns)
Player_played_fixtures = Player_all.applymap(lambda x: x[0] if type(x) in {list, np.ndarray} else np.nan)
Player_upcoming_fixtures = x.apply(lambda y: Team_upcoming_fixtures.iloc[Players.at[y.name,'Team number']-1], axis=1)
Player_fixtures = x.apply(lambda x: Team_fixtures.iloc[Players.at[x.name,'Team number']-1], axis=1)
Player_fixtures[Player_played_fixtures.columns] = Player_played_fixtures
# Player_fixtures = Player_fixturesX.merge(Player_played_fixtures)
Player_fixtures[f'GW{lastGW}'] = [Player_upcoming_fixtures[f'GW{lastGW}'][i] \
if np.isnan(Player_played_fixtures[f'GW{lastGW}'][i]) else Player_played_fixtures[f'GW{lastGW}'][i] \
for i in range(len(Players))]

Player_opponent_team = x.apply(lambda x: Team_opponent_team.iloc[Players.at[x.name,'Team number']-1], axis=1)
Pot = Player_all.applymap(lambda x: x[1] if type(x) in {list, np.ndarray} else np.nan) #Opponents played against
Player_opponent_team[Pot.columns]  = Pot
#Player_opponent_teamX = Pot.merge(Player_opponent_teamX)

Player_fixtures

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
1,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
2,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
3,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
4,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
5,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
6,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
7,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
8,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
9,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
10,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
11,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
12,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
13,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
14,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
15,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
16,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
17,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
18,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
19,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
20,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
21,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
22,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
23,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
24,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
25,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
26,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
27,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
28,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
29,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
596,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
597,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
598,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
599,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
600,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
601,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
602,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
603,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
604,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
605,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
606,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
607,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
608,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
609,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
610,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
611,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
612,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
613,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
614,NaN,NaN,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
615,NaN,NaN,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
616,NaN,NaN,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
617,NaN,NaN,NaN,NaN,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
618,NaN,NaN,NaN,NaN,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0

In [75]:
constti.differences(Player_upcoming_fixtures, Player_upcoming_fixturesX)

Empty DataFrame
Columns: []
Index: []

In [53]:
Pot.merge(Player_opponent_teamX, how='outer')
#how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’
Player_opponent_teamX

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
1,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
2,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
3,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
4,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
5,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
6,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
7,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
8,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
9,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
10,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
11,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
12,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
13,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
14,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
15,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
16,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
17,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
18,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
19,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
20,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
21,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
22,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
23,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
24,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
25,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
26,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
27,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
28,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
29,8.0,19.0,11.0,15.0,12.0,9.0,13.0,2.0,10.0,20.0,...,19.0,11.0,15.0,8.0,7.0,14.0,18.0,5.0,6.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16510,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16511,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16512,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16513,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16514,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16515,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16516,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16517,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16518,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16519,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16520,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16521,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16522,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16523,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16524,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16525,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16526,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16527,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16528,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16529,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16530,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16531,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16532,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16533,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16534,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16535,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16536,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16537,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16538,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0
16539,15.0,12.0,19.0,8.0,10.0,14.0,6.0,9.0,16.0,1.0,...,12.0,19.0,8.0,15.0,4.0,18.0,3.0,17.0,7.0,13.0

In [27]:
'''
    Player_all - contains [number of fixture, opponent team id] for played fixtures
    PLayer_played_fixtures - contains [number of fixture played], future or empty GW deleted
    PLayer_upcoming_fixtures - contains [number of upcoming fixture], played or empty GW deleted
    Team_opponent_team - [opponent team id]
'''
Team_opponent_team = to_lists(Team_opponent_team[Team_opponent_team.columns[::-1]])
Team_upcoming_fixtures = to_lists(Team_upcoming_fixtures[Team_upcoming_fixtures.columns[::-1]])



Player_all = pd.DataFrame()
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_opponent_team = pd.DataFrame(columns = Team_opponent_team.columns)
if  not Table.empty:
    lastGW = Table['round'].max()
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team']].values for i in Players['id']]

for i in Players.index:
    Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)
    Player_opponent_team = Player_opponent_team.append(Team_opponent_team.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)

Player_played_fixtures = Player_all.applymap(lambda x: [x[i][0] for i in range(len(x))])
Pot = Player_all.applymap(lambda x: [x[i][1] for i in range(len(x))]) #Opponents played against (Player Opponent Team)
for i in Player_opponent_team.index:
    for j in Player_opponent_team.columns:
        if j in Player_all.columns:
            if int(j[2:])!=lastGW:
                Player_opponent_team.at[i,j] = Pot.at[i,j]

def Phome(col):
    '''Function for apply to get home/away for players based on home/away of opposed team'''
    return [np.nan if np.isnan(col[i]) else 1 if Team_home.at[int(col[i])-1, col.name]==0 else 0 for i in range(len(col))]
Player_home = no_lists(Player_opponent_team).apply(Phome, axis=0)

Player_home = Player_home[Player_home.columns[::-1]] #making right order

In [30]:
Player_all = pd.DataFrame()
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_opponent_team = pd.DataFrame(columns = Team_opponent_team.columns)
if  not Table.empty:
    lastGW = Table['round'].max()
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team']].values for i in Players['id']]
Player_all = no_lists(Player_all)

for i in Players.index:
    Player_upcoming_fixtures = Player_upcoming_fixtures.append(Team_upcoming_fixtures.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)
    Player_opponent_team = Player_opponent_team.append(Team_opponent_team.iloc[Players.at[i,'Team number']-1],\
    ignore_index=True)

Player_played_fixtures = Player_all.applymap(lambda x: x[0] if type(x) in {list, np.ndarray} else np.nan)
Pot = Player_all.applymap(lambda x: x[1] if type(x) in {list, np.ndarray} else np.nan) #Opponents played against (Player Opponent Team)
for i in Player_opponent_team.index:
    for j in Player_opponent_team.columns:
        if j in Player_all.columns:
            if int(j[2:])!=lastGW:
                Player_opponent_team.at[i,j] = Pot.at[i,j]

def Phome(col):
    '''Function for apply to get home/away for players based on home/away of opposed team'''
    return [np.nan if np.isnan(col[i]) else 1 if Team_home.at[int(col[i])-1, col.name]==0 else 0 for i in range(len(col))]
Player_home = Player_opponent_team.apply(Phome, axis=0)

#Player_home = Player_home[Player_home.columns[::-1]] #making right order

'End'

TypeError: ("int() argument must be a string, a bytes-like object or a number, not 'list'", 'occurred at index GW38')

In [6]:
Player_opponent_team
Team_opponent_team
Pot
no_lists(Player_all)
Player_fixtures

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
1,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
2,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
3,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
4,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
5,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
6,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
7,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
8,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
9,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
10,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
11,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
12,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
13,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
14,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
15,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
16,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
17,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
18,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
19,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
20,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
21,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
22,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
23,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
24,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
25,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
26,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
27,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
28,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
29,2.0,9.0,23.0,29.0,44.0,49.0,64.0,69.0,82.0,89.0,...,288.0,289.0,305.0,309.0,319.0,335.0,339.0,354.0,362.0,369.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
596,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
597,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
598,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
599,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
600,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
601,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
602,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
603,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
604,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
605,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
606,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
607,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
608,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
609,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
610,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
611,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
612,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
613,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
614,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
615,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
616,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
617,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
618,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
619,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
620,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
621,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
622,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
623,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0
624,8.0,18.0,28.0,38.0,42.0,58.0,68.0,74.0,88.0,89.0,...,284.0,298.0,302.0,318.0,328.0,338.0,348.0,358.0,363.0,378.0

In [5]:
Player_all
Team_played_fixtures

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,2.0,9,23,29,44,49,64,69,82,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,10,22,30,43,50,59,69,79,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7.0,16,19,32,40,51,67,70,79,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,14,20,36,48,52,60,70,80,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7.0,11,27,31,39,55,60,71,85,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,15,21,31,40,53,68,72,80,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4.0,12,21,32,41,56,65,73,81,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.0,13,22,38,46,53,61,78,81,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5.0,14,24,34,43,49,62,74,83,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3.0,13,25,33,42,50,62,72,82,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3.0,11,23,30,41,54,63,75,83,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,18,24,33,44,57,66,75,87,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,15,19,35,45,55,64,73,84,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,16,26,36,45,58,65,76,85,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,8.0,10,25,29,46,54,66,71,86,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1.0,17,20,37,39,56,59,76,88,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4.0,17,26,35,47,52,67,77,87,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5.0,12,27,37,48,51,61,77,84,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,6.0,9,28,34,47,57,63,78,86,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,8.0,18,28,38,42,58,68,74,88,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN