In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from Brr_functions import no_lists, del_empty_col

# DATA input
year = ''
if year=='': folder = ''
else: folder = f'history/{year}/'

Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv'))
Teams = pd.read_csv(Path(f'{folder}in/Teams.csv'))



# Team_all, 
Team_all = pd.DataFrame()
Team_opponent_team = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    '''
        Team_all - contains [number of fixture, home team id, away team id]
        Team_fixtures - contains [number of fixture]
        Team_played_fixtures - contains [number of future fixture], future or empty GW deleted
        Team_upcoming_fixtures - contains [number of played fixture], played or empty GW deleted
        Team_opponent_team - [opponent team id]
    '''

    Team_all['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['id', 'team_h', 'team_a']].values for i in range(1, len(Teams)+1)]

    Team_opponent_team['GW'+str(j)] = [[pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0]\
    if pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0] != i+1\
    else pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][1]\
    for v in range(len(pd.DataFrame(Team_all.at[i,'GW'+str(j)])))] for i in Team_all.index]
    


Team_fixtures = Team_all.applymap(lambda x: [x[i][0] for i in range(len(x))])
    
#calculating home/away table with 1/0 and NaN
Team_home = no_lists(Team_all.applymap(lambda x: list(x))).applymap(lambda x: np.nan if type(x)==float else x[1]-1).\
apply(lambda x: x==list(range(len(Team_all)))).applymap(lambda x: 1 if x else 0)\
+no_lists(Team_fixtures)-no_lists(Team_fixtures)#to add NaN

Team_home = Team_home[Team_home.columns[::-1]]#making right order



Team_scores = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    Team_scores['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['team_h_score','team_a_score']].values for i in range(1, len(Teams)+1)]
Team_scores = Team_scores[Team_scores.columns[::-1]]

TSS = Team_scores

Team_scored = (no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[0])*Team_home) +\
(no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[1])*(1-Team_home))
    
del_empty_col(Team_fixtures)

no_lists(Team_fixtures)

del_empty_col(Team_scored)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\missing.py:48: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask = arr == x

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,GW11,GW12,GW13,GW14,GW15
0,3.0,2.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,3.0
1,NaN,1.0,3.0,7.0,1.0,0.0,3.0,3.0,1.0,1.0,NaN,1.0,0.0,3.0,3.0
2,1.0,3.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,2.0
3,NaN,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0
4,3.0,0.0,3.0,4.0,3.0,0.0,3.0,4.0,2.0,0.0,3.0,0.0,1.0,3.0,1.0
5,1.0,3.0,1.0,0.0,1.0,2.0,0.0,4.0,0.0,0.0,5.0,1.0,1.0,0.0,0.0
6,1.0,5.0,2.0,4.0,2.0,0.0,1.0,1.0,3.0,0.0,1.0,1.0,2.0,2.0,1.0
7,0.0,3.0,0.0,0.0,1.0,1.0,2.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0
8,3.0,4.0,5.0,0.0,0.0,1.0,4.0,1.0,0.0,1.0,2.0,3.0,0.0,2.0,2.0
9,3.0,4.0,1.0,1.0,0.0,3.0,1.0,1.0,0.0,1.0,1.0,1.0,5.0,2.0,1.0
10,4.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,2.0,7.0,1.0
11,NaN,3.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,5.0,2.0,0.0,1.0,1.0,2.0
12,NaN,1.0,3.0,1.0,4.0,0.0,0.0,3.0,1.0,3.0,3.0,0.0,3.0,6.0,2.0
13,2.0,0.0,1.0,3.0,1.0,1.0,2.0,0.0,0.0,2.0,NaN,2.0,2.0,1.0,0.0
14,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
15,0.0,2.0,1.0,2.0,3.0,2.0,4.0,2.0,1.0,2.0,2.0,3.0,1.0,0.0,0.0
16,0.0,5.0,1.0,6.0,3.0,1.0,2.0,1.0,2.0,0.0,2.0,1.0,1.0,0.0,1.0
17,0.0,2.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
18,0.0,1.0,4.0,3.0,3.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,0.0,2.0
19,2.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,1.0,2.0,0.0,0.0,2.0,1.0,1.0

In [31]:
Team_scores = TSS
no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[0]).columns
#Team_home.columns

Index(['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8', 'GW9', 'GW10',
       'GW11', 'GW12', 'GW13', 'GW14', 'GW15', 'GW16', 'GW17', 'GW18', 'GW19*',
       'GW19', 'GW20', 'GW21', 'GW22', 'GW23', 'GW24', 'GW25', 'GW26', 'GW27',
       'GW28', 'GW29', 'GW30', 'GW31', 'GW32', 'GW33', 'GW34', 'GW35', 'GW36',
       'GW37', 'GW38'],
      dtype='object')

In [26]:
TSS

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,"[[0.0, 3.0]]","[[2.0, 1.0]]","[[3.0, 1.0]]","[[2.0, 1.0]]","[[1.0, 0.0]]","[[0.0, 1.0]]","[[0.0, 1.0]]","[[0.0, 3.0]]","[[0.0, 0.0]]","[[1.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
1,[],"[[1.0, 0.0]]","[[0.0, 3.0]]","[[7.0, 2.0]]","[[0.0, 1.0]]","[[0.0, 3.0]]","[[3.0, 4.0]]","[[0.0, 3.0]]","[[1.0, 2.0]]","[[2.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
2,"[[1.0, 3.0]]","[[0.0, 3.0]]","[[2.0, 3.0]]","[[4.0, 2.0]]","[[1.0, 1.0]]","[[1.0, 1.0]]","[[2.0, 1.0]]","[[0.0, 0.0]]","[[1.0, 2.0]]","[[1.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
3,[],"[[4.0, 2.0]]","[[0.0, 1.0]]","[[3.0, 1.0]]","[[0.0, 0.0]]","[[0.0, 1.0]]","[[0.0, 3.0]]","[[0.0, 0.0]]","[[1.0, 0.0]]","[[5.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
4,"[[1.0, 3.0]]","[[0.0, 2.0]]","[[3.0, 3.0]]","[[4.0, 0.0]]","[[3.0, 3.0]]","[[0.0, 0.0]]","[[0.0, 3.0]]","[[4.0, 1.0]]","[[0.0, 2.0]]","[[0.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
5,"[[1.0, 0.0]]","[[1.0, 3.0]]","[[1.0, 2.0]]","[[4.0, 0.0]]","[[1.0, 1.0]]","[[1.0, 2.0]]","[[2.0, 0.0]]","[[4.0, 1.0]]","[[1.0, 0.0]]","[[0.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
6,"[[0.0, 1.0]]","[[5.0, 2.0]]","[[1.0, 2.0]]","[[4.0, 2.0]]","[[2.0, 2.0]]","[[2.0, 0.0]]","[[2.0, 1.0]]","[[1.0, 3.0]]","[[2.0, 3.0]]","[[0.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
7,"[[0.0, 3.0]]","[[4.0, 3.0]]","[[0.0, 3.0]]","[[1.0, 0.0]]","[[1.0, 1.0]]","[[1.0, 2.0]]","[[2.0, 0.0]]","[[1.0, 0.0]]","[[2.0, 3.0]]","[[1.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
8,"[[0.0, 3.0]]","[[4.0, 2.0]]","[[2.0, 5.0]]","[[0.0, 3.0]]","[[0.0, 1.0]]","[[0.0, 1.0]]","[[1.0, 4.0]]","[[1.0, 0.0]]","[[3.0, 0.0]]","[[1.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
9,"[[4.0, 3.0]]","[[4.0, 3.0]]","[[0.0, 1.0]]","[[1.0, 1.0]]","[[0.0, 1.0]]","[[0.0, 3.0]]","[[1.0, 4.0]]","[[4.0, 1.0]]","[[0.0, 0.0]]","[[0.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
10,"[[4.0, 3.0]]","[[0.0, 2.0]]","[[3.0, 1.0]]","[[7.0, 2.0]]","[[2.0, 2.0]]","[[2.0, 1.0]]","[[2.0, 1.0]]","[[1.0, 1.0]]","[[3.0, 0.0]]","[[1.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
11,[],"[[1.0, 3.0]]","[[2.0, 5.0]]","[[1.0, 1.0]]","[[1.0, 0.0]]","[[1.0, 1.0]]","[[0.0, 1.0]]","[[1.0, 1.0]]","[[2.0, 0.0]]","[[5.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
12,[],"[[1.0, 3.0]]","[[2.0, 3.0]]","[[1.0, 6.0]]","[[1.0, 4.0]]","[[0.0, 0.0]]","[[0.0, 1.0]]","[[1.0, 3.0]]","[[1.0, 0.0]]","[[2.0, 3.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
13,"[[0.0, 2.0]]","[[0.0, 3.0]]","[[1.0, 1.0]]","[[3.0, 1.0]]","[[1.0, 4.0]]","[[1.0, 1.0]]","[[2.0, 1.0]]","[[2.0, 0.0]]","[[0.0, 2.0]]","[[0.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
14,"[[0.0, 2.0]]","[[1.0, 0.0]]","[[0.0, 1.0]]","[[2.0, 1.0]]","[[1.0, 1.0]]","[[2.0, 1.0]]","[[0.0, 1.0]]","[[4.0, 1.0]]","[[0.0, 1.0]]","[[1.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
15,"[[1.0, 0.0]]","[[2.0, 5.0]]","[[0.0, 1.0]]","[[2.0, 0.0]]","[[3.0, 3.0]]","[[2.0, 0.0]]","[[3.0, 4.0]]","[[2.0, 0.0]]","[[1.0, 1.0]]","[[2.0, 3.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
16,"[[0.0, 1.0]]","[[2.0, 5.0]]","[[1.0, 1.0]]","[[1.0, 6.0]]","[[3.0, 3.0]]","[[0.0, 1.0]]","[[2.0, 1.0]]","[[0.0, 1.0]]","[[2.0, 0.0]]","[[0.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
17,"[[0.0, 3.0]]","[[5.0, 2.0]]","[[3.0, 3.0]]","[[2.0, 0.0]]","[[0.0, 0.0]]","[[1.0, 1.0]]","[[2.0, 0.0]]","[[0.0, 1.0]]","[[1.0, 0.0]]","[[1.0, 0.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
18,"[[0.0, 2.0]]","[[2.0, 1.0]]","[[4.0, 0.0]]","[[0.0, 3.0]]","[[3.0, 3.0]]","[[1.0, 1.0]]","[[2.0, 1.0]]","[[1.0, 0.0]]","[[0.0, 1.0]]","[[2.0, 1.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"
19,"[[0.0, 2.0]]","[[1.0, 3.0]]","[[4.0, 0.0]]","[[1.0, 0.0]]","[[0.0, 1.0]]","[[1.0, 1.0]]","[[2.0, 0.0]]","[[1.0, 0.0]]","[[1.0, 1.0]]","[[1.0, 2.0]]",...,"[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]","[[nan, nan]]"