In [1]:
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from pathlib import Path
from Brr_functions import no_lists
import json

In [9]:
with open(Path('mid/FPL/Team_xG.txt'), 'r') as file:
    Team_xG = pd.DataFrame(json.loads(file.read()))
    Team_xG.index = pd.to_numeric(Team_xG.index)
    Team_xG = Team_xG.sort_index()
    
with open(Path('mid/FPL/Team_xG_Ad.txt'), 'r') as file:
    Team_xG_Ad = pd.DataFrame(json.loads(file.read()))
    Team_xG_Ad.index = pd.to_numeric(Team_xG_Ad.index)
    Team_xG_Ad = Team_xG_Ad.sort_index()
    
with open(Path('mid/FPL/Team_Opponent_xG.txt'), 'r') as file:
    Team_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    Team_Opponent_xG.index = pd.to_numeric(Team_Opponent_xG.index)
    Team_Opponent_xG = Team_Opponent_xG.sort_index()
    
with open(Path('mid/FPL/Team_oppdefence_coeff.txt'), 'r') as file:
    Team_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    Team_oppdefence_coeff.index = pd.to_numeric(Team_oppdefence_coeff.index)
    Team_oppdefence_coeff = Team_oppdefence_coeff.sort_index()
    
threatAllowedAv = no_lists(Team_Opponent_xG[Team_Opponent_xG.columns[4:]]).mean(axis=1).mean()
#lastGW = len(Team_xG.columns[4:])
Team_oppdefence_coeff
Team_xG_Ad

,id,Teams,xG av adj,Matches,GW8 adj,GW7 adj,GW6 adj,GW5 adj,GW4 adj,GW3 adj,GW2 adj,GW1 adj
0,1,Arsenal,133.506720,8,[115.93643071],[62.90070059],[190.3782441278],[160.0350553506],[101.9891954449],[89.4487716106],[145.342991683],[202.0223672322]
1,2,Aston Villa,237.110643,7,[317.0103928571],[373.4807557118],[123.5118446602],[155.8652291105],[352.5333939945],[166.3201385403],[171.0527451162],[]
2,3,Brighton,162.392604,8,[237.5952546296],[129.0509987602],[61.1621153846],[222.7340425532],[166.9882301466],[219.6193952802],[99.3303756797],[162.6604207959]
3,4,Burnley,110.418210,7,[67.2525683272],[35.7059460284],[145.7798319328],[93.728956044],[95.042733564],[135.0192819483],[200.3981517135],[]
4,5,Chelsea,187.327190,8,[229.6764558837],[168.9938078704],[92.751880531],[242.8169344715],[188.1875379939],[227.9678846154],[96.0258871702],[252.197131227]
5,6,Crystal Palace,133.494881,8,[124.3138696255],[193.3392097264],[240.3369541211],[48.7581120372],[67.4445647202],[131.8827499453],[178.0409660767],[83.8426186292]
6,7,Everton,170.937525,8,[86.355199115],[141.4921898171],[103.4421918152],[155.2199272066],[309.3618143051],[131.8221884498],[248.6200274725],[191.1866648299]
7,8,Fulham,127.386381,8,[177.1699241683],[140.5934340659],[145.4589665653],[125.2780668457],[114.2458966565],[161.3835115483],[114.6895700416],[40.2716785714]
8,9,Leicester,136.577372,8,[119.7384878419],[141.1563938974],[59.8912142857],[140.0512082977],[74.2628424658],[164.0359317343],[225.8828125],[167.6000824176]
9,10,Leeds,183.927760,8,[92.7300911854],[153.6385829804],[300.5072284003],[195.5362462006],[326.7382380074],[145.3546801222],[128.0055516514],[128.9114649682]
10,11,Liverpool,238.567372,8,[168.0368081181],[154.8910714286],[190.3262938617],[264.7142966528],[244.8577416595],[276.7387142857],[300.1944351273],[308.7796116505]
11,12,Man City,179.905206,7,[99.9721565059],[186.3109712064],[206.8750611546],[199.2931785714],[198.9021914008],[163.658490566],[204.3243920973],[]
12,13,Man Utd,167.803628,7,[134.7291402319],[112.5541785714],[195.7214819332],[262.2607760751],[75.2797492768],[206.8016476061],[187.2784194529],[]
13,14,Newcastle,108.751715,8,[50.0877981421],[149.909888427],[74.6992401216],[113.0080383481],[116.287818287],[102.7628323461],[72.2965109517],[190.9615949119]
14,15,Sheffield Utd,112.830210,8,[104.4729531941],[68.014898524],[215.7293903549],[103.6235418131],[72.2825],[145.9685436893],[51.9395209581],[140.6103343465]
15,16,Southampton,136.384404,8,[145.7798319328],[69.561858426],[134.7291402319],[234.0723128526],[123.9128571429],[49.3595775463],[209.1104146577],[124.5492401216]
16,17,Spurs,196.308668,8,[175.5432142857],[151.3182787362],[141.3859085648],[153.8301736791],[331.561320059],[260.8315620366],[178.5738890284],[177.4249945307]
17,18,West Brom,111.610715,8,[152.9493318639],[96.6572532878],[131.142508238],[144.7323206019],[71.8651016821],[138.8564567769],[78.7501312623],[77.9326145553]
18,19,West Ham,161.176014,8,[158.4830639494],[101.2875796178],[74.6830258303],[233.0087477614],[214.8713515595],[196.6347644377],[161.0867142857],[149.3528670292]
19,20,Wolves,110.863386,8,[82.3859068156],[146.3680851064],[85.0382352941],[81.8065464632],[143.6797008332],[135.7949119374],[122.6935424354],[89.1401629479]

In [19]:
year = '2019-2020'
if year=='': folder = ''
else: folder = f'history/{year}/'
with open(Path(f'{folder}mid/FPL/Team_xG.txt'), 'r') as file:
    Team_xG = pd.DataFrame(json.loads(file.read()))
    Team_xG.index = pd.to_numeric(Team_xG.index)
    #Team_xG = Team_xG.sort_index()
    TxG1920 = no_lists(Team_xG.sort_index()[Team_xG.columns[:3:-1]])
    
with open(Path(f'{folder}mid/FPL/Team_xG_Ad.txt'), 'r') as file:
    Team_xG_Ad = pd.DataFrame(json.loads(file.read()))
    Team_xG_Ad.index = pd.to_numeric(Team_xG_Ad.index)
    #Team_xG_Ad = Team_xG_Ad.sort_index()
    TxGA1920 = no_lists(Team_xG_Ad.sort_index()[Team_xG_Ad.columns[:3:-1]])
    
with open(Path(f'{folder}mid/FPL/Team_Opponent_xG.txt'), 'r') as file:
    Team_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    Team_Opponent_xG.index = pd.to_numeric(Team_Opponent_xG.index)
    #Team_Opponent_xG = Team_Opponent_xG.sort_index()
    TOxG1920 = no_lists(Team_Opponent_xG.sort_index()[Team_Opponent_xG.columns[:3:-1]])
    
with open(Path(f'{folder}mid/FPL/Team_oppdefence_coeff.txt'), 'r') as file:
    Team_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    Team_oppdefence_coeff.index = pd.to_numeric(Team_oppdefence_coeff.index)
    #Team_oppdefence_coeff = Team_oppdefence_coeff.sort_index()
    Todc = no_lists(Team_oppdefence_coeff.sort_index()[Team_oppdefence_coeff.columns[::-1]])
    
threatAllowedAv = no_lists(Team_Opponent_xG[Team_Opponent_xG.columns[4:]]).mean(axis=1).mean()
#lastGW = len(Team_xG.columns[4:])
TOxG1920

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW39*,GW39,GW40,GW41,GW42,GW43,GW44,GW45,GW46,GW47
0,93,227,362,161,287,182,162,86,104,190,...,152.0,288,123,49,98,117,206,334,94,305
1,313,154,131,251,152,262,173,349,238,435,...,215.0,71,126,86,119,176,150,112,92,69
2,88,248,317,181,209,264,309,187,91,81,...,NaN,75,105,145,257,118,206,111,236,196
3,112,113,174,185,36,126,339,88,318,143,...,NaN,179,120,161,131,311,379,280,165,147
4,146,226,180,202,181,120,138,145,173,245,...,NaN,230,97,213,152,308,338,175,72,155
5,190,113,115,64,170,122,92,107,27,158,...,NaN,115,112,199,61,219,170,32,154,66
6,126,213,231,107,141,214,181,133,309,189,...,NaN,123,252,92,191,176,189,199,171,80
7,179,114,143,184,169,29,257,126,114,94,...,NaN,127,108,200,101,265,175,131,125,201
8,90,163,113,98,91,131,13,258,164,68,...,NaN,155,128,87,68,156,148,92,101,109
9,125,178,88,60,70,103,149,46,60,131,...,NaN,114,3,154,102,148,94,50,144,27
10,67,81,173,111,112,106,235,73,84,160,...,7.0,23,309,181,75,89,28,205,14,65
11,160,84,111,126,112,101,145,109,117,109,...,NaN,103,52,70,103,75,188,164,132,125
12,149,238,165,156,318,207,187,121,259,165,...,NaN,103,138,150,223,336,279,172,122,163
13,222,135,287,280,382,225,228,268,146,284,...,NaN,290,180,170,101,144,253,283,311,476
14,182,88,130,162,152,236,151,90,127,148,...,179.0,219,223,139,94,49,152,230,60,203
15,160,163,180,276,214,90,135,157,45,392,...,NaN,104,155,95,409,104,129,144,148,117
16,86,469,113,304,174,196,175,242,87,343,...,NaN,152,89,139,95,149,131,191,320,124
17,71,119,310,176,102,401,88,104,183,165,...,NaN,139,112,123,301,121,110,106,374,202
18,237,167,287,108,107,126,210,182,300,161,...,NaN,181,120,197,127,134,89,186,141,128
19,130,110,157,230,229,170,203,240,174,151,...,NaN,95,33,85,150,122,98,110,99,128

In [14]:
hist_num = 6

'''
    Making all input tables standart format. Only numer columns. From left to right. No lists, columns for DGW added
'''
df = no_lists(Team_xG_Ad.sort_index()[Team_xG_Ad.columns[:3:-1]])
df_answers = no_lists(Team_xG.sort_index()[Team_xG.columns[:3:-1]])

X3 = pd.DataFrame()
X3_opponents = []
X3_answers = []
col = []

for i in range(hist_num, 0, -1):
    col.append(f'GW-{i}')

for i in range(0,len(df.columns)-hist_num):
    print(i+1)
    next_tour2add = no_lists(df.sort_index())[df.columns[i:i+6]]
    next_tour2add.columns=col#['GW-6','GW-5','GW-4','GW-3','GW-2','GW-1']
    X3 = X3.append(next_tour2add, ignore_index=True, sort=False)
    
    X3_opponents.extend(Team_oppdefence_coeff[Team_oppdefence_coeff.columns[::-1]]\
    [df_answers.columns[hist_num+i]]*threatAllowedAv)
    #[f'GW{hist_num+1+i}']*threatAllowedAv)
    
    X3_answers.extend(df_answers[df_answers.columns[hist_num+i]].tolist())
X3['Opponent'] = X3_opponents
X3['GW'] = X3_answers

X3 = X3.dropna()
X = X3[X3.columns[:-1]]
Y = X3['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43

0.34574400066927247

array([0.13225432, 0.16084764, 0.07686628, 0.05959735, 0.19174913,
       0.05019388, 1.1111016 ])

In [24]:
X3 = X3.dropna()
X = X3[X3.columns[:-1]]
Y = X3['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

0.6117905519215519

array([-0.09775415,  0.20358946,  0.17616046,  0.14356745, -0.2375316 ,
        0.21926084,  1.23342266])