In [2]:
''' Fantasy Tables from Different Sources

    Creates class Source which makes tables and htmls from 2 sources: FPL and Understat. Depending on source
    getting data from inputFPL.py or inputUnderstat.py
    
    Sources:    f'{folder}in/Table_'+source+'.csv'
                f'{folder}in/Fixtures.csv'
                f'{folder}in/Teams.csv'
                f'{folder}in/Players.csv'
                f'{folder}in/Team_played_fixtures.csv'
                f'{folder}in/Team_upcoming_fixtures.csv'
                f'{folder}in/Team_opponent_team.csv'
                'in/Player_opponent_team.csv'
                'in/Player_played_fixtures.csv'
                'in/Player_upcoming_fixtures.csv'
                f'{folder}Team_fixtures.txt'
                f'{folder}Player_fixtures.txt'
                
                'index.html'
                f'html/{source}/{name}.html'
                f'html/{source}/css/{name}.css'
                name in {Team_xG, Team_xA, Team_Opponent_xG, Team_xG_Ad, Team_xA_Ad, Team_Opponent_xG_Ad,
                Player_xG, PLayer_xA, Player_xG_Ad, Player_xA_Ad}
    
    Write:      f'{folder}out/{source}/{name}.csv'

                f'{folder}mid/{self.source}/Team_xxG.csv'
                f'{folder}mid/{self.source}/Team_xOxG.csv'
                f'{folder}mid/{self.source}/Player_xxG.csv'
                
                'mid/{source}/TxG.csv'
                'mid/{source}/TxA.csv'
                'mid/{source}/TOxG.csv'
                'mid/{source}/TxGA.csv'
                'mid/{source}/TxAA.csv'
                'mid/{source}/TOxGA.csv'
                'mid/{source}/PxG.csv'
                'mid/{source}/PxA.csv'
                'mid/{source}/PxGA.csv'
                'mid/{source}/PxAA.csv'
                f'mid/{source}/Team_Attack_weight.csv'
                f'mid/{source}/Team_Defence_weight.csv'
                f'mid/{source}/Player_Attack_weight.csv'
                f'mid/{source}/Player_Defence_weight.csv'
                
                'index.html'
                f'html/{source}/{name}.html'
                f'html/{source}/css/{name}.css'

'''




from time import time
import constti
from Brr_functions import toint, noZ, no_lists, to_lists, del_empty_col, is_finished, get_gw_num
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
import os

class Source:
    def __init__(self, source, ma_num=0, year=''):
        '''
            Initialization function
            source = FPL or Understat
            ma_num = numbers in Moving Average. If 0 then no MA and calculations are faster
            year = '' then current, otherwize year of history "2019-2020" for example
        '''
        self.source = source
        print(f'Start Creating {self.source} Tables:')
        start_module = time()
        start = time()
        self.ma_num = ma_num # Number of matches for the moving average
        
#1. Reading nessesry data from files.
        
        #finding folder with data for year entered
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        
        #Catching empty data at the start of the season. Avoiding mistake with reading empty file
        try:
            Table = pd.read_csv(Path(f'{folder}in/Table_'+source+'.csv')) # Main data. Row for player's played fixture
        except:
            print('!!!!!!!!')
            Table = pd.DataFrame()
            self.Table = Table
            return
        if len(Table)<1:
            Table = pd.DataFrame()
            self.Table = Table
            return
    
        #in a game with columns 'element', 'round', 'fixture', 'threat', 'creativity', 'team', opponent_team'
        Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv')) # Table of rows for each fixture
        Teams = pd.read_csv(Path(f'{folder}in/Teams.csv')) # Table of rows as teams with columns 'id', 'Teams',
        #'TARGET COL', 'Matches'
        Players = pd.read_csv(Path(f'{folder}in/Players.csv')) # Table of rows as players with columns 'id', 'Name',
        #'Team', Team games', 'Played'
        del Players['web_name'] #This column is needed only for inputUnderstat.py

        #Reading Fxtures and Opponents for Teams and Players
        
        Team_played_fixtures = pd.read_csv(Path(f'{folder}in/Team_played_fixtures.csv'))       
        Team_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Team_upcoming_fixtures.csv'))
        Team_opponent_team = pd.read_csv(Path(f'{folder}in/Team_opponent_team.csv'))
        Player_opponent_team = pd.read_csv(Path(f'{folder}in/Player_opponent_team.csv'))
        #To make code shorter
        Tot = Team_opponent_team
        Pot = Player_opponent_team
        
        #file names differ for the present and history
        if year=='':

            Player_played_fixtures = pd.read_csv(Path(f'{folder}in/Player_played_fixtures.csv'))
            Player_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Player_upcoming_fixtures.csv'))
        else:
            with open(Path(f'{folder}in/Team_fixtures.txt'), 'r') as file:
                Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
                Team_played_fixtures = Team_played_fixtures.sort_index()
            with open(Path(f'{folder}in/Player_fixtures.txt'), 'r') as file:
                Player_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Player_played_fixtures.index = pd.to_numeric(Player_played_fixtures.index)
                Player_played_fixtures = Player_played_fixtures.sort_index()
            Team_upcoming_fixtures = pd.DataFrame()
            Player_upcoming_fixtures = pd.DataFrame()
        
        print('\t 1. Reading files from ' + source +' is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

#2. Defenition of useful constants and funtions
        
        #Teams in Premier League
        team_number = len(Teams)

        #Calculating lastGW - last gameweek with at least one game played
        lastGW  = Table['round'].max()

        print('\t 2. Constants and Functions are over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 3. Calculating team tables

        print('\t 3. Calculating team tables')
    
        def xAxG(col, id, entity, field):
            '''
                Function for apply to *_played_fixtures to make tables
                entity: team, opponent or player
                field: name of the field in Table
            '''
            new_col = []
            if entity == 'player':
                entity = 'element'
            elif entity == 'opponent':
                entity = 'opponent_team'
                
            for i in range(len(col)):
                if np.isnan(col[i]):
                    new_col.append(np.nan)
                else:
                    x = Table[(Table['fixture']==col[i])&(Table[entity]==id[i])][field]
                    
                    if len(x) == 0:
                        new_col.append(0)
                    else:
                        new_col.append(x.sum())
            return new_col

        #(1). Creating  a table with average threat and GW threats for teams
        
        TxG = Team_played_fixtures.apply(xAxG, args=(Teams['id'],'team','threat'))
        
        print('\t\t 3.1. Team_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
        #(2). Creating  a table with average creativity and GW creativities for teams
        
        TxA = Team_played_fixtures.apply(xAxG, args=(Teams['id'],'team','creativity'))
        
        print('\t\t 3.2. Team_xA is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()
        
        
        #(3). Creating  a table with average threat allowed by teams and GW threat allowed
        
        TOxG = Team_played_fixtures.apply(xAxG, args=(Teams['id'],'opponent','threat'))
        
        print('\t\t 3.3. Team_Opponent_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
        #(3.99). Creating coeffitients for team tables adjustment
        
        threatAllowedAv = TOxG.mean(axis=1).mean() #Team_Opponent_xG['Opponent xG av'].mean()
        TOxG_av = TOxG.mean(axis=1)
        TxG_av = TxG.mean(axis=1)
        #Team Attack weight unadjusted
        TAwu = Tot.applymap(lambda x: np.nan if np.isnan(x) else TOxG_av[int(x)-1])/threatAllowedAv
        #Team Defence weight unadjusted
        TDwu = Tot.applymap(lambda x: np.nan if np.isnan(x) else TxG_av[int(x)-1])/threatAllowedAv
        #Player Attack weight unadjusted
        PAwu = 'Define to be defined for "class_args"'
        #Player Defence weight unadjusted
        PDwu = 'Define to be defined for "class_args"'
        
        class_args = [Teams, Players, TAwu, TDwu, PAwu, 'TxxG', 'TxxA', 'TxOxG', 'PxxG', 'PxxA']
        class_args += [self.source, self.ma_num, folder]
        
        print('\t\t 3.3.99 Creating coeffitients is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()

        
        #(4). Creating  a table with average adjusted threat and GW threats adj for teams

        TxGA, Team_xG_Ad = adjustment('Team_xG', TxG, class_args)

        print('\t\t 3.4. Team_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(5). Creating  a table with average adjusted creativity and GW creativities adj for teams
        
        TxAA, Team_xA_Ad = adjustment('Team_xA', TxA, class_args)

        print('\t\t 3.5. Team_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(6). Creating  a table with average threat allowed adjusted by teams and GW threat allowed adjusted

        TOxGA, Team_Opponent_xG_Ad = adjustment('Team_Opponent_xG', TOxG, class_args)

        print('\t\t 3.6. Team_Opponent_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()


        #(7) Total Team Table

        TableTeams = pd.DataFrame()
        TableTeams['id'] = Teams['id']
        TableTeams['Team'] = Teams['Teams']
        
        TOxGA_av = TOxGA.mean(axis=1)
        TxGA_av = TxGA.mean(axis=1)
        
        TableTeams['xG adjusted'] = TxGA_av#Team_xG_Ad['xG av adj']
        TableTeams['xG'] = TxG_av#TxG.mean(axis=1)#Team_xG['xG av']
        TableTeams['xA adjusted'] = TxAA.mean(axis=1)#Team_xA_Ad['xA av adj']
        TableTeams['xA'] = TxA.mean(axis=1)#Team_xA['xA av']
        TableTeams['Opponent xG adjusted'] = TOxGA_av#Team_Opponent_xG_Ad['Opponent xG av adj']
        TableTeams['Opponent xG'] = TOxG_av#Team_Opponent_xG['Opponent xG av']
        
        print('\t\t 3.7. TableTeams is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        
# 4. Calculating pLayer tables
        
        print('\t 4. Calculating player tables')

        #(1) Players Threat
        
        PxG = Player_played_fixtures.apply(xAxG, args=(Players['id'],'player','threat'))
        
        print('\t\t 4.1. Player_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
        #(2) Players Creativity
        
        PxA = Player_played_fixtures.apply(xAxG, args=(Players['id'],'player','creativity'))
        
        print('\t\t 4.2. Player_xA is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
        #(2.99) Creating coeffitients for player tables adjustment

        PAwu=Player_opponent_team.applymap(lambda x: np.nan if np.isnan(x) else TOxG_av[int(x)-1])/threatAllowedAv
        PDwu = Player_opponent_team.applymap(lambda x:np.nan if np.isnan(x) else TxG_av[int(x)-1])/threatAllowedAv

        class_args = [Teams, Players, TAwu, TDwu, PAwu, 'TxxG', 'TxxA', 'TxOxG', 'PxxG', 'PxxA']
        class_args += [self.source, self.ma_num, folder]
        
        print('\t\t 4.2.99 Creating coeffitients is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
        #(3) Players Threat Adjusted
        
        PxGA, Player_xG_Ad = adjustment('Player_xG', PxG, class_args)

        print('\t\t 4.3. Player_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        
        #(4) PLayers Creativity Adjusted
        
        PxAA, Player_xA_Ad = adjustment('Player_xA', PxA, class_args)

        print('\t\t 4.4. Player_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        
# 5. Creating future tables and opponent tables

        #(1) Calculating futures
        print('\t 5. Creating future tables and opponent tables.')
        
        #Columns with np.nan automatically become float that's why int() is needed
        Team_Defence_weight = Tot.applymap(lambda x: TxGA_av[int(x)-1] if not np.isnan(x) else np.nan)/threatAllowedAv
        Team_Attack_weight = Tot.applymap(lambda x: TOxGA_av[int(x) - 1] if not np.isnan(x) else np.nan)/threatAllowedAv
        Player_Defence_weight = Pot.applymap(lambda x: TxGA_av[int(x)-1] if not np.isnan(x) else np.nan)/threatAllowedAv
        Player_Attack_weight = Pot.applymap(lambda x: TOxGA_av[int(x) - 1] if not np.isnan(x) else np.nan)/threatAllowedAv

        TxxG = Team_Attack_weight.mul(Team_xG_Ad['xG av adj'], axis=0)
        TxxG = Team_upcoming_fixtures.applymap(lambda x: np.nan if np.isnan(x) else 1)*TxxG
        TxxA = Team_Attack_weight.mul(Team_xA_Ad['xA av adj'], axis=0)
        TxxA = Team_upcoming_fixtures.applymap(lambda x: np.nan if np.isnan(x) else 1)*TxxA
        TxOxG = Team_Defence_weight.mul(Team_Opponent_xG_Ad['Opponent xG av adj'], axis=0)
        TxOxG =  Team_upcoming_fixtures.applymap(lambda x: np.nan if np.isnan(x) else 1)*TxOxG
        PxxG = Player_Attack_weight.mul(Player_xG_Ad['xG per game adj'], axis=0)
        PxxG =  Player_upcoming_fixtures.applymap(lambda x: np.nan if np.isnan(x) else 1)*PxxG
        PxxA = Player_Attack_weight.mul(Player_xA_Ad['xA per game adj'], axis=0)
        PxxA =  Player_upcoming_fixtures.applymap(lambda x: np.nan if np.isnan(x) else 1)*PxxA
        
        class_args = [Teams, Players, TAwu, TDwu, PAwu, TxxG, TxxA, TxOxG, PxxG, PxxA]
        class_args += [self.source, self.ma_num, folder]
        
        #Writing pure numbers(lists of numbers) tables to mid folder for stats calculations
#         Team_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppxG_coeff.txt'))
#         Team_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppdefence_coeff.txt'))
#         Player_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppxG_coeff.txt'))
#         Player_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppdefence_coeff.txt'))
#         Team_xxG.to_json(Path(f'{folder}mid/{self.source}/Team_xxG.txt'))
#         Team_xOxG.to_json(Path(f'{folder}mid/{self.source}/Team_xOxG.txt'))
#         Player_xxG.to_json(Path(f'{folder}mid/{self.source}/Player_xxG.txt'))

        
        print('\t\t 5.1. Calculating futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Visualizing futures
        
        #Adding some words for tables to be readable (lists still)
        Team_xxG = del_empty_col(TxxG.copy())
        Team_xxG['sum'] = Team_xxG.sum(axis=1)
        Team_xxG.insert(0, 'Teams', Teams['Teams'])
        Team_xxG = Team_xxG.sort_values('sum', ascending=False)
        del Team_xxG['sum']
#         for i in range(1,lastGW+1):
#             del Team_xxG[f'GW{i}']
        #Team_xxG

        Player_xxG = del_empty_col(PxxG.copy())
        Player_xxG['sum'] = Player_xxG.sum(axis=1)
        Player_xxG.insert(0, 'Name', Players['Name'])
#         Player_xxG['name'] =  Players['Name']
        Player_xxG = Player_xxG.sort_values('sum', ascending=False)
        del Player_xxG['sum']
#         for i in range(1,lastGW+1):
#             del Player_xxG[f'GW{i}']
#         Player_xxG

        Team_xOxG = del_empty_col(TxOxG.copy())
        Team_xOxG['sum'] = Team_xOxG.sum(axis=1)
        Team_xOxG.insert(0, 'Teams', Teams['Teams'])
#         Team_xOxG['Teams'] = Teams['Teams']
        Team_xOxG = Team_xOxG.sort_values('sum', ascending=True)
        del Team_xOxG['sum']
#         for i in range(1,lastGW+1):
#             del Team_xOxG[f'GW{i}']
#         Team_xOxG
        
        print('\t\t 5.2. Visualizing futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
# 6. Writing tables to files (and variables to class.variables)
        
        # Useful variables for debugging
        self.Table = Table
        self.Fixtures = Fixtures
        self.Teams = Teams
        self.Players = Players
        self.lastGW = lastGW
        
        self.class_args = class_args
        self.threatAllowedAv = threatAllowedAv
        self.Team_played_fixtures = Team_played_fixtures
        self.Team_upcoming_fixtures = Team_upcoming_fixtures
        self.Team_opponent_team = Team_opponent_team
        self.Player_played_fixtures = Player_played_fixtures
        self.Player_upcoming_fixtures = Player_upcoming_fixtures
        self.Player_opponent_team = Player_opponent_team
        
        #Save before modifying while writing into files
#         self.Team_xG = Team_xG.copy()
#         self.Team_xA = Team_xA.copy()
#         self.Team_Opponent_xG = Team_Opponent_xG.copy()
#         self.Team_xG_Ad = Team_xG_Ad.copy()
#         self.Team_xA_Ad = Team_xA_Ad.copy()
#         self.Team_Opponent_xG_Ad = Team_Opponent_xG_Ad.copy()
#         self.TableTeams = TableTeams.copy() 
#         self.Player_xG = Player_xG.copy()
#         self.Player_xA = Player_xA.copy()
#         self.Player_xG_Ad = Player_xG_Ad.copy()
#         self.Player_xA_Ad = Player_xA_Ad.copy()
        
        self.TxG = TxG.copy()
        self.TxA = TxA.copy()
        self.TOxG = TOxG.copy()
        self.TxGA = TxGA.copy()
        self.TxAA = TxAA.copy()
        self.TOxGA = TOxGA.copy()
        self.PxG = PxG.copy()
        self.PxA = PxA.copy()
        self.PxGA = PxGA.copy()
        self.PxAA = PxAA.copy()
        
        self.TxxG = TxxG
        self.TxxA = TxxA
        self.TxOxG = TxOxG
        self.PxxG = PxxG
        self.PxxA = PxxA
        self.Team_xxG = Team_xxG
        self.Team_xOxG = Team_xOxG
        self.Player_xxG = Player_xxG
        
        TxG.to_csv(Path(f'{folder}mid/{source}/TxG.csv'), index=False)
        TxA.to_csv(Path(f'{folder}mid/{source}/TxA.csv'), index=False)
        TOxG.to_csv(Path(f'{folder}mid/{source}/TOxG.csv'), index=False)
        TxGA.to_csv(Path(f'{folder}mid/{source}/TxGA.csv'), index=False)
        TxAA.to_csv(Path(f'{folder}mid/{source}/TxAA.csv'), index=False)
        TOxGA.to_csv(Path(f'{folder}mid/{source}/TOxGA.csv'), index=False)
        PxG.to_csv(Path(f'{folder}mid/{source}/PxG.csv'), index=False)
        PxA.to_csv(Path(f'{folder}mid/{source}/PxA.csv'), index=False)
        PxGA.to_csv(Path(f'{folder}mid/{source}/PxGA.csv'), index=False)
        PxAA.to_csv(Path(f'{folder}mid/{source}/PxAA.csv'), index=False)
        
        Team_Attack_weight.to_csv(Path(f'{folder}mid/{source}/Team_Attack_weight.csv'), index=False)
        Team_Defence_weight.to_csv(Path(f'{folder}mid/{source}/Team_Defence_weight.csv'), index=False)
        Player_Attack_weight.to_csv(Path(f'{folder}mid/{source}/Player_Attack_weight.csv'), index=False)
        Player_Defence_weight.to_csv(Path(f'{folder}mid/{source}/Player_Defence_weight.csv'), index=False)
        
        Team_xxG.to_csv(Path(f'{folder}mid/{self.source}/Team_xxG.csv'), index=False)
        Team_xOxG.to_csv(Path(f'{folder}mid/{self.source}/Team_xOxG.csv'), index=False)
        Player_xxG.to_csv(Path(f'{folder}mid/{self.source}/Player_xxG.csv'), index=False)
        

        self.Team_xG = write_table(TxG, 'Team_xG', 'xG av', TxxG, class_args)
        self.Team_xA = write_table(TxA, 'Team_xA', 'xA av', TxxA, class_args)
        self.Team_Opponent_xG = write_table(TOxG, 'Team_Opponent_xG', 'Opponent xG av', TxOxG, class_args)
        self.Team_xG_Ad = write_table(TxGA, 'Team_xG_Ad', 'xG av adj', TxxG, class_args)
        self.Team_xA_Ad = write_table(TxAA, 'Team_xA_Ad', 'xA av adj', TxxA, class_args)
        self.Team_Opponent_xG_Ad = write_table(TOxGA, 'Team_Opponent_xG_Ad', 'Opponent xG av adj', TxOxG, class_args)
        self.TableTeams = write_table(TableTeams, 'TableTeams', 'xG adjusted', 'NOTHING', class_args)
        
        self.Player_xG = write_table(PxG, 'Player_xG', 'xG per fixture', PxxG, class_args)
        self.Player_xA = write_table(PxA, 'Player_xA', 'xA per fixture', PxxA, class_args)
        self.Player_xG_Ad = write_table(PxGA, 'Player_xG_Ad', 'xG per fixture adj', PxxG, class_args)
        self.Player_xA_Ad = write_table(PxAA, 'Player_xA_Ad', 'xA per fixture adj', PxxA, class_args)
        
        print('\t 6. Writing to files is over.\t It takes ' + str(time() - start) + ' sec')
        print(f'{self.source} is created./t It takes {time() - start_module} sec')
        start = time()

# 7. Tests for each element of the class
    
    def test2FPL(self, folder=''):
        '''
            Checks if all names in the source can be found in fantasy.premierleague.com (FPL)
            Subfunction of test()
        '''
        FPL = pd.read_csv(f'{folder}in/Table_FPL.csv')
        Table_Source = pd.read_csv(f'{folder}in/Table_'+self.source+'.csv')
        Mistakes = pd.DataFrame()
        No_Names = pd.DataFrame()
        if self.source == 'FPL':
            return Mistakes, No_Names
        
        col_m = ['player', 'element', 'fixture', 'minutes', 'FPL_minutes']
        col_n = ['player', 'team_name', 'fixture']
        for i in Table_Source.index:
            if Table_Source.at[i,'element'] < 1000000:
                
                C = (FPL['element'] == Table_Source.at[i,'element'])&(FPL['fixture'] == Table_Source.at[i,'fixture'])
                FPLmin = FPL[C]['minutes'].sum()
                
                if abs(Table_Source.at[i,'minutes'] - FPLmin) > 10:
                    a = [Table_Source.at[i,'player'], Table_Source.at[i,'element']]
                    a += [Table_Source.at[i,'fixture'], Table_Source.at[i,'minutes'], FPLmin]
                    Mistakes = Mistakes.append(pd.DataFrame( [a], columns = col_m), ignore_index=True)
            else:
                T = [[Table_Source.at[i,'player'], Table_Source.at[i,'team_name'], Table_Source.at[i,'fixture']]]
                No_Names = No_Names.append(pd.DataFrame( T, columns = col_n), ignore_index=True)
                
        display(Mistakes)
        display(No_Names)
        return Mistakes, No_Names
        
    def test(self, year=''):
        '''
            Tests that all tables are correct (no duplicated columns or rows)
            Uses test2FPL() to compare names
        '''
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        if self.Table.empty:
            print(f'Nothing to test. {self.source} table is empty.')
            return
        start = time()
        
        constti.DRDC(self.Team_xG)
        constti.DRDC(self.Team_xA)
        constti.DRDC(self.Team_Opponent_xG)
        constti.DRDC(self.Team_xG_Ad)
        constti.DRDC(self.Team_xA_Ad)
        constti.DRDC(self.Team_Opponent_xG_Ad)
        constti.DRDC(self.TableTeams)
        constti.DRDC(self.Player_xG)
        constti.DRDC(self.Player_xA)
        constti.DRDC(self.Player_xG_Ad)
        constti.DRDC(self.Player_xA_Ad)
        
        self.test2FPL(folder='')
        
        print(f'\t {self.source} Testing is over.\t It takes {time() - start} sec\n\n')

# 7. Useful not class functions

def html_table_name(table_name):
    '''
    Converts the name of the table into the name of the Tale in html file
    '''
    x = table_name.replace('Team_', 'Teams Ranking Based on Team ')
    x = x.replace('Player_', 'Players Ranking Based on Player ')
    x = x.replace('Ad', 'Adjusted').replace('_', ' ').replace('TableTeams', 'Teams Ranking')
    return x


def write_table(df, name, key_col, xdf, class_args):
    '''
        Writing final tables to files and returning table itself and MA variant also
        df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
        source - Understat or FPL, ma_num - number for MA(currently unused just calculated)
    '''
    def GW_forecast (df, xdf):
    #     a = df.copy()
        lastGW = get_gw_num(del_empty_col(df.copy()).columns[-1])
        Table = pd.DataFrame()
        for i in df.columns:
            Table[i] = [df.at[j,i] if np.isnan(xdf.at[j,i]) else xdf.at[j,i] for j in df.index]

        column_numbers = np.asarray(list(map(get_gw_num, Table.columns)))
        if max(column_numbers)>lastGW:
            n = lastGW + 1
        else:
            n = lastGW
        for i in Table.columns:
            if get_gw_num(i) > n:
                del Table[i]
        return Table 
    def table2string(table):
        '''
        Converts table to view suitable for html. All number columns are actually strings with 1 digit after .
        '''
        df = table.copy()
        for j in df.columns:
            if ('GW' in j)|(' av' in j)|('xG' in j)|('xA' in j):
                df[j] = [str(int(df.at[i,j]*10)/10) if not np.isnan(df.at[i,j]) else '' for i in df.index]

        return df
    
    df = df.copy() # not to change initial df
    Teams, Players = class_args[:2]
    source, ma_num, folder = class_args[10:]
    
    if name != 'TableTeams':
        if 'Team' in name:
            X = Teams.copy()
            X.columns = ['id', 'Teams', key_col, 'Matches']
            X[key_col] = df.mean(axis=1)
        else:
            X = Players.copy()
            n = Players.columns.get_loc('Team games')
            X.insert( n, key_col, df.mean(axis=1))
            X.insert(n + 1, key_col.replace('fixture','game'),X[key_col]*Players['Team games']/noZ(Players['Played']))
            
        df = GW_forecast(df, xdf)
        
        Y = df[df.columns[::-1]]
        X[Y.columns] = Y.copy()
        df = X.copy()
        del_empty_col(df)
    
    #Removes redundant columns
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    
    # Sort decreasing for attack an increasing for defence
    if 'Opponent' in name:
        df.sort_values(key_col, ascending = True, inplace = True)
    else:
        df.sort_values(key_col, ascending = False, inplace = True)
    
    df.index = np.arange(1, len(df) + 1)
    
    # If moving average number is 0 no calculation needed. Use it to fasten the debug!
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    
    #Writes result to file
    df.to_csv(Path(f'{folder}out/{source}/{name}.csv'))
    
    
    # Add table created as table of stringe to existing html file replacing table tag with a new one
    #Also adding a new css
    if folder == '':
        dfString = table2string(df)
        
        
        
        
        
        
#         for i in dfString.columns:
#             dfString[i]=[[dfString.at[j,i],1] if np.isnan(xdf.at[j,i]) else [dfString.at[j,i],0] for j in dfString.index]
        
        
        dfStringStyler = dfString.style.apply(color_table, axis=None)
        dfStringStyler.set_table_attributes('class="DataTable"')
        html_table = dfStringStyler.render().replace('\n', '')
        BS_table = BeautifulSoup(html_table, 'html.parser')
        css = str(BS_table('style')[0])
        html_ = str(BS_table('table')[0])

        #Getting right paths for different tables
        if source=='FPL' and name=='TableTeams':
            html_path = Path(f'{folder}index.html')
            css_path = Path(f'{folder}html/FPL/css/TableTeams.css')
        else:
            html_path = Path(f'{folder}html/{source}/{name}.html')
            css_path = Path(f'{folder}html/{source}/css/{name}.css')

        #Making css for coloring butons

        css = ('#' + source + '-button {\n background-color: #82f5cf;\n}\n' +
               '#' + name + ' {\n background-color: lightgrey;\n}\n' + 
               css)

        #Rewriting html and css
        with open(f'{folder}index.html', 'r', encoding="utf-8") as file:
            old_file = file.read()
        tag_to_replace1 = str(BeautifulSoup(old_file, 'html.parser')('table', attrs={"class":"DataTable"})[0])
        tag_to_replace2 = str(BeautifulSoup(old_file, 'html.parser')('h2', attrs={"id":"DataTitle"})[0])
        new_file = old_file.replace(tag_to_replace1, html_)
        new_file = new_file.replace(tag_to_replace2, f'<h2 id="DataTitle"> {html_table_name(name)} </h2>')

        #Making links right

        if not(source=='FPL' and name=='TableTeams'):
            new_file = new_file.replace('html/FPL/', '')
            new_file = new_file.replace('"out/FPL/TableTeams.csv"', f'"../../out/{source}/{name}.csv"')#Download button
            new_file = new_file.replace(f'TableTeams', name)
            if name != 'TableTeams': #changes links for buttons FPL and Understat
                str1 = 'class="header-form" action="index.html"'
                str2 = f'class="header-form" action="../FPL/{name}.html"'
                new_file = new_file.replace(str1, str2)
            else:
                new_file = new_file.replace('form action="index.html"', f'form action="../../index.html"')
            new_file = new_file.replace('html/', '../')
            new_file = new_file.replace('"index.html"', '"../../index.html"')

        #Creating .html and special files for the Table
        with open(html_path, 'w', encoding="utf-8") as file:
            file.write(new_file)
        with open(css_path, 'w', encoding="utf-8") as file:
            file.write(css)
    
    return df

def color_table(df):
    '''
        Makes colored tables
    '''
    def table_type(df):
        if df.columns[2]=='xG': return 'TableTeams'
        elif 'Opponent' in df.columns[1]: return 'Defence'
        elif df.columns[0]=='Teams': return 'Team'
        else: return 'Player'
    def color_Team_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Player_xG(val):
        if val=='': color = 'white'
        elif float(val)>50: color = '#09bb9f'
        elif float(val)>25: color = '#82f5cf'
        elif float(val)>10: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Defence(val):
        if val=='': color = 'white'
        elif float(val)<120: color = '#09bb9f'
        elif float(val)<150: color = '#82f5cf'
        elif float(val)<180: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    
    def color_table_row(row, x):
        '''
            function for style.apply by rows where x is a table type
            Subfunction of color_table_row
        '''
        str1 = 'Background-color: white'
        tw = (row.name in ['Matches', 'Teams'])
        pw = (row.name  in ['Team games', 'Played', 'Name', 'Team'])
        ttw = (row.name in ['xG adjusted', 'xG', 'xA', 'xA adjusted'])
        
        if x=='Team':
            return [color_Team_xG(i) if not tw else str1 for i in row]
        elif x=='Player':
            return [color_Player_xG(i) if not pw else str1 for i in row]
        elif x=='Defence':
            return [color_Defence(i) if not tw else str1 for i in row]
        elif x=='TableTeams':
            return [color_Team_xG(i) if ttw else str1 if row.name in ['Team'] else color_Defence(i) for i in row]
        
    return df.apply(color_table_row, x=table_type(df), axis=0)


# Returns the table with d mean average for table Out_T
# If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
def MA(Out_T, d):
    '''
        Returns the table with d mean average for table Out_T.
        If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
        Filling the column with averages. Subfunction for MA.
        Adds d - averages for j-th GW_column (not GWj but j-th in order) of table T.
    '''
    def d_av(T, j, GW_columns, d):
        T.insert(T.columns.get_loc(GW_columns[-1]), f'{GW_columns[j]} {str(d)} - average', [0.0 for i in T.itertuples()])
        for i in T.index:
            u = 0
            k = 0
            while (u < d)&(j-k>=0):
                if not np.isnan(T.at[i, GW_columns[j-k]]):#!!!'':
                    T.at[i, f'{GW_columns[j]} {str(d)} - average'] += T.at[i, GW_columns[j-k]]
                    u+=1
                    k+=1
                else: k+=1
            if u==d:
                T.at[i, f'{GW_columns[j]} {str(d)} - average'] = T.at[i, f'{GW_columns[j]} {str(d)} - average']/d
            else:
                T.loc[i, f'{GW_columns[j]} {str(d)} - average'] = ''
        return None
    
    T = Out_T.copy()
    
    #Creating the list of GW_columns for the table T
    GW_columns = []
    gw_col=0
        
    for col in T.columns:
        if 'GW' in col:
            GW_columns.append(col)
            gw_col+=1
    GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)] #makes the opposite order of the list
    
    #returning colored MA table if it is TableTeams
    if GW_columns == []: return T
    
    #Add averages for GW_columns using d_av function defined above returning colored MA table if it is not TableTeams
    # Add MA columns only id d not larger than GW played
    if d<=gw_col:
        for j in range(gw_col-1, d-2, -1):
            d_av(T, j, GW_columns, d)

    return T
    
    
#     return dfAd
def adjustment(name, df, class_args):
    '''
        Creating adjusted tables from unadjusted
        name - table name before transformation
        df - table to transform
        class_args - list of needed data from source class
    '''
    [Teams, Players, Team_Attack_weight_unadj, Team_Defence_weight_unadj, Player_Attack_weight_unadj] = class_args[:5]
    
    Name = name.split('_')
    
    key_par = ' '.join(Name[1:])
    if Name[0] == 'Team':
        dfAdjusted = Teams.copy()
        dfAdjusted.columns = ['id', 'Teams', f'{key_par} av adj', 'Matches']
        if key_par in {'xG', 'xA'}:
            weight = Team_Attack_weight_unadj
        else:
            weight = Team_Defence_weight_unadj
    else:
        dfAdjusted = Players.copy()
        weight = Player_Attack_weight_unadj
        
    dfAd = df/weight #Main formula
    
    X = dfAd[dfAd.columns[::-1]]
    dfAdjusted[X.columns] = X
    del_empty_col(dfAdjusted)
    
    if Name[0] == 'Team':
        dfAdjusted[f'{key_par} av adj'] = dfAd.mean(axis=1)
    else:
        n = Players.columns.get_loc('Team games')
        dfAdjusted.insert(n, f'{key_par} per fixture adj', dfAd.sum(axis=1)/noZ(Players['Team games']))
        a = dfAdjusted[f'{key_par} per fixture adj']
        dfAdjusted.insert(n+1, f'{key_par} per game adj', a*Players['Team games']/noZ(Players['Played']))
    
    
    return dfAd, dfAdjusted
        
if __name__ == '__main__':
    year = ''
    Understat = Source('Understat', ma_num=7, year=year)
    Understat.test(year)
    FPL = Source('FPL', ma_num=7, year=year)
    FPL.test(year)
    #display(MA(Understat.TeamThreatAd, 8))
    print('End')
    pass

Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.060973167419433594 sec
	 2. Constants and Functions are over.	 It takes 0.0009906291961669922 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.5560863018035889 sec
		 3.2. Team_xA is over.	 It takes 0.6196436882019043 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.6086330413818359 sec
		 3.3.99 Creating coeffitients is over.	 It takes 0.048966169357299805 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.04397463798522949 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.04297375679016113 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.042998313903808594 sec
		 3.7. TableTeams is over.	 It takes 0.0049741268157958984 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 16.563619136810303 sec
		 4.2. Player_xA is over.	 It takes 16.974987506866455 sec
		 4.2.99 Creating coeffitients is over.	 It takes 0.4717090129852295 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.7495636940002441 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.7185723781585693 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 0.6925876140594482 sec
		 5.2. Visualizing futures.	 It takes 0.6867344379425049 sec
	 6. Writing to files is over.	 It takes 44.305742025375366 sec
Understat is created./t It takes 83.19472861289978 sec

                       player  element  fixture  minutes  FPL_minutes
0  David Luiz Moreira Marinho      3.0       89       56           45
1     Willian Borges Da Silva    478.0       89       75           64
2                 Rob Holding     16.0       89       34           45
3      Daniel Castelo Podence    469.0       89       80           69
4                 Fabio Silva    504.0       89       74           63

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 7.946328401565552 sec


Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.07395744323730469 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.6126337051391602 sec
		 3.2. Team_xA is over.	 It takes 0.5746569633483887 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.7016818523406982 sec
		 3.3.99 Creating coeffitients is over.	 It takes 0.052967071533203125 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.051969051361083984 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.04797244071960449 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.051976680755615234 sec
		 3.7. TableTeams is over.	 It takes 0.003997802734375 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 18.83316469192505 sec
		 4.2. Player_xA is over.	 It takes 18.03291654586792 sec
		 4.2.99 Creating coeffitients is over.	 It takes 0.4607264995574951 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.6989030838012695 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.6813108921051025 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 0.7683277130126953 sec
		 5.2. Visualizing futures.	 It takes 0.6925866603851318 sec
	 6. Writing to files is over.	 It takes 45.4898157119751 sec
FPL is created./t It takes 87.83457374572754 sec
	 FPL Testing is over.	 It takes 0.25934481620788574 sec


End

In [18]:
def write_table(df, name, key_col, xdf, class_args):
    '''
        Writing final tables to files and returning table itself and MA variant also
        df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
        source - Understat or FPL, ma_num - number for MA(currently unused just calculated)
    '''
    def GW_forecast (df, xdf):
    #     a = df.copy()
        lastGW = get_gw_num(del_empty_col(df.copy()).columns[-1])
        Table = pd.DataFrame()
        for i in df.columns:
            Table[i] = [df.at[j,i] if np.isnan(xdf.at[j,i]) else xdf.at[j,i] for j in df.index]

        column_numbers = np.asarray(list(map(get_gw_num, Table.columns)))
        if max(column_numbers)>lastGW:
            n = lastGW + 1
        else:
            n = lastGW
        for i in Table.columns:
            if get_gw_num(i) > n:
                del Table[i]
        return Table 
    def table2string(table):
        '''
        Converts table to view suitable for html. All number columns are actually strings with 1 digit after .
        '''
        df = table.copy()
        for j in df.columns:
            if ('GW' in j)|(' av' in j)|('xG' in j)|('xA' in j):
                df[j] = [str(int(df.at[i,j]*10)/10) if not np.isnan(df.at[i,j]) else '' for i in df.index]

        return df
    
    df = df.copy() # not to change initial df
    Teams, Players = class_args[:2]
    source, ma_num, folder = class_args[5:]
    
    F_UF = pd.DataFrame()
    for i in df.columns:
#         nan1 = np.isnan(xdf.at[j,i])
#         nan2 = not np.isnan(df.at[j,i])
        F_UF[i]=[np.nan if np.isnan(xdf.at[j,i])&np.isnan(df.at[j,i]) else 1 for j in df.index]
        F_UF[i] = [np.nan if np.isnan(F_UF.at[j,i]) else 1 if np.isnan(xdf.at[j,i]) else 0 for j in df.index]
    display(F_UF)
    
    if name != 'TableTeams':
        if 'Team' in name:
            X = Teams.copy()
            X.columns = ['id', 'Teams', key_col, 'Matches']
            X[key_col] = df.mean(axis=1)
        else:
            X = Players.copy()
            n = Players.columns.get_loc('Team games')
            X.insert( n, key_col, df.mean(axis=1))
            X.insert(n + 1, key_col.replace('fixture','game'),X[key_col]*Players['Team games']/noZ(Players['Played']))
            
        df = GW_forecast(df, xdf)
        
        Y = df[df.columns[::-1]]
        X[Y.columns] = Y.copy()
        df = X.copy()
        del_empty_col(df)
    
    #Removes redundant columns
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    
    # Sort decreasing for attack an increasing for defence
    if 'Opponent' in name:
        df.sort_values(key_col, ascending = True, inplace = True)
    else:
        df.sort_values(key_col, ascending = False, inplace = True)
    
    df.index = np.arange(1, len(df) + 1)
    
    # If moving average number is 0 no calculation needed. Use it to fasten the debug!
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    
    #Writes result to file
    df.to_csv(Path(f'{folder}out/{source}/{name}.csv'))
    
    
    # Add table created as table of stringe to existing html file replacing table tag with a new one
    #Also adding a new css
    if folder == '':
        dfString = table2string(df)
        
        
        
        
        
        
#         for i in dfString.columns:
#             dfString[i]=[[dfString.at[j,i],1] if np.isnan(xdf.at[j,i]) else [dfString.at[j,i],0] for j in dfString.index]
        
        
        dfStringStyler = dfString.style.apply(color_table, args=F_UF, axis=None)
        dfStringStyler.set_table_attributes('class="DataTable"')
        html_table = dfStringStyler.render().replace('\n', '')
        BS_table = BeautifulSoup(html_table, 'html.parser')
        css = str(BS_table('style')[0])
        html_ = str(BS_table('table')[0])

        #Getting right paths for different tables
        if source=='FPL' and name=='TableTeams':
            html_path = Path(f'{folder}index.html')
            css_path = Path(f'{folder}html/FPL/css/TableTeams.css')
        else:
            html_path = Path(f'{folder}html/{source}/{name}.html')
            css_path = Path(f'{folder}html/{source}/css/{name}.css')

        #Making css for coloring butons

        css = ('#' + source + '-button {\n background-color: #82f5cf;\n}\n' +
               '#' + name + ' {\n background-color: lightgrey;\n}\n' + 
               css)

        #Rewriting html and css
        with open(f'{folder}index.html', 'r', encoding="utf-8") as file:
            old_file = file.read()
        tag_to_replace1 = str(BeautifulSoup(old_file, 'html.parser')('table', attrs={"class":"DataTable"})[0])
        tag_to_replace2 = str(BeautifulSoup(old_file, 'html.parser')('h2', attrs={"id":"DataTitle"})[0])
        new_file = old_file.replace(tag_to_replace1, html_)
        new_file = new_file.replace(tag_to_replace2, f'<h2 id="DataTitle"> {html_table_name(name)} </h2>')

        #Making links right

        if not(source=='FPL' and name=='TableTeams'):
            new_file = new_file.replace('html/FPL/', '')
            new_file = new_file.replace('"out/FPL/TableTeams.csv"', f'"../../out/{source}/{name}.csv"')#Download button
            new_file = new_file.replace(f'TableTeams', name)
            if name != 'TableTeams': #changes links for buttons FPL and Understat
                str1 = 'class="header-form" action="index.html"'
                str2 = f'class="header-form" action="../FPL/{name}.html"'
                new_file = new_file.replace(str1, str2)
            else:
                new_file = new_file.replace('form action="index.html"', f'form action="../../index.html"')
            new_file = new_file.replace('html/', '../')
            new_file = new_file.replace('"index.html"', '"../../index.html"')

        #Creating .html and special files for the Table
        with open(html_path, 'w', encoding="utf-8") as file:
            file.write(new_file)
        with open(css_path, 'w', encoding="utf-8") as file:
            file.write(css)
    
    return df, dfStringStyler

def color_table(df, F_UF):
    '''
        Makes colored tables
    '''
    def table_type(df):
        '''
            Detecting the type of the table (TableTeams, Defence, Team, Player)
        '''
        if df.columns[2]=='xG': return 'TableTeams'
        elif 'Opponent' in df.columns[1]: return 'Defence'
        elif df.columns[0]=='Teams': return 'Team'
        else: return 'Player'
        
    def color_Team_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Player_xG(val):
        if val=='': color = 'white'
        elif float(val)>50: color = '#09bb9f'
        elif float(val)>25: color = '#82f5cf'
        elif float(val)>10: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Defence(val):
        if val=='': color = 'white'
        elif float(val)<120: color = '#09bb9f'
        elif float(val)<150: color = '#82f5cf'
        elif float(val)<180: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    
    def color_xTeam_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'background: repeating-linear-gradient( 45deg, {color}, {color} 10px, white 10px, white 20px);'
    
    def color_table_row(row, x, F_UF):
        '''
            function for style.apply by rows where x is a table type
            Subfunction of color_table_row
        '''
        str1 = 'Background-color: white'
        tw = (row.name in ['Matches', 'Teams'])
        pw = (row.name  in ['Team games', 'Played', 'Name', 'Team'])
        ttw = (row.name in ['xG adjusted', 'xG', 'xA', 'xA adjusted'])
        
        if x=='Team':
            return [color_Team_xG(row[i]) if (not tw)&(F_UF.at[i, row.name]==1) else color_xTeam_xG(row[i]) \
            if not tw else str1 for i in range(len(row))]
        elif x=='Player':
            return [color_Player_xG(i) if not pw else str1 for i in row]
        elif x=='Defence':
            return [color_Defence(i) if not tw else str1 for i in row]
        elif x=='TableTeams':
            return [color_Team_xG(i) if ttw else str1 if row.name in ['Team'] else color_Defence(i) for i in row]
        
    return df.apply(color_table_row, args=(table_type(df), F_UF), axis=0)

df, dfStringStyler = write_table(FPL.TxG, 'Team_xG', 'xG av', FPL.TxxG, FPL.class_args)
FPL.Team_xxG
dfStringStyler

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
1,NaN,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
2,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
3,NaN,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
4,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
5,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
6,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
7,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,NaN,0,0,0,0,0
8,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
9,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
10,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
11,NaN,1,1,1,1,1,1,1,1,1,...,0,0,0,0,NaN,0,0,0,0,0
12,NaN,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
13,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
14,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
15,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,NaN,0,0,0,0,0
16,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,NaN,0,0,0,0,0
17,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
18,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0
19,1.0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0.0,0,0,0,0,0

TypeError: color_table() got an unexpected keyword argument 'args'

In [72]:
TxG = FPL.TxG
TxxG = FPL.TxxG
lastGW = FPL.lastGW 

Table = pd.DataFrame()
for i in TxG.columns:
    Table[i] = [TxG.at[j,i] if np.isnan(TxxG.at[j,i]) else TxxG.at[j,i] for j in TxG.index]
    
column_numbers = np.asarray(list(map(get_gw_num, Table.columns)))
if max(column_numbers)>lastGW:
    n = lastGW + 1
else:
    n = lastGW
for i in Table.columns:
    if get_gw_num(i) > n:
        del Table[i]
Table

def GW_forecast (df, xdf):
#     a = df.copy()
    lastGW = get_gw_num(del_empty_col(df.copy()).columns[-1])
    Table = pd.DataFrame()
    for i in df.columns:
        Table[i] = [df.at[j,i] if np.isnan(xdf.at[j,i]) else xdf.at[j,i] for j in df.index]

    column_numbers = np.asarray(list(map(get_gw_num, Table.columns)))
    if max(column_numbers)>lastGW:
        n = lastGW + 1
    else:
        n = lastGW
    for i in Table.columns:
        if get_gw_num(i) > n:
            del Table[i]
    return Table    
        
GW_forecast(FPL.TOxG, FPL.TxOxG)
#get_gw_num(del_empty_col(TxG).columns[-1])

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW17,GW18,GW19,GW19*,GW20,GW21,GW22,GW23,GW24,GW24*
0,39.0,156.0,268.0,70.0,193.0,58.0,109.0,307.0,213.0,176.0,...,67.0,137.0,48.0,NaN,147.0,140.0,124.0,160.0,166.315901,NaN
1,NaN,56.0,174.0,264.0,151.0,324.0,75.0,125.0,101.0,107.0,...,263.0,NaN,468.0,67.0,133.0,309.0,242.0,193.0,174.798777,NaN
2,150.0,43.0,123.0,184.0,29.0,78.0,90.0,40.0,195.0,80.0,...,126.0,276.0,100.0,NaN,119.0,121.0,131.0,281.0,182.733306,NaN
3,NaN,270.0,59.0,139.0,173.0,169.0,202.0,284.0,205.0,222.0,...,NaN,199.0,225.0,337.0,268.0,268.0,227.0,70.0,149.753869,175.443143
4,123.0,227.0,105.0,51.0,177.0,148.0,27.0,79.0,79.0,55.0,...,224.0,NaN,115.0,115.0,18.0,25.0,48.0,104.0,79.670427,NaN
5,137.0,206.0,145.0,207.0,245.0,160.0,161.0,102.0,141.0,130.0,...,111.0,118.0,180.0,NaN,264.0,108.0,258.0,224.0,130.871237,NaN
6,187.0,83.0,139.0,176.0,279.0,142.0,158.0,142.0,168.0,260.0,...,131.0,121.0,NaN,NaN,244.0,156.0,221.0,185.0,154.854117,235.000969
7,232.0,147.0,191.0,165.0,119.0,276.0,111.0,182.0,209.0,214.0,...,NaN,188.0,278.0,180.0,248.0,76.0,158.0,80.0,156.329390,129.869287
8,70.0,180.0,147.0,193.0,140.0,171.0,138.0,74.0,343.0,141.0,...,96.0,NaN,85.0,140.0,106.0,205.0,128.0,130.0,192.968105,NaN
9,385.0,143.0,182.0,248.0,102.0,154.0,176.0,155.0,82.0,173.0,...,254.0,NaN,105.0,NaN,180.0,197.0,131.0,101.0,193.542611,NaN
10,98.0,73.0,68.0,268.0,118.0,164.0,77.0,76.0,154.0,129.0,...,51.0,NaN,129.0,83.0,44.0,132.0,162.0,167.0,112.299888,NaN
11,NaN,92.0,123.0,245.0,120.0,56.0,51.0,126.0,56.0,73.0,...,133.0,44.0,34.0,108.0,58.0,35.0,23.0,116.0,78.817790,79.318217
12,NaN,167.0,206.0,311.0,106.0,87.0,59.0,81.0,71.0,126.0,...,216.0,105.0,245.0,143.0,95.0,154.0,14.0,118.0,89.157977,NaN
13,209.0,139.0,365.0,133.0,367.0,119.0,198.0,204.0,167.0,124.0,...,90.0,258.0,229.0,166.0,136.0,120.0,72.0,212.0,225.404598,NaN
14,111.0,213.0,181.0,127.0,156.0,237.0,232.0,286.0,233.0,180.0,...,125.0,78.0,171.0,NaN,190.0,190.0,166.0,138.0,187.790635,NaN
15,77.0,164.0,124.0,66.0,223.0,95.0,343.0,46.0,259.0,194.0,...,228.0,NaN,195.0,NaN,135.0,123.0,392.0,90.0,134.517627,NaN
16,160.0,175.0,86.0,63.0,195.0,122.0,108.0,128.0,339.0,121.0,...,183.0,175.0,177.0,NaN,205.0,237.0,255.0,51.0,240.221429,NaN
17,211.0,313.0,287.0,156.0,118.0,77.0,177.0,221.0,274.0,281.0,...,321.0,NaN,259.0,186.0,290.0,154.0,196.0,194.0,266.747523,NaN
18,180.0,137.0,128.0,70.0,145.0,195.0,146.0,167.0,110.0,159.0,...,98.0,NaN,112.0,61.0,76.0,174.0,116.0,176.0,106.762577,NaN
19,128.0,186.0,179.0,104.0,178.0,68.0,176.0,109.0,113.0,175.0,...,222.0,92.0,151.0,NaN,194.0,100.0,149.0,143.0,128.277178,NaN

In [39]:
TxG.at[0, 'GW1']

232.0

In [64]:
TxG

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW15,GW16,GW17,GW18,GW19,GW19*,GW20,GW21,GW22,GW23
0,232.0,137.0,68.0,127.0,120.0,171.0,59.0,125.0,82.0,175.0,...,201.0,135.0,321.0,118.0,229.0,NaN,135.0,154.0,149.0,193.0
1,NaN,213.0,191.0,268.0,140.0,154.0,343.0,307.0,195.0,159.0,...,327.0,137.0,216.0,NaN,108.0,166.0,268.0,123.0,116.0,160.0
2,123.0,139.0,206.0,176.0,245.0,77.0,108.0,284.0,101.0,129.0,...,168.0,176.0,222.0,44.0,105.0,NaN,248.0,237.0,162.0,70.0
3,NaN,180.0,124.0,133.0,118.0,122.0,27.0,40.0,141.0,73.0,...,237.0,90.0,NaN,105.0,112.0,83.0,133.0,25.0,23.0,281.0
4,150.0,73.0,287.0,207.0,223.0,87.0,202.0,286.0,167.0,121.0,...,208.0,175.0,133.0,NaN,278.0,140.0,194.0,268.0,255.0,138.0
5,77.0,167.0,139.0,51.0,29.0,276.0,176.0,155.0,205.0,124.0,...,120.0,36.0,125.0,137.0,34.0,NaN,76.0,100.0,72.0,101.0
6,160.0,313.0,145.0,184.0,118.0,95.0,198.0,81.0,209.0,173.0,...,97.0,NaN,98.0,92.0,NaN,NaN,106.0,120.0,131.0,118.0
7,39.0,143.0,174.0,104.0,156.0,160.0,177.0,167.0,168.0,141.0,...,128.0,NaN,NaN,175.0,115.0,143.0,119.0,154.0,128.0,176.0
8,211.0,270.0,123.0,70.0,151.0,58.0,176.0,109.0,154.0,214.0,...,99.0,132.0,90.0,NaN,195.0,115.0,244.0,197.0,158.0,143.0
9,98.0,147.0,181.0,245.0,178.0,324.0,138.0,102.0,213.0,260.0,...,121.0,183.0,183.0,NaN,100.0,NaN,136.0,205.0,221.0,224.0
10,385.0,227.0,268.0,264.0,279.0,237.0,146.0,126.0,343.0,80.0,...,186.0,150.0,228.0,NaN,245.0,337.0,205.0,174.0,131.0,116.0
11,NaN,186.0,147.0,248.0,193.0,195.0,232.0,76.0,339.0,222.0,...,233.0,NaN,224.0,276.0,180.0,468.0,290.0,190.0,227.0,167.0
12,NaN,206.0,123.0,63.0,367.0,148.0,109.0,142.0,274.0,194.0,...,108.0,158.0,263.0,199.0,129.0,180.0,190.0,140.0,392.0,185.0
13,180.0,43.0,86.0,139.0,106.0,68.0,158.0,46.0,79.0,130.0,...,69.0,99.0,96.0,78.0,48.0,67.0,180.0,156.0,258.0,90.0
14,128.0,56.0,182.0,70.0,119.0,164.0,51.0,79.0,110.0,281.0,...,129.0,106.0,111.0,258.0,177.0,NaN,95.0,35.0,196.0,104.0
15,137.0,175.0,59.0,156.0,177.0,142.0,75.0,204.0,113.0,126.0,...,30.0,104.0,51.0,NaN,85.0,NaN,147.0,309.0,14.0,212.0
16,187.0,164.0,365.0,311.0,145.0,169.0,90.0,221.0,56.0,55.0,...,84.0,NaN,254.0,188.0,171.0,NaN,44.0,121.0,48.0,194.0
17,70.0,83.0,105.0,66.0,173.0,78.0,111.0,128.0,71.0,180.0,...,65.0,46.0,67.0,NaN,151.0,61.0,58.0,76.0,166.0,51.0
18,209.0,156.0,179.0,193.0,195.0,56.0,77.0,182.0,233.0,107.0,...,211.0,152.0,131.0,NaN,225.0,186.0,264.0,132.0,242.0,80.0
19,111.0,92.0,128.0,165.0,102.0,119.0,161.0,74.0,259.0,176.0,...,184.0,133.0,126.0,121.0,259.0,NaN,18.0,108.0,124.0,130.0