In [1]:
from time import time
import constti
from Brr_functions import no_lists, toint, noZ
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path

class Source:
    #def adjustment(df)
    def __init__(self, source, ma_num=0):
        self.source = source
        print(f'Start Creating {self.source} Tables:')
        start_module = time()
        start = time()
        self.ma_num = ma_num # Number of matches for the moving average
        
#1. Reading nessesry data from files.
        
        Table = pd.read_csv(Path('in/Table_'+source+'.csv')) # Main data from source containing rows for each player
        #in a game with columns 'element', 'round', 'fixture', 'threat', 'creativity', 'team', opponent_team'
        Fixtures = pd.read_csv(Path('in/Fixtures.csv')) # Table of rows for each fixture
        Teams = pd.read_csv(Path('in/Teams.csv')) # Table of rows as teams with columns 'id', 'Teams',
        #'TARGET COL', 'Matches'
        Players = pd.read_csv(Path('in/Players.csv')) # Table of rows as players with columns 'id', 'Name',
        #'Team', Team games', 'Played'
        del Players['web_name'] #This column is needed only for inputUnderstat.py
        
        #Reading Fxtures and Opponents for Teams and Players
        with open('in/Team_fixtures.txt', 'r') as file:
            Team_fixtures = pd.DataFrame(json.loads(file.read()))
            Team_fixtures.index = pd.to_numeric(Team_fixtures.index)
            Team_fixtures = Team_fixtures.sort_index()
        with open('in/Team_opponent_team.txt', 'r') as file:
            Team_opponent_team = pd.DataFrame(json.loads(file.read()))
            Team_opponent_team.index = pd.to_numeric(Team_opponent_team.index)
            Team_opponent_team = Team_opponent_team.sort_index()
        with open('in/Player_fixtures.txt', 'r') as file:
            Player_fixtures = pd.DataFrame(json.loads(file.read()))
            Player_fixtures.index = pd.to_numeric(Player_fixtures.index)
            Player_fixtures = Player_fixtures.sort_index()
        with open('in/Player_opponent_team.txt', 'r') as file:
            Player_opponent_team = pd.DataFrame(json.loads(file.read()))
            Player_opponent_team.index = pd.to_numeric(Player_opponent_team.index)
            Player_opponent_team = Player_opponent_team.sort_index()
        
        print('\t 1. Reading files from ' + source +' is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

#2. Defenition of useful constants and funtions
        
        #Teams in Premier League
        team_number = len(Teams)

        #Calculating lastGW - last gameweek with at least one game played
        firstr = len(Fixtures)+1
        lastr = 0
        for i in range(len(Fixtures)):
            if Fixtures.at[i,'finished']==True:
                firstr = min(firstr, i)
                lastr = i
        if firstr < len(Fixtures)+1:
            lastGW = int(Fixtures.at[lastr,'event'])
        else: lastGW = 0
        if lastr == len(Fixtures):
            lastGW = int(Fixtures.at[lastr,'event'])

        print('\t 2. Constants and Functions are over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 3. Calculating team tables

        print('\t 3. Calculating team tables')

        #(1). Creating  a table with average threat and GW threats for teams

        TeamThreat = Teams.copy()
        TeamThreat.columns = ['id', 'Teams', 'Threat av', 'Matches']

        for j in range(lastGW,0,-1):
            TeamThreat['Threat GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_fixtures.at[i, 'GW'+str(j)])):
                    TeamThreat.at[i,'Threat GW'+str(j)].append(Table[(Table['fixture']==\
                                        Team_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['threat'].sum())


        TeamThreat['Threat av'] = [Table[Table['team']==i]['threat'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        TeamThreat.sort_values('Threat av', ascending = False, inplace = True)

        print('\t\t 3.1. TeamThreat is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2). Creating  a table with average creativity and GW creativities for teams

        TeamCreativity = Teams.copy()
        TeamCreativity.columns = ['id', 'Teams', 'Creativity av', 'Matches']

        for j in range(lastGW,0,-1):
            TeamCreativity['Creativity GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_fixtures.at[i, 'GW'+str(j)])):
                    TeamCreativity.at[i,'Creativity GW'+str(j)].append(Table[(Table['fixture']==\
                                    Team_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['creativity'].sum())


        TeamCreativity['Creativity av'] = [Table[Table['team']==i]['creativity'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        
        print('\t\t 3.2. TeamCreativity is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()
        
        #(3). Creating  a table with average threat allowed by teams and GW threat allowed

        TableDefence = Teams.copy()
        TableDefence.columns = ['id', 'Teams', 'Threat allowed av', 'Matches']

        for j in range(lastGW,0,-1):
            TableDefence['Threat allowed GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_fixtures.at[i, 'GW'+str(j)])):
                    TableDefence.at[i,'Threat allowed GW'+str(j)].append(Table[(Table['fixture']== \
                        Team_fixtures.at[i, 'GW'+str(j)][k])&(Table['opponent_team']==i+1)]['threat'].sum())


        TableDefence['Threat allowed av'] = [Table[Table['opponent_team']==i]['threat'].sum()
                        for i in range(1,team_number+1)]/noZ(Teams['Matches'])

        threatAllowedAv = TableDefence['Threat allowed av'].mean()
        
        print('\t\t 3.3. TeamDefence is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        class_data = [Teams, Players, Team_fixtures, Player_fixtures, Team_opponent_team,\
        Player_opponent_team, TeamThreat, TableDefence, threatAllowedAv, lastGW]\

        #(4). Creating  a table with average adjusted threat and GW threats adj for teams

        TeamThreatAd = adjustment(TeamThreat, class_data)       
        print('\t\t 3.4. TeamThreatAd is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(5). Creating  a table with average adjusted creativity and GW creativities adj for teams
        
        TeamCreativityAd = adjustment(TeamCreativity, class_data)
        print('\t\t 3.5. TeamCreativityAd is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(6). Creating  a table with average threat allowed adjusted by teams and GW threat allowed adjusted

        TableDefenceAd = adjustment(TableDefence, class_data)
        print('\t\t 3.6. TeamDefenceAd is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()


        #(7) Total Team Table

        TableTeams = pd.DataFrame()
        TableTeams['id'] = Teams['id']
        TableTeams['Team'] = Teams['Teams']

        TableTeams['Threat adjusted'] = TeamThreatAd['Threat av adj']
        TableTeams['Threat'] = TeamThreat['Threat av']
        TableTeams['Creativity adjusted'] = TeamCreativityAd['Creativity av adj']
        TableTeams['Creativity'] = TeamCreativity['Creativity av']
        TableTeams['Threat allowed adjusted'] = TableDefenceAd['Threat allowed av adj']
        TableTeams['Threat allowed'] = TableDefence['Threat allowed av']
        
        print('\t\t 3.7. TableTeams is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 4. Calculating pLayer tables
        
        print('\t 4. Calculating player tables')

        #(1) Players Threat

        PlayerThreat = Players.copy()
        #PlayerThreat['Threat per fixture'] = np.zeros(len(Players))
        #PlayerThreat['Threat per game'] = np.zeros(len(Players))
        PlayerThreat.insert(PlayerThreat.columns.get_loc('Team games'), 'Threat per fixture',\
        [0.0 for i in PlayerThreat.itertuples()])
        PlayerThreat.insert(PlayerThreat.columns.get_loc('Team games'), 'Threat per game',\
        [0.0 for i in PlayerThreat.itertuples()])

        for j in range(lastGW,0,-1):
            PlayerThreat['Threat GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_fixtures.at[i, 'GW'+str(j)])):
                    PlayerThreat.at[i,'Threat GW'+str(j)].append(Table[(Table['fixture']==\
                        Player_fixtures.at[i, 'GW'+str(j)][k])&(Table['element']==\
                        PlayerThreat.at[i,'id'])]['threat'].sum())
                    PlayerThreat.at[i,'Threat per game'] = PlayerThreat.at[i,'Threat per game'] +\
                        PlayerThreat.at[i,'Threat GW'+str(j)][k]


        PlayerThreat['Threat per fixture'] = PlayerThreat['Threat per game']/noZ(Players['Team games'])
        PlayerThreat['Threat per game'] = PlayerThreat['Threat per game']/noZ(Players['Played'])
        
        print('\t\t 4.1. PlayerThreat is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Players Creativity

        PlayerCreativity = Players.copy()
        #PlayerCreativity['Creativity per fixture'] = np.zeros(len(Players))
        #PlayerCreativity['Creativity per game'] = np.zeros(len(Players))
        PlayerCreativity.insert(PlayerCreativity.columns.get_loc('Team games'), 'Creativity per fixture',\
        [0.0 for i in PlayerCreativity.itertuples()])
        PlayerCreativity.insert(PlayerCreativity.columns.get_loc('Team games'), 'Creativity per game',\
        [0.0 for i in PlayerCreativity.itertuples()])

        for j in range(lastGW,0,-1):
            PlayerCreativity['Creativity GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_fixtures.at[i, 'GW'+str(j)])):
                    PlayerCreativity.at[i,'Creativity GW'+str(j)].append(Table[(Table['fixture']==\
                                                Player_fixtures.at[i, 'GW'+str(j)][k])&\
                                                (Table['element']==PlayerCreativity.at[i,'id'])]['creativity'].sum())
                    PlayerCreativity.at[i,'Creativity per game'] = PlayerCreativity.at[i,'Creativity per game'] +\
                        PlayerCreativity.at[i,'Creativity GW'+str(j)][k]


        PlayerCreativity['Creativity per fixture'] = PlayerCreativity['Creativity per game']/noZ(Players['Team games'])
        PlayerCreativity['Creativity per game'] = PlayerCreativity['Creativity per game']/noZ(Players['Played'])
        
        print('\t\t 4.2. PlayerCreativity is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(3) Players Threat Adjusted
        
        PlayerThreatAd = adjustment(PlayerThreat, class_data)
        print('\t\t 4.3. PlayerThreatAd is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        #(4) PLayers Creativity Adjusted
        
        PlayerCreativityAd = adjustment(PlayerCreativity, class_data)    
        print('\t\t 4.4. PlayerCreativityAd is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 5. Writing tables to files (and variables to class.variables)
        
        # Useful variables for debugging
        self.Table = Table
        self.Fixtures = Fixtures
        self.Teams = Teams
        self.Players = Players
        
        self.threatAllowedAv = threatAllowedAv
        self.Team_fixtures = Team_fixtures
        self.Team_opponent_team = Team_opponent_team
        self.Player_fixtures = Player_fixtures
        self.Player_opponent_team = Player_opponent_team
        
        #Save before modifying while riting into files
        self.TT = TeamThreat.copy()
        self.TC = TeamCreativity.copy()
        self.TD = TableDefence.copy()
        self.TTA = TeamThreatAd.copy()
        self.TCA = TeamCreativityAd.copy()
        self.TDA = TableDefenceAd.copy()
        self.TaTe = TableTeams.copy() 
        self.PT = PlayerThreat.copy()
        self.PC = PlayerCreativity.copy()
        self.PTA = PlayerThreatAd.copy()
        self.PCA = PlayerCreativityAd.copy()
        
        self.TeamThreat, self.TeamThreat_MA =\
            write_table(TeamThreat, 'TeamThreat', 'Threat av', self.source, self.ma_num)
        self.TeamCreativity, self.Creativity_MA = (write_table
            (TeamCreativity, 'TeamCreativity', 'Creativity av', self.source, self.ma_num))
        self.TableDefence, self.TableDefence_MA =\
            write_table(TableDefence, 'TableDefence', 'Threat allowed av', self.source, self.ma_num)
        self.TeamThreatAd, self.TeamThreatAd_MA =\
            write_table(TeamThreatAd, 'TeamThreatAd', 'Threat av adj', self.source, self.ma_num)
        self.TeamCreativityAd, self.CreativityAd_MA =\
            write_table(TeamCreativityAd, 'TeamCreativityAd', 'Creativity av adj', self.source, self.ma_num)
        self.TableDefenceAd, self.TableDefenceAd_MA =\
            write_table(TableDefenceAd, 'TableDefenceAd', 'Threat allowed av adj', self.source, self.ma_num)
        self.TableTeams, self.TableTeams_MA =\
            write_table(TableTeams, 'TableTeams', 'Threat adjusted', self.source, self.ma_num)
        
        self.PlayerThreat, self.PlayerThreat_MA =\
            write_table(PlayerThreat, 'PlayerThreat', 'Threat per fixture', self.source, self.ma_num)
        self.PlayerCreativity, self.PlayerCreativity_MA =\
            write_table(PlayerCreativity, 'PlayerCreativity', 'Creativity per fixture', self.source, self.ma_num)
        self.PlayerThreatAd, self.PlayerThreatAd_MA =\
            write_table(PlayerThreatAd, 'PlayerThreatAd', 'Threat per fixture adj', self.source, self.ma_num)
        self.PlayerCreativityAd, self.PlayerCreativityAd_MA =\
            write_table(PlayerCreativityAd, 'PlayerCreativityAd', 'Creativity per fixture adj', self.source, self.ma_num)
        
        print('\t 5. Writing to files is over.\t It takes ' + str(time() - start) + ' sec')
        print(f'{self.source} is created./t It takes {time() - start_module} sec\n')
        start = time()

# 6. Tests for each element of the class
    
    # Checks if all names in the source can be found in fantasy.premierleague.com (FPL)
    def test2FPL(self):
        FPL = pd.read_csv('in/Table_FPL.csv')
        Table_Source = pd.read_csv('in/Table_'+self.source+'.csv')
        Mistakes = pd.DataFrame()
        No_Names = pd.DataFrame()
        if self.source == 'FPL':
            return Mistakes, No_Names
        for i in Table_Source.index:
            if Table_Source.at[i,'element'] < 1000000:
                FPLmin = FPL[(FPL['element'] == Table_Source.at[i,'element'])&\
                            (FPL['fixture'] == Table_Source.at[i,'fixture'])]['minutes'].sum()
                if abs(Table_Source.at[i,'minutes'] - FPLmin) > 10:
                    Mistakes = Mistakes.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'element'],\
                        Table_Source.at[i,'fixture'], Table_Source.at[i,'minutes'], FPLmin]], columns = ['player',\
                        'element', 'fixture', 'minutes', 'FPL_minutes']), ignore_index=True)
            else:
                 No_Names = No_Names.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'fixture']]],\
                    columns = ['player', 'fixture']), ignore_index=True)
        display(Mistakes)
        display(No_Names)
        return Mistakes, No_Names
        
    def test(self):
        start = time()
        
        constti.DRDC(self.TeamThreat)
        constti.DRDC(self.TeamCreativity)
        constti.DRDC(self.TeamThreatAd)
        constti.DRDC(self.TeamCreativityAd)
        constti.DRDC(self.TableTeams)
        constti.DRDC(self.PlayerThreat)
        constti.DRDC(self.PlayerCreativity)
        constti.DRDC(self.PlayerThreatAd)
        constti.DRDC(self.PlayerCreativityAd)
        
        self.test2FPL()
        
        print(f'\t {self.source} Testing is over.\t It takes {time() - start} sec')

# 7. Useful not class functions

# Writing final tables to files and returning table itself and MA variant also
# df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
# source - Understat o FPL, ma_num - number for MA
def write_table(df, name, key_col, source, ma_num):
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    df.sort_values(key_col, ascending = False, inplace = True)
    df.index = np.arange(1, len(df) + 1)
    df = no_lists(df)
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    df_ma.to_csv(Path('out/' + source + '/' + name + '.csv'))
    return df, df_ma

# Returns the table with d mean average for table Out_T
# If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.


# def MA(Out_T, d):
#     # Filling the column with averages. Subfunction for MA
#     def d_av(T, j, GW_columns, d):
#         T[GW_columns[j] +' '+ str(d) + ' - average'] = [0.0 for i in T.itertuples()]
#         for i in T.index:
#             u = 0
#             k = 0
#             while (u < d)&(j-k>=0):
#                 if T.at[i, GW_columns[j-k]] != '':
#                     T.at[i, GW_columns[j] +' '+ str(d) + ' - average'] += T.at[i, GW_columns[j-k]]
#                     u+=1
#                     k+=1
#                 else: k+=1
#             if u==d:
#                 T.at[i, GW_columns[j] +' '+ str(d) + ' - average'] = T.at[i, GW_columns[j] +' '+ str(d) + ' - average']/d
#             else:
#                 T.loc[i, GW_columns[j] +' '+ str(d) + ' - average'] = ''
#         return T[GW_columns[j] +' '+ str(d) + ' - average']
#     T = Out_T.copy()
#     GW_columns = []
#     gw_col=0
#     for col in T.columns:
#         if 'GW' in col:
#             GW_columns.append(col)
#             gw_col+=1
#     GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)]
#     #print(GW_columns)
#     if d>gw_col:
#         return T
#     else:
#         for j in range(gw_col-1, d-2, -1):
#             #print(j)
#             T[GW_columns[j] +' '+ str(d) + ' - average'] = d_av(T, j, GW_columns, d)#[0 for i in T.itertuples()]
#     return T

def color(num, x):
    if x=='Team':
        if num == '':
            return 'white'
        elif num<120:
            return 'red'
        elif num<140:
            return 'pink'
        elif num<200:
            return 'light green'
        else:
            return 'green'
    elif x=='Defence':
        if num == '':
            return 'white'
        elif num<120:
            return 'green'
        elif num<150:
            return 'light green'
        elif num<180:
            return 'pink'
        else:
            return 'red'
    else: #'PLayer'
        if num == '':
            return 'white'
        elif num<10:
            return 'red'
        elif num<25:
            return 'pink'
        elif num<50:
            return 'light green'
        else:
            return 'green'

def MA(Out_T, d):
    
    # Filling the column with averages. Subfunction for MA
    #Adds d - averages for j-th GW_column (not GWj but j-th in order) of table T
    def d_av(T, j, GW_columns, d):
        #T = df.copy()
        #T[f'{GW_columns[j]} {str(d)} - average'] = [0.0 for i in T.itertuples()]
        T.insert(T.columns.get_loc(GW_columns[-1]), f'{GW_columns[j]} {str(d)} - average', [0.0 for i in T.itertuples()])
        for i in T.index:
            u = 0
            k = 0
            while (u < d)&(j-k>=0):
                if T.at[i, GW_columns[j-k]] != '':
                    T.at[i, f'{GW_columns[j]} {str(d)} - average'] += T.at[i, GW_columns[j-k]]
                    u+=1
                    k+=1
                else: k+=1
            if u==d:
                T.at[i, f'{GW_columns[j]} {str(d)} - average'] = T.at[i, f'{GW_columns[j]} {str(d)} - average']/d
            else:
                T.loc[i, f'{GW_columns[j]} {str(d)} - average'] = ''
        return None
    
    #Adds color columns for columns with GW data
    def color_columns(df, GW_columns, table_type):
        for i in range(len(GW_columns)):
            df.insert(df.columns.get_loc(GW_columns[i]), f'{GW_columns[i]} color',\
            df[GW_columns[i]].apply(lambda x: color(x, table_type)))
        return df
    
    
    #Adds color columns to the TableTeams table
    def colorTableTeams(T):
        df = T.copy()
        dfcol = df.columns.copy()
        for i in range(len(dfcol)):
            if 'allowed' in dfcol[i]:
                df.insert(df.columns.get_loc(dfcol[i]), f'{dfcol[i]} color',\
                df[dfcol[i]].apply(lambda x: color(x, 'Defence')))
            elif ('Threat' in dfcol[i]) | ('Creativity' in dfcol[i]):
                df.insert(df.columns.get_loc(dfcol[i]), f'{dfcol[i]} color',\
                df[dfcol[i]].apply(lambda x: color(x, 'Team')))
        return df
    
    
#     #Adds color columns to the TableTeams table
#     colorTableTeams(df):
#         for i in range(len(df.columns)):
#             if ('Threat' in df.columns[i]) ||
    
    
    
    
    
    T = Out_T.copy()
    
    #Creating the list of GW_columns for the table T
    GW_columns = []
    gw_col=0
    for col in T.columns:
        if 'GW' in col:
            GW_columns.append(col)
            gw_col+=1
    GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)] #makes the opposite order of the list
    #print(GW_columns)
    
    #Add averages for GW_columns using d_av function defined above
    if d>gw_col: #gw_col is the length of GW_columns
        #returning colored MA table depends on whether it is TableTeams or not
        if GW_columns == []: return colorTableTeams(T)
        else: return T
    else:
        for j in range(gw_col-1, d-2, -1):
            #print(j)
            #T[f'{GW_columns[j]} {str(d)} - average'] = d_av(T, j, GW_columns, d)
            #T.insert(T.columns.get_loc('Matches')+1, f'{GW_columns[j]} {str(d)} - average', d_av(T, j, GW_columns, d))
            d_av(T, j, GW_columns, d)
    #print(GW_columns[-1])
    if T.columns[0] == 'Name':
        table_type = 'Player'
    elif 'allowed' in GW_columns[0]:
        table_type = 'Defence'
    else:
        table_type = 'Team'
        

    return color_columns(T, GW_columns, table_type)
    
    
######################################For Debugging
# lastGW = 43
# team_number = 20
# Fixtures = Understat.Fixtures
# Table = Understat.Table
# Players = Understat.Players
# Teams = Understat.Teams
# threatAllowedAv = Understat.threatAllowedAv
# TableDefence = Understat.TD
# Team_fixtures = Understat.Team_fixtures
# Team_opponent_team = Understat.Team_opponent_team
# Player_opponent_team = Understat.Player_opponent_team
# Player_fixtures = Understat.Player_fixtures
# TeamThreat = Understat.TT
# PlayerCreativity = Understat.PC






def adjustment(df, class_data):
    [Teams, Players, Team_fixtures, Player_fixtures, Team_opponent_team, Player_opponent_team,\
     TeamThreat, TableDefence, threatAllowedAv, lastGW]\
    = class_data
    if len(df)==len(Teams):
        dfAd = Teams.copy()
        for i in df.columns:
            if ' av' in i:
                key_par = i[:-3]
        #key_par = df.columns[2][:-3]
        av  = 'av'
        dfAd.columns = ['id', 'Teams', f'{key_par} av adj', 'Matches']
        the_fixtures = Team_fixtures
        the_opponent_team = Team_opponent_team
    else:
        dfAd = Players.copy()
        for i in df.columns:
            if 'per fixture' in i:
                key_par = i[:-12]
        #key_par = df.columns[4][:-12]
        av = 'per game'
        #dfAd[f'{key_par} per fixture adj'] = np.zeros(len(Players))
        #dfAd[f'{key_par} per game adj'] = np.zeros(len(Players))
        
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per fixture adj',\
        [0.0 for i in dfAd.itertuples()])
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per game adj',\
        [0.0 for i in dfAd.itertuples()])
        
        
        the_fixtures = Player_fixtures
        the_opponent_team = Player_opponent_team
    #print(key_par)
    if key_par[-7:] == 'allowed':
        #print('Defence!')
        Weighting_table = TeamThreat
        col = 'Threat av'
    else:
        Weighting_table = TableDefence
        col = 'Threat allowed av'
        
    for j in range(lastGW,0,-1):
        dfAd[f'{key_par} GW{j} adj'] = [[] for _ in range(len(df))]
        for i in range(len(df)):
             for k in range(len(the_fixtures.at[i, 'GW'+str(j)])):
                #print(f'{TeamThreat.at[i,f'Threat GW{j}']} {Team_opponent_team.at[i,f'GW{j}']} {})
                dfAd.at[i,f'{key_par} GW{j} adj'].append(df.at[i,f'{key_par} GW{j}'][k]\
                *threatAllowedAv/ Weighting_table.at[the_opponent_team.at[i,f'GW{j}'][k]-1, col])

                dfAd.at[i,f'{key_par} {av} adj'] += dfAd.at[i,f'{key_par} GW{j} adj'][k]

    if len(df) == len(Teams): dfAd[f'{key_par} av adj'] = dfAd[f'{key_par} av adj']/noZ(dfAd['Matches'])
    else:
        dfAd[f'{key_par} per fixture adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Team games'])
        dfAd[f'{key_par} per game adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Played'])
    
    
    return dfAd
        
if __name__ == '__main__':
    Understat = Source('Understat', ma_num=5)
    Understat.test()
    display(MA(Understat.TeamThreatAd, 8))
    pass

Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.8710033893585205 sec
	 2. Constants and Functions are over.	 It takes 0.00997471809387207 sec
	 3. Calculating team tables
		 3.1. TeamThreat is over.	 It takes 4.123458385467529 sec
		 3.2. TeamCreativity is over.	 It takes 3.852625846862793 sec
		 3.3. TeamDefence is over.	 It takes 3.632760524749756 sec
		 3.4. TeamThreatAd is over.	 It takes 0.1549074649810791 sec
		 3.5. TeamCreativityAd is over.	 It takes 0.22286081314086914 sec
		 3.6. TeamDefenceAd is over.	 It takes 0.22786688804626465 sec
		 3.7. TableTeams is over.	 It takes 0.036971092224121094 sec
	 4. Calculating player tables
		 4.1. PlayerThreat is over.	 It takes 94.29751014709473 sec
		 4.2. PlayerCreativity is over.	 It takes 102.8383195400238 sec
		 4.3. PlayerThreatAd is over.	 It takes 7.9740869998931885 sec
		 4.4. PlayerCreativityAd is over.	 It takes 6.184188604354858 sec
	 5. Writing to files is over.	 It takes 171.91452193260193 sec
Understat is created./t It takes 396.3480577468872 sec

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 47.49690055847168 sec

,Teams,Threat av adj,Matches,Threat GW47 adj 8 - average,Threat GW46 adj 8 - average,Threat GW45 adj 8 - average,Threat GW44 adj 8 - average,Threat GW43 adj 8 - average,Threat GW42 adj 8 - average,Threat GW41 adj 8 - average,...,Threat GW5 adj color,Threat GW5 adj,Threat GW4 adj color,Threat GW4 adj,Threat GW3 adj color,Threat GW3 adj,Threat GW2 adj color,Threat GW2 adj,Threat GW1 adj color,Threat GW1 adj
1,Man City,267.315127,38,286.618424,287.614675,271.173871,273.080931,244.105016,232.900056,232.826296,...,light green,175.763,green,207.933,green,268.102,green,323.348,green,253.933
2,Chelsea,206.779401,38,271.700002,261.690377,244.864578,238.083246,245.998880,231.417106,211.559451,...,green,440.213,green,236.551,light green,142.837,light green,140.04,light green,156.366
3,Liverpool,201.393811,38,169.718359,173.120093,169.445413,145.171541,142.267954,132.823687,168.998384,...,green,237.072,pink,121.879,green,263.464,light green,146.155,light green,167.577
4,Man Utd,172.703742,38,175.735728,177.912709,199.897222,194.102410,204.209062,188.336716,181.583996,...,pink,126.024,light green,182.807,green,214.887,light green,164.05,green,312.908
5,Leicester,154.919009,38,154.361296,152.763046,160.216920,134.352236,129.833754,127.457621,128.787620,...,red,65.3887,light green,192.684,red,72.3134,pink,125.085,red,78.0216
6,Southampton,152.400724,38,172.511893,168.980923,148.518465,130.580447,126.231461,102.630032,103.411002,...,light green,161.742,red,109.605,light green,188.495,green,293.649,red,110.402
7,Everton,146.127431,38,76.948111,69.241333,68.574477,103.200545,130.280255,155.490166,183.710439,...,pink,129.509,green,213.566,red,95.098,red,74.9037,red,117.014
8,Wolves,145.203220,38,107.678682,115.579062,107.808883,125.340003,119.467417,131.618546,147.434713,...,green,200.386,green,222.13,pink,135.147,red,43.7722,red,92.8369
9,Arsenal,136.800646,38,145.852614,131.756132,133.866771,126.873753,136.686316,148.809605,144.586825,...,red,90.4834,light green,194.468,pink,135.146,red,118.493,red,91.5923
10,West Ham,130.541744,38,169.272284,169.809031,166.105702,190.184417,163.865992,139.590409,133.098889,...,red,40.5067,light green,166.218,green,321.469,red,90.8567,light green,175.584
11,Burnley,130.253952,38,112.461332,96.477130,122.104722,100.825660,126.184359,126.403319,136.028740,...,red,31.4336,red,84.662,light green,176.325,pink,132.269,red,87.3185
12,Watford,129.555118,38,119.735494,86.963482,89.845622,127.610251,101.249266,97.609365,100.328924,...,green,268.499,red,90.086,light green,182.924,pink,132.073,red,60.4954
13,Spurs,127.191692,38,103.841213,109.705674,113.182230,127.830342,110.731415,146.694611,147.280178,...,red,98.9422,light green,191.536,red,101.951,red,10.9042,light green,195.391
14,Brighton,126.967598,38,107.895951,98.184882,95.076535,107.965772,118.828110,86.437050,98.234188,...,light green,171.287,pink,125.955,red,96.521,light green,191.871,red,76.9364
15,Bournemouth,126.622839,38,147.952259,131.921925,147.127366,142.855387,128.851198,131.288390,130.071123,...,light green,157.068,red,63.3484,green,276.98,pink,123.18,light green,198.466
16,Sheffield Utd,125.821126,38,117.913407,106.751398,102.484830,104.281752,89.236714,103.418732,92.953667,...,light green,180.578,pink,137.91,red,74.7217,light green,174.691,light green,171.892
17,Aston Villa,123.156371,38,100.070677,121.371201,127.526647,116.038611,101.701383,112.593106,116.286952,...,red,112.063,red,28.6179,red,94.9814,light green,141.082,red,64.3742
18,Norwich,101.232364,38,55.106276,48.405235,76.053822,83.460785,83.815218,77.591091,95.920609,...,green,254.722,red,93.1104,light green,142.468,light green,169.406,red,115.579
19,Newcastle,95.290106,38,95.513585,117.287731,145.757437,146.671504,131.636680,141.458736,135.853111,...,red,39.9145,red,93.8652,red,51.7611,red,69.1215,red,35.959
20,Crystal Palace,89.983584,38,83.675603,79.008636,80.738482,95.006829,103.455854,94.175775,99.370656,...,red,58.1063,red,107.152,red,96.4142,red,24.8177,red,96.7197

In [ ]:
def templateTable(df):
    template = pd.DataFrame(0, index=range(1,21), columns = df.columns)
    print(len(template))
    #template.columns = df.columns
    for i in range(len(template.columns)):
        if (template.columns[i] == 'Teams')|(template.columns[i] == 'Name'):
            template[template.columns[i]] = ['Team green', 'Team light green', 'Team pink', 'Team red', 'Team white']*4
        elif 'color' in template.columns[i].split():
            template[template.columns[i]] = ['green', 'light green', 'pink', 'red', 'white']*4
        else: template[template.columns[i]] = [1,1,1,1,1]*4
    return template
templateTable(MA(Understat.TeamThreatAd, 7)).to_csv(Path('out/TeamTemplate.csv'))
templateTable(MA(Understat.PlayerThreatAd, 7)).to_csv(Path('out/PlayerTemplate.csv'))
templateTable(MA(Understat.TableTeams, 7)).to_csv(Path('out/TTTemplate.csv'))

20

In [18]:
[1,1,1,1,1]*5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [21]:
a = range(1,21)
a

range(1, 21)

In [30]:
template = pd.DataFrame(0, index=range(1,21), columns = ['1'])
template
a =['Team green', 'Team light green', 'Team pink', 'Team red', 'Team white']*5

In [33]:
print(f'{len(template)}{len(a)}')

2025