In [53]:
''' Fantasy Tables from Different Sources

    Creates class Source which makes tables and htmls from 2 sources: FPL and Understat. Depending on source
    getting data from inputFPL.py or inputUnderstat.py
    
    Sources:    f'{folder}in/Table_'+source+'.csv'
                f'{folder}in/Fixtures.csv'
                f'{folder}in/Teams.csv'
                f'{folder}in/Players.csv'
                f'{folder}in/Team_played_fixtures.csv'
                f'{folder}in/Team_upcoming_fixtures.csv'
                f'{folder}in/Team_opponent_team.csv'
                'in/Player_opponent_team.txt'
                'in/Player_played_fixtures.txt'
                'in/Player_upcoming_fixtures.txt'
                f'{folder}_fixtures.txt'
                f'{folder}_fixtures.txt'
                
                'index.html'
                f'html/{source}/{name}.html'
                f'html/{source}/css/{name}.css'
                name in {Team_xG, Team_xA, Team_Opponent_xG, Team_xG_Ad, Team_xA_Ad, Team_Opponent_xG_Ad,
                Player_xG, PLayer_xA, Player_xG_Ad, Player_xA_Ad}
    
    Write:      f'out/' + source + '/' + name + '.csv')
                f'{folder}mid/{self.source}/Team_oppxG_coeff.txt'
                f'{folder}mid/{self.source}/Team_oppdefence_coeff.txt'
                f'{folder}mid/{self.source}/Player_oppxG_coeff.txt'
                f'{folder}mid/{self.source}/Player_oppdefence_coeff.txt'
                f'{folder}mid/{self.source}/Team_xxG.txt'
                f'{folder}mid/{self.source}/Team_xOxG.txt'
                f'{folder}mid/{self.source}/Player_xxG.txt'
                f'{folder}mid/{source}/{name}.txt'

'''




from time import time
import constti
from Brr_functions import toint, noZ, no_lists, to_lists, del_empty_col
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
import os

class Source:
    def __init__(self, source, ma_num=0, year=''):
        '''
            Initialization function
            source = FPL or Understat
            ma_num = numbers in Moving Average. If 0 then no MA and calculations are faster
            year = '' then current, otherwize year of history "2019-2020" for example
        '''
        self.source = source
        print(f'Start Creating {self.source} Tables:')
        start_module = time()
        start = time()
        self.ma_num = ma_num # Number of matches for the moving average
        
#1. Reading nessesry data from files.
        
        #finding folder with data for year entered
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        
        #Catching empty data at the start of the season. Avoiding mistake with reading empty file
        try:
            Table = pd.read_csv(Path(f'{folder}in/Table_'+source+'.csv')) # Main data from source containing rows for each player
        except:
            print('!!!!!!!!')
            Table = pd.DataFrame()
            self.Table = Table
            return
        if len(Table)<1:
            Table = pd.DataFrame()
            self.Table = Table
            return
    
        #in a game with columns 'element', 'round', 'fixture', 'threat', 'creativity', 'team', opponent_team'
        Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv')) # Table of rows for each fixture
        Teams = pd.read_csv(Path(f'{folder}in/Teams.csv')) # Table of rows as teams with columns 'id', 'Teams',
        #'TARGET COL', 'Matches'
        Players = pd.read_csv(Path(f'{folder}in/Players.csv')) # Table of rows as players with columns 'id', 'Name',
        #'Team', Team games', 'Played'
        del Players['web_name'] #This column is needed only for inputUnderstat.py
        
        
        Team_played_fixtures = pd.read_csv(Path(f'{folder}in/Team_played_fixtures.csv'))
        Team_played_fixtures = to_lists(Team_played_fixtures)
        Team_played_fixtures = Team_played_fixtures[Team_played_fixtures.columns[::-1]]
        
        Team_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Team_upcoming_fixtures.csv'))
        Team_opponent_team = pd.read_csv(Path(f'{folder}in/Team_opponent_team.csv'))
        Team_opponent_team = to_lists(Team_opponent_team)
        Team_opponent_team = Team_opponent_team[Team_opponent_team.columns[::-1]]
        

        #Reading Fxtures and Opponents for Teams and Players
        
        Team_played_fixtures = pd.read_csv(Path(f'{folder}in/Team_played_fixtures.csv'))
        Team_played_fixtures = to_lists(Team_played_fixtures)
        Team_played_fixtures = Team_played_fixtures[Team_played_fixtures.columns[::-1]]
        
        Team_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Team_upcoming_fixtures.csv'))
        Team_opponent_team = pd.read_csv(Path(f'{folder}in/Team_opponent_team.csv'))
        Team_opponent_team = to_lists(Team_opponent_team)
        Team_opponent_team = Team_opponent_team[Team_opponent_team.columns[::-1]]
        
        Player_opponent_team = pd.read_csv(Path(f'{folder}in/Player_opponent_team.csv'))
        Player_opponent_team = to_lists(Player_opponent_team[Player_opponent_team.columns[::-1]])
        
        #file names differ for the present and history
        if year=='':

            Player_played_fixtures = pd.read_csv(Path(f'{folder}in/Player_played_fixtures.csv'))
            #print(Player_played_fixtures.columns)
            Player_played_fixtures = to_lists(Player_played_fixtures[Player_played_fixtures.columns[::-1]])
            Player_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Player_upcoming_fixtures.csv'))
            Player_upcoming_fixtures = to_lists(Player_upcoming_fixtures[Player_upcoming_fixtures.columns[::-1]])
        else:
            with open(Path(f'{folder}in/Team_fixtures.txt'), 'r') as file:
                Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
                Team_played_fixtures = Team_played_fixtures.sort_index()
            with open(Path(f'{folder}in/Player_fixtures.txt'), 'r') as file:
                Player_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Player_played_fixtures.index = pd.to_numeric(Player_played_fixtures.index)
                Player_played_fixtures = Player_played_fixtures.sort_index()
            Team_upcoming_fixtures = pd.DataFrame()
            Player_upcoming_fixtures = pd.DataFrame()
        
        print('\t 1. Reading files from ' + source +' is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

#2. Defenition of useful constants and funtions
        
        #Teams in Premier League
        team_number = len(Teams)

        #Calculating lastGW - last gameweek with at least one game played
        lastGW  = Table['round'].max()

        print('\t 2. Constants and Functions are over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 3. Calculating team tables

        print('\t 3. Calculating team tables')

        #(1). Creating  a table with average threat and GW threats for teams

        Team_xG = Teams.copy()
        Team_xG.columns = ['id', 'Teams', 'xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['threat'].sum())


        Team_xG['xG av'] = [Table[Table['team']==i]['threat'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        Team_xG.sort_values('xG av', ascending = False, inplace = True)
        
        
        def xAxG(col):
            new_col = []
            for i in range(len(col)):
                if np.isnan(col[i]):
                    new_col.append(np.nan)
                else:
                    x = Table[(Table['fixture']==col[i])&(Table['team']==i+1)]['threat']#.sum()
                    if len(x) == 0:
                        new_col.append(np.nan)
                    else:
                        new_col.append(x.sum())
            return new_col
        
        NTeam_xG = no_lists(Team_played_fixtures[Team_played_fixtures.columns[::-1]]).apply(xAxG)
#         NTeam_xG = no_lists(Team_played_fixtures[Team_played_fixtures.columns[::-1]]).apply(lambda x: \
#         np.nan if np.isnan(x[i]) else\
#         [Table[(Table['fixture']==x[i])&(Table['team']==i+1)]['threat'].sum() for i in Team_played_fixtures.index])
        X = Teams.copy()
        X.columns = ['id', 'Teams', 'xG av', 'Matches']
        X['xG av'] = NTeam_xG.mean(axis=1)
        NTeam_xG = to_lists(NTeam_xG[NTeam_xG.columns[::-1]])
        X[NTeam_xG.columns] = NTeam_xG.copy()
        NTeam_xG = X.copy()
        NTeam_xG.sort_values('xG av', ascending = False, inplace = True)
        #NTeam_xG = del_empty_col(NTeam_xG)
        self.NTeam_xG = NTeam_xG
        
        print('\t\t 3.1. Team_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2). Creating  a table with average creativity and GW creativities for teams

        Team_xA = Teams.copy()
        Team_xA.columns = ['id', 'Teams', 'xA av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xA['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                    Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['creativity'].sum())


        Team_xA['xA av'] = [Table[Table['team']==i]['creativity'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        
        print('\t\t 3.2. Team_xA is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()
        
        #(3). Creating  a table with average threat allowed by teams and GW threat allowed

        Team_Opponent_xG = Teams.copy()
        Team_Opponent_xG.columns = ['id', 'Teams', 'Opponent xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_Opponent_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_Opponent_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']== \
                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['opponent_team']==i+1)]['threat'].sum())


        Team_Opponent_xG['Opponent xG av'] = [Table[Table['opponent_team']==i]['threat'].sum()
                        for i in range(1,team_number+1)]/noZ(Teams['Matches'])

        threatAllowedAv = Team_Opponent_xG['Opponent xG av'].mean()
        
        print('\t\t 3.3. Team_Opponent_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        class_data = [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team,\
        Player_opponent_team, Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\

        #(4). Creating  a table with average adjusted threat and GW threats adj for teams

        Team_xG_Ad = adjustment(Team_xG, class_data)       
        print('\t\t 3.4. Team_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(5). Creating  a table with average adjusted creativity and GW creativities adj for teams
        
        Team_xA_Ad = adjustment(Team_xA, class_data)
        print('\t\t 3.5. Team_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(6). Creating  a table with average threat allowed adjusted by teams and GW threat allowed adjusted

        Team_Opponent_xG_Ad = adjustment(Team_Opponent_xG, class_data)
        print('\t\t 3.6. Team_Opponent_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()


        #(7) Total Team Table

        TableTeams = pd.DataFrame()
        TableTeams['id'] = Teams['id']
        TableTeams['Team'] = Teams['Teams']

        TableTeams['xG adjusted'] = Team_xG_Ad['xG av adj']
        TableTeams['xG'] = Team_xG['xG av']
        TableTeams['xA adjusted'] = Team_xA_Ad['xA av adj']
        TableTeams['xA'] = Team_xA['xA av']
        TableTeams['Opponent xG adjusted'] = Team_Opponent_xG_Ad['Opponent xG av adj']
        TableTeams['Opponent xG'] = Team_Opponent_xG['Opponent xG av']
        
        print('\t\t 3.7. TableTeams is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 4. Calculating pLayer tables
        
        print('\t 4. Calculating player tables')

        #(1) Players Threat

        Player_xG = Players.copy()
        #Player_xG['xG per fixture'] = np.zeros(len(Players))
        #Player_xG['xG per game'] = np.zeros(len(Players))
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per fixture',\
        [0.0 for i in Player_xG.itertuples()])
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per game',\
        [0.0 for i in Player_xG.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xG['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                        Player_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['element']==\
                        Player_xG.at[i,'id'])]['threat'].sum())
                    Player_xG.at[i,'xG per game'] = Player_xG.at[i,'xG per game'] +\
                        Player_xG.at[i,'GW'+str(j)][k]


        Player_xG['xG per fixture'] = Player_xG['xG per game']/noZ(Players['Team games'])
        Player_xG['xG per game'] = Player_xG['xG per game']/noZ(Players['Played'])
        
        print('\t\t 4.1. Player_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Players Creativity

        Player_xA = Players.copy()
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per fixture',\
        [0.0 for i in Player_xA.itertuples()])
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per game',\
        [0.0 for i in Player_xA.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xA['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                                Player_played_fixtures.at[i, 'GW'+str(j)][k])&\
                                                (Table['element']==Player_xA.at[i,'id'])]['creativity'].sum())
                    Player_xA.at[i,'xA per game'] = Player_xA.at[i,'xA per game'] +\
                        Player_xA.at[i,'GW'+str(j)][k]


        Player_xA['xA per fixture'] = Player_xA['xA per game']/noZ(Players['Team games'])
        Player_xA['xA per game'] = Player_xA['xA per game']/noZ(Players['Played'])
        
        print('\t\t 4.2. Player_xA is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(3) Players Threat Adjusted
        
        Player_xG_Ad = adjustment(Player_xG, class_data)
        print('\t\t 4.3. Player_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        #(4) PLayers Creativity Adjusted
        
        Player_xA_Ad = adjustment(Player_xA, class_data)    
        print('\t\t 4.4. Player_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
# 5. Creating future tables and opponent tables

        #(1) Calculating futures
        print('\t 5. Creating future tables and opponent tables.')

        Team_oppxG_coeff = no_lists(Team_opponent_team)
        Team_oppdefence_coeff = no_lists(Team_opponent_team)
        Player_oppxG_coeff = no_lists(Player_opponent_team)
        Player_oppdefence_coeff = no_lists(Player_opponent_team)
        
        #Columns with np.nan automatically become float that's why int() is needed
        Team_oppxG_coeff = Team_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[int(x)-1,'xG av adj'] \
        if not np.isnan(x) else np.nan)/threatAllowedAv

        Team_oppdefence_coeff = Team_oppdefence_coeff.applymap(lambda x: \
        Team_Opponent_xG_Ad.at[int(x)-1,'Opponent xG av adj'] if not np.isnan(x) else np.nan)/threatAllowedAv

        Player_oppxG_coeff = Player_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[int(x)-1,'xG av adj'] \
        if not np.isnan(x) else np.nan)/threatAllowedAv

        Player_oppdefence_coeff = Player_oppdefence_coeff.applymap(lambda x: \
        Team_Opponent_xG_Ad.at[int(x)-1,'Opponent xG av adj'] if not np.isnan(x) else np.nan)/threatAllowedAv

        Team_xxG = Team_oppdefence_coeff.mul(Team_xG_Ad['xG av adj'], axis=0)
        Team_xOxG = Team_oppxG_coeff.mul(Team_Opponent_xG_Ad['Opponent xG av adj'], axis=0)
        Player_xxG = Player_oppdefence_coeff.mul(Player_xG_Ad['xG per game adj'], axis=0)
        
        #Writing pure numbers(lists of numbers) tables to mid folder for stats calculations
        Team_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppxG_coeff.txt'))
        Team_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppdefence_coeff.txt'))
        Player_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppxG_coeff.txt'))
        Player_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppdefence_coeff.txt'))
        Team_xxG.to_json(Path(f'{folder}mid/{self.source}/Team_xxG.txt'))
        Team_xOxG.to_json(Path(f'{folder}mid/{self.source}/Team_xOxG.txt'))
        Player_xxG.to_json(Path(f'{folder}mid/{self.source}/Player_xxG.txt'))
        
        print('\t\t 5.1. Calculating futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Visualizing futures
        
        #Adding some words for tables to be readable (lists still)
        Display_Team_xxG = Team_xxG.copy()
        Display_Team_xxG['sum'] = Display_Team_xxG.sum(axis=1)
        Display_Team_xxG['Teams'] =  Teams['Teams']
        Display_Team_xxG = Display_Team_xxG[Display_Team_xxG.columns[::-1]].sort_values('sum', ascending=False)
        del Display_Team_xxG['sum']
        for i in range(1,lastGW+1):
            del Display_Team_xxG[f'GW{i}']
        Display_Team_xxG

        Display_Player_xxG = Player_xxG.copy()
        Display_Player_xxG['sum'] = Display_Player_xxG.sum(axis=1)
        Display_Player_xxG['name'] =  Players['Name']
        Display_Player_xxG = Display_Player_xxG[Display_Player_xxG.columns[::-1]].sort_values('sum', ascending=False)
        del Display_Player_xxG['sum']
        for i in range(1,lastGW+1):
            del Display_Player_xxG[f'GW{i}']
        Display_Player_xxG

        Display_Team_xOxG = Team_xOxG.copy()
        Display_Team_xOxG['sum'] = Display_Team_xOxG.sum(axis=1)
        Display_Team_xOxG['Teams'] = Teams['Teams']
        Display_Team_xOxG = Display_Team_xOxG[Display_Team_xOxG.columns[::-1]].sort_values('sum', ascending=True)
        del Display_Team_xOxG['sum']
        for i in range(1,lastGW+1):
            del Display_Team_xOxG[f'GW{i}']
        Display_Team_xOxG
        
        print('\t\t 5.2. Visualizing futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
# 6. Writing tables to files (and variables to class.variables)
        
        # Useful variables for debugging
        self.Table = Table
        self.Fixtures = Fixtures
        self.Teams = Teams
        self.Players = Players
        self.lastGW = lastGW
        
        self.threatAllowedAv = threatAllowedAv
        self.Team_played_fixtures = Team_played_fixtures
        self.Team_opponent_team = Team_opponent_team
        self.Player_played_fixtures = Player_played_fixtures
        self.Player_opponent_team = Player_opponent_team
        
        #Save before modifying while writing into files
        self.TxG = Team_xG.copy()
        self.TxA = Team_xA.copy()
        self.TOxG = Team_Opponent_xG.copy()
        self.TxGA = Team_xG_Ad.copy()
        self.TxAA = Team_xA_Ad.copy()
        self.TOxGA = Team_Opponent_xG_Ad.copy()
        self.TaTe = TableTeams.copy() 
        self.PxG = Player_xG.copy()
        self.PxA = Player_xA.copy()
        self.PxGA = Player_xG_Ad.copy()
        self.PxAA = Player_xA_Ad.copy()
        
        self.Team_xG =\
            write_table(Team_xG, 'Team_xG', 'xG av', self.source, self.ma_num, folder)
        self.Team_xA = (write_table
            (Team_xA, 'Team_xA', 'xA av', self.source, self.ma_num, folder))
        self.Team_Opponent_xG =\
            write_table(Team_Opponent_xG, 'Team_Opponent_xG', 'Opponent xG av', self.source, self.ma_num, folder)
        self.Team_xG_Ad =\
            write_table(Team_xG_Ad, 'Team_xG_Ad', 'xG av adj', self.source, self.ma_num, folder)
        self.Team_xA_Ad =\
            write_table(Team_xA_Ad, 'Team_xA_Ad', 'xA av adj', self.source, self.ma_num, folder)
        self.Team_Opponent_xG_Ad =\
            write_table(Team_Opponent_xG_Ad, 'Team_Opponent_xG_Ad', 'Opponent xG av adj', self.source, self.ma_num, folder)
        self.TableTeams =\
            write_table(TableTeams, 'TableTeams', 'xG adjusted', self.source, self.ma_num, folder)
        
        self.Player_xG =\
            write_table(Player_xG, 'Player_xG', 'xG per fixture', self.source, self.ma_num, folder)
        self.Player_xA =\
            write_table(Player_xA, 'Player_xA', 'xA per fixture', self.source, self.ma_num, folder)
        self.Player_xG_Ad =\
            write_table(Player_xG_Ad, 'Player_xG_Ad', 'xG per fixture adj', self.source, self.ma_num, folder)
        self.Player_xA_Ad =\
            write_table(Player_xA_Ad, 'Player_xA_Ad', 'xA per fixture adj', self.source, self.ma_num, folder)
        
        print('\t 6. Writing to files is over.\t It takes ' + str(time() - start) + ' sec')
        print(f'{self.source} is created./t It takes {time() - start_module} sec')
        start = time()

# 7. Tests for each element of the class
    
    def test2FPL(self, folder=''):
        '''
            Checks if all names in the source can be found in fantasy.premierleague.com (FPL)
            Subfunction of test()
        '''
        FPL = pd.read_csv(f'{folder}in/Table_FPL.csv')
        Table_Source = pd.read_csv(f'{folder}in/Table_'+self.source+'.csv')
        Mistakes = pd.DataFrame()
        No_Names = pd.DataFrame()
        if self.source == 'FPL':
            return Mistakes, No_Names
        for i in Table_Source.index:
            if Table_Source.at[i,'element'] < 1000000:
                FPLmin = FPL[(FPL['element'] == Table_Source.at[i,'element'])&\
                            (FPL['fixture'] == Table_Source.at[i,'fixture'])]['minutes'].sum()
                if abs(Table_Source.at[i,'minutes'] - FPLmin) > 10:
                    Mistakes = Mistakes.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'element'],\
                        Table_Source.at[i,'fixture'], Table_Source.at[i,'minutes'], FPLmin]], columns = ['player',\
                        'element', 'fixture', 'minutes', 'FPL_minutes']), ignore_index=True)
            else:
                No_Names = No_Names.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'team_name'], Table_Source.at[i,'fixture']]],\
                                                         columns = ['player', 'team_name', 'fixture']), ignore_index=True)
                #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        display(Mistakes)
        display(No_Names)
        return Mistakes, No_Names
        
    def test(self, year=''):
        '''
            Tests that all tables are correct (no duplicated columns or rows)
            Uses test2FPL() to compare names
        '''
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        if self.Table.empty:
            print(f'Nothing to test. {self.source} table is empty.')
            return
        start = time()
        
        constti.DRDC(self.Team_xG)
        constti.DRDC(self.Team_xA)
        constti.DRDC(self.Team_Opponent_xG)
        constti.DRDC(self.Team_xG_Ad)
        constti.DRDC(self.Team_xA_Ad)
        constti.DRDC(self.Team_Opponent_xG_Ad)
        constti.DRDC(self.TableTeams)
        constti.DRDC(self.Player_xG)
        constti.DRDC(self.Player_xA)
        constti.DRDC(self.Player_xG_Ad)
        constti.DRDC(self.Player_xA_Ad)
        
        self.test2FPL(folder='')
        
        print(f'\t {self.source} Testing is over.\t It takes {time() - start} sec\n\n')

# 7. Useful not class functions

def html_table_name(table_name):
    '''
    Converts the name of the table into the name of the Tale in html file
    '''
    return table_name.replace('Team_', 'Teams Ranking Based on Team ').replace('Player_', 'Players Ranking Based on Player ')\
    .replace('Ad', 'Adjusted').replace('_', ' ').replace('TableTeams', 'Teams Ranking')



def write_table(df, name, key_col, source, ma_num, folder):
    '''
        Writing final tables to files and returning table itself and MA variant also
        df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
        source - Understat or FPL, ma_num - number for MA(currently unused just calculated)
    '''
    
    #print(f'folder = {folder}')
    df.to_json(Path(f'{folder}mid/{source}/{name}.txt')) #writing table to "mid" folder for advanced calculations
    def table2string(table):
        '''
        Converts table to view suitable for html. All number columns are actually strings with 1 digit after .
        '''
        df = table.copy()
        for j in df.columns:
            if ('GW' in j)|(' av' in j)|('xG' in j)|('xA' in j):
                df[j] = [str(int(df.at[i,j]*10)/10) if not np.isnan(df.at[i,j]) else '' for i in df.index]

        return df
    
    #Removes redundant columns
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    
    # Sort decreasing for attack an increasing for defence
    if 'Opponent' in name:
        df.sort_values(key_col, ascending = True, inplace = True)
    else:
        df.sort_values(key_col, ascending = False, inplace = True)
    
    # Removes lists in celss which are needed for double gameweeks
    df.index = np.arange(1, len(df) + 1)
    df = no_lists(df)
    
    # If moving average number is 0 no calculation needed. Use it to fasten the debug!
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    
    #Writes result to file
    df.to_csv(Path(f'{folder}out/' + source + '/' + name + '.csv'))
    
    
    # Add table created as table of stringe to existing html file replacing table tag with a new one
    #Also adding a new css
    if folder == '':
        dfString = table2string(df)
        
        dfStringStyler = dfString.style.apply(color_table, axis=None)#.render().replace('\n', '')#.format(digit_dict)
        dfStringStyler.set_table_attributes('class="DataTable"')
        html_table = dfStringStyler.render().replace('\n', '')
        BS_table = BeautifulSoup(html_table, 'html.parser')
        css = str(BS_table('style')[0])
        html_ = str(BS_table('table')[0])

        #Getting right paths for different tables
        if source=='FPL' and name=='TableTeams':
            html_path = Path(f'{folder}index.html')
            css_path = Path(f'{folder}html/FPL/css/TableTeams.css')
        else:
            html_path = Path(f'{folder}html/{source}/{name}.html')
            css_path = Path(f'{folder}html/{source}/css/{name}.css')

        #Making css for coloring butons

        css = ('#' + source + '-button {\n background-color: #82f5cf;\n}\n' +
               '#' + name + ' {\n background-color: lightgrey;\n}\n' + 
               css)

        #Rewriting html and css
        with open(f'{folder}index.html', 'r', encoding="utf-8") as file:
            old_file = file.read()
        tag_to_replace1 = str(BeautifulSoup(old_file, 'html.parser')('table', attrs={"class":"DataTable"})[0])
        tag_to_replace2 = str(BeautifulSoup(old_file, 'html.parser')('h2', attrs={"id":"DataTitle"})[0])
        new_file = old_file.replace(tag_to_replace1, html_)
        new_file = new_file.replace(tag_to_replace2, f'<h2 id="DataTitle"> {html_table_name(name)} </h2>')

        #Making links right

        if not(source=='FPL' and name=='TableTeams'):
            new_file = new_file.replace('html/FPL/', '')
            new_file = new_file.replace('"out/FPL/TableTeams.csv"', f'"../../out/{source}/{name}.csv"')#Change download button
            new_file = new_file.replace(f'TableTeams', name)
            if name != 'TableTeams': #changes links for buttons FPL and Understat
                new_file = new_file.replace('class="header-form" action="index.html"',\
                f'class="header-form" action="../FPL/{name}.html"')
            else:
                new_file = new_file.replace('form action="index.html"', f'form action="../../index.html"')
            new_file = new_file.replace('html/', '../')
            new_file = new_file.replace('"index.html"', '"../../index.html"')

        #Creating .html and special files for the Table
        with open(html_path, 'w', encoding="utf-8") as file:
            file.write(new_file)
        with open(css_path, 'w', encoding="utf-8") as file:
            file.write(css)
    
    return df

def color_table(df):
    '''
        Makes colored tables
    '''
    def table_type(df):
        if df.columns[2]=='xG': return 'TableTeams'
        elif 'Opponent' in df.columns[1]: return 'Defence'
        elif df.columns[0]=='Teams': return 'Team'
        else: return 'Player'
    def color_Team_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Player_xG(val):
        if val=='': color = 'white'
        elif float(val)>50: color = '#09bb9f'
        elif float(val)>25: color = '#82f5cf'
        elif float(val)>10: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Defence(val):
        if val=='': color = 'white'
        elif float(val)<120: color = '#09bb9f'
        elif float(val)<150: color = '#82f5cf'
        elif float(val)<180: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    
    def color_table_row(row, x):
        '''
            function for style.apply by rows where x is a table type
            Subfunction of color_table_row
        '''
        if x=='Team':
            return [color_Team_xG(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='Player':
            return [color_Player_xG(i) if not (row.name  in ['Team games', 'Played', 'Name', 'Team'])\
                    else 'Background-color: white' for i in row]
        elif x=='Defence':
            return [color_Defence(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='TableTeams':
            return [color_Team_xG(i) if row.name in ['xG adjusted', 'xG', 'xA', 'xA adjusted']\
                   else 'Background-color: white' if row.name in ['Team'] else color_Defence(i) for i in row]
        
    return df.apply(color_table_row, x=table_type(df), axis=0)


# Returns the table with d mean average for table Out_T
# If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
def MA(Out_T, d):
    '''
        Returns the table with d mean average for table Out_T.
        If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
        Filling the column with averages. Subfunction for MA.
        Adds d - averages for j-th GW_column (not GWj but j-th in order) of table T.
    '''
    def d_av(T, j, GW_columns, d):
        T.insert(T.columns.get_loc(GW_columns[-1]), f'{GW_columns[j]} {str(d)} - average', [0.0 for i in T.itertuples()])
        for i in T.index:
            u = 0
            k = 0
            while (u < d)&(j-k>=0):
                if not np.isnan(T.at[i, GW_columns[j-k]]):#!!!'':
                    T.at[i, f'{GW_columns[j]} {str(d)} - average'] += T.at[i, GW_columns[j-k]]
                    u+=1
                    k+=1
                else: k+=1
            if u==d:
                T.at[i, f'{GW_columns[j]} {str(d)} - average'] = T.at[i, f'{GW_columns[j]} {str(d)} - average']/d
            else:
                T.loc[i, f'{GW_columns[j]} {str(d)} - average'] = ''
        return None
    
    T = Out_T.copy()
    
    #Creating the list of GW_columns for the table T
    GW_columns = []
    gw_col=0
        
    for col in T.columns:
        if 'GW' in col:
            GW_columns.append(col)
            gw_col+=1
    GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)] #makes the opposite order of the list
    
    #returning colored MA table if it is TableTeams
    if GW_columns == []: return T
    
    #Add averages for GW_columns using d_av function defined above returning colored MA table if it is not TableTeams
    # Add MA columns only id d not larger than GW played
    if d<=gw_col:
        for j in range(gw_col-1, d-2, -1):
            d_av(T, j, GW_columns, d)

    return T
    
    
######################################For Debugging
# lastGW = 43
# team_number = 20
# Fixtures = Understat.Fixtures
# Table = Understat.Table
# Players = Understat.Players
# Teams = Understat.Teams
# threatAllowedAv = Understat.threatAllowedAv
# Team_Opponent_xG = Understat.TD
# Team_played_fixtures = Understat.Team_played_fixtures
# Team_opponent_team = Understat.Team_opponent_team
# Player_opponent_team = Understat.Player_opponent_team
# Player_played_fixtures = Understat.Player_played_fixtures
# TeamThreat = Understat.TT
# Player_xA = Understat.PC






def adjustment(df, class_data):
    '''
        Creating adjusted tables from unadjusted
        df - table to transform
        class_data - list of needed data from source class
    '''
    [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team, Player_opponent_team,\
     Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\
    = class_data
    if len(df)==len(Teams):
        dfAd = Teams.copy()
        for i in df.columns:
            if ' av' in i:
                key_par = i[:-3]
        av  = 'av'
        dfAd.columns = ['id', 'Teams', f'{key_par} av adj', 'Matches']
        the_fixtures = Team_played_fixtures
        the_opponent_team = Team_opponent_team
    else:
        dfAd = Players.copy()
        for i in df.columns:
            if 'per fixture' in i:
                key_par = i[:-12]
        av = 'per game'
        
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per fixture adj',\
        [0.0 for i in dfAd.itertuples()])
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per game adj',\
        [0.0 for i in dfAd.itertuples()])
        
        
        the_fixtures = Player_played_fixtures
        the_opponent_team = Player_opponent_team
        
    if 'Opponent' in key_par:#key_par[-7:] == 'allowed':
        Weighting_table = Team_xG
        col = 'xG av'
    else:
        Weighting_table = Team_Opponent_xG
        col = 'Opponent xG av'
        
    for j in range(lastGW,0,-1):
        dfAd[f'GW{j}'] = [[] for _ in range(len(df))]
        for i in range(len(df)):
             for k in range(len(the_fixtures.at[i, 'GW'+str(j)])):
                dfAd.at[i,f'GW{j}'].append(df.at[i,f'GW{j}'][k]\
                *threatAllowedAv/ Weighting_table.at[int(the_opponent_team.at[i,f'GW{j}'][k])-1, col])

                dfAd.at[i,f'{key_par} {av} adj'] += dfAd.at[i,f'GW{j}'][k]

    
    if len(df) == len(Teams): dfAd[f'{key_par} av adj'] = dfAd[f'{key_par} av adj']/noZ(dfAd['Matches'])
    else:
        dfAd[f'{key_par} per fixture adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Team games'])
        dfAd[f'{key_par} per game adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Played'])
    
    
    return dfAd

        
if __name__ == '__main__':
    year = ''
    Understat = Source('Understat', ma_num=7, year=year)
    Understat.test(year)
    FPL = Source('FPL', ma_num=7, year=year)
    FPL.test(year)
    #display(MA(Understat.TeamThreatAd, 8))
    pass

Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 0.27884554862976074 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 1.0289607048034668 sec
		 3.2. Team_xA is over.	 It takes 0.447756290435791 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.46573305130004883 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.023825645446777344 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.022986888885498047 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.022986888885498047 sec
		 3.7. TableTeams is over.	 It takes 0.003997802734375 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 12.589820146560669 sec
		 4.2. Player_xA is over.	 It takes 12.759743213653564 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.43059611320495605 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.42073655128479004 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.4691708087921143 sec
		 5.2. Visualizing futures.	 It takes 0.018980026245117188 sec
	 6. Writing to files is over.	 It takes 29.681629180908203 sec
Understat is created./t It takes 59.667752504348755 sec

                       player  element  fixture  minutes  FPL_minutes
0      Daniel Castelo Podence    469.0       89       80           69
1                 Fabio Silva    504.0       89       74           63
2  David Luiz Moreira Marinho      3.0       89       56           45
3     Willian Borges Da Silva    478.0       89       75           64
4                 Rob Holding     16.0       89       34           45

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 6.235801935195923 sec


Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.29784131050109863 sec
	 2. Constants and Functions are over.	 It takes 0.0 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.9864449501037598 sec
		 3.2. Team_xA is over.	 It takes 0.4987063407897949 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.45973730087280273 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.023346900939941406 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.021987438201904297 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.02298712730407715 sec
		 3.7. TableTeams is over.	 It takes 0.00299835205078125 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 13.376415491104126 sec
		 4.2. Player_xA is over.	 It takes 14.827554941177368 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.4877355098724365 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.5956566333770752 sec
	 5. Creating future tables and opponent tables.
		 5.1. Calculating futures.	 It takes 1.6960747241973877 sec
		 5.2. Visualizing futures.	 It takes 0.020969867706298828 sec
	 6. Writing to files is over.	 It takes 33.09080481529236 sec
FPL is created./t It takes 66.41325449943542 sec
	 FPL Testing is over.	 It takes 0.24985790252685547 sec

In [59]:
def del_empty_col(df):
    '''
        Deleting empty columns
    '''
    for i in df.columns:
        try:
            print(df[i].tolist()==[[] for _ in df.index])
            #print([np.isnan(df[i].tolist()[j]) for j in range(len(df))]==[True for _ in df.index])
            if (df[i].tolist()==[[] for _ in df.index])|\
            ([np.isnan(df[i].tolist()[j]) for j in range(len(df))]==[True for _ in df.index]):
                 del df[i]
        except:
            pass
    return df

Understat.NTeam_xG
#Understat.NTeam_xG.sort_values('xG av', ascending = False, inplace = True)
# to_lists(Understat.NTeam_xG)
#constti.differences(Understat.NTeam_xG)
#Understat.TxG
del_empty_col(Understat.NTeam_xG.copy()[Understat.NTeam_xG.columns[4:]])
#Understat.NTeam_xG

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  # Remove the CWD from sys.path while we load stuff.

,GW19,GW18,GW17,GW16,GW15,GW14,GW13,GW12,GW11,GW10,GW9,GW8,GW7,GW6,GW5,GW4,GW3,GW2,GW1
11,"[96.79450504481792, 371.3787071406841]",[290.8545162528753],[325.3768779337406],[],[319.57530342042446],[115.59934392571449],[259.7260751761496],[130.95164187252522],[328.96083258092403],[226.12867997959256],[167.86035625264049],[158.48749428987503],[189.64285058900714],[89.24563145264983],[154.09909896552563],[141.53252635151148],[144.63312169536948],[207.65146650373936],[]
10,"[120.52912916988133, 165.27214590460062]",[],[137.76925597339869],[132.0468726567924],[145.4847937449813],[287.40522004663944],[121.7832013964653],[182.44472481310368],[159.45401303470135],[28.109000995755196],[421.9125308096409],[119.03676185756922],[156.30165580660105],[265.53993951529264],[252.76610162109137],[165.70484042167664],[280.37091232836246],[230.21926041692495],[316.3538724184036]
1,[60.326309502124786],[],[156.43410831689835],[73.08590356260538],[516.599577665329],[261.96378050372005],[181.50254599750042],[126.87208130955695],[],[239.05069082975388],[194.39844377338886],[198.5531985759735],[244.85467234626412],[154.10015136003494],[87.37762244418263],[311.69424820691347],[203.22180166840553],[80.52702955901623],[]
4,"[137.93921619653705, 61.57274320721626]",[],[69.10128202289343],[153.70097197592258],[225.4138793796301],[268.1783507578075],[156.77166134119034],[100.62671974301338],[500.9606434032321],[97.475516051054],[181.92277494817972],[288.75890858471394],[123.07725325226784],[21.990608517080545],[198.7078694626689],[251.4334158971906],[239.28571022115648],[90.41826473549007],[127.06250268965957]
12,"[118.92911978065969, 168.40144861489534]",[123.99645596742629],[246.52127008885145],[181.6049262881279],[208.42320397496223],[480.7996444404125],[178.6669815890491],[59.161681309342384],[178.70782539248466],[250.66684614866972],[243.1038973852992],[159.76239889860153],[39.41134847700596],[64.84272675588727],[221.72902077436447],[87.34353706240653],[157.58275259286162],[110.13481756672263],[]
9,[24.51931033283472],[],[115.62610194087029],[154.22512581571937],[213.27089108526707],[163.46667129546404],[298.4804593026638],[156.64448086172342],[102.99920700490475],[344.6602525189519],[197.70850539207458],[84.79131739586592],[177.30648610740903],[238.46892900764942],[108.33213608711958],[256.6618546843529],[146.64131421595812],[145.7077842205763],[26.981324329972267]
16,[128.38470079004765],[315.7573448494077],[252.86047533154488],[],[40.81089440733194],[98.9194430410862],[151.6101099550724],[141.93513877689838],[39.06285185366869],[22.6889718323946],[76.11420564353466],[189.1799807548523],[197.23618663847444],[81.43992014229298],[177.6020236313343],[330.17044477164745],[332.7577270567417],[234.4843193888664],[82.29440376162529]
8,"[212.01937198638916, 114.49014656245708]",[],[70.20810879766941],[172.13209820911288],[103.95984873175621],[174.92179684340954],[83.88299541547894],[164.35141172260046],[142.89673753082752],[132.70611725747585],[198.39726574718952],[205.45035004615784],[312.6464493572712],[73.61716106534004],[67.15950481593609],[45.6021586433053],[286.7210805416107],[98.73648025095463],[298.582948371768]
6,[],[32.344476878643036],[37.1044859290123],[],[56.88030440360308],[66.6564779356122],[221.93985879421234],[122.15970251709223],[228.1387731432915],[129.22898521646857],[225.07994174957275],[37.64638304710388],[121.80457208305599],[28.705432824790474],[135.99792970344424],[234.1650126501918],[227.18924637883902],[427.61159744113684],[126.7927606590092]
2,[114.42360412329437],[17.708406317979097],[244.7467127814889],[79.93676848709583],[150.80992244184017],[293.3006638661027],[47.167502995580435],[79.16734861209989],[203.37576214224103],[230.72186615318057],[151.98765397071838],[159.21809915453196],[32.44568910449743],[54.68069119378925],[109.35028679668903],[120.3390771523118],[297.78816401958466],[187.65969965606928],[144.36947777867317]
18,"[173.39721359312534, 217.51151010394096]",[],[125.02764090895653],[107.24631957709789],[138.8772202655673],[27.773665264248848],[44.94691081345081],[178.50954681634903],[258.58464865013957],[57.16326981782913],[211.69899981468916],[143.74188743531704],[26.90475694835186],[26.407769601792097],[158.27867593616247],[203.22747360914946],[309.8528914153576],[206.46867286413908],[87.77559446170926]
0,[233.04236913099885],[36.96127291768789],[416.7563149705529],[131.5365655347705],[195.27494348585606],[125.20630396902561],[66.11350364983082],[185.36249361932278],[59.521557204425335],[111.8501327931881],[71.07782764360309],[139.03699815273285],[99.80722852051258],[74.66747350990772],[83.83222110569477],[66.71310849487782],[117.8171444684267],[132.90194496512413],[271.98892682790756]
7,"[46.30896206945181, 75.36693532019854]",[105.32936863601208],[],[],[78.18546602502465],[110.64502373337746],[100.44803842902184],[175.56021213531494],[28.74437882564962],[203.71896382421255],[187.02811691910028],[185.04844093695283],[163.01824264228347],[107.47905820608139],[135.61140075325966],[96.93931266665459],[53.53976786136627],[155.5031105875969],[12.632650975137949]
19,[194.35786586254835],[85.24946169927716],[181.85610407963395],[41.10464304685593],[74.2598220705986],[145.72241976857185],[68.37827861309052],[114.01655972003938],[35.775332152843475],[231.5020002424717],[162.75758631527424],[57.936041243374355],[134.89451464265585],[76.26251354813576],[61.81912124156952],[91.01026672869921],[38.515184074640274],[72.7677259594202],[161.30684465169907]
14,[97.81329520046711],[202.91177965700626],[32.315776124596596],[49.257842637598515],[125.10570902377368],[103.71268633753061],[123.52503687143326],[21.91147208213806],[29.0742902085185],[365.93613401055336],[69.5481725037098],[77.30905171483755],[68.75436678528786],[139.7875364869833],[166.36329758912325],[14.499417319893837],[153.27766481786966],[84.97092444449662],[95.07563784718513]
5,[5.158357694745065],[71.73833269625902],[59.888806752860546],[32.13476538658142],[84.90859707817435],[48.931847279891365],[109.1079043224454],[184.44324098527431],[168.8583116978407],[53.48931476473808],[128.33077777177095],[130.1691273227334],[80.27672208845615],[286.7823727428913],[76.11688375473021],[10.324854403734207],[44.311497174203396],[191.45617708563805],[139.56860154867172]
15,[38.10025919228792],[],[50.04363898187876],[67.09958147257566],[11.970867402851582],[58.697166573256254],[111.29566077142954],[228.42298243194818],[134.80080841109157],[49.87832400947809],[107.85045959055425],[98.58283773064613],[100.33299773931503],[74.15100820362568],[142.38150101155043],[94.90786418318748],[70.66316157579422],[235.03156080842018],[126.26736983656883]
13,[16.879622545093298],[104.74466104060413],[26.458394527435303],[81.7934850230813],[20.09532544761896],[126.72527134418488],[147.59241435676813],[90.41625121608377],[],[127.92897466570139],[36.82859092950821],[17.563267424702644],[263.10976557433605],[25.368521735072136],[86.74957752227783],[195.62900941818955],[94.27263196557759],[52.067840937525034],[165.91140814125538]
3,"[39.56677699461579, 108.05874913930893]",[64.85817553475499],[],[97.38306477665901],[154.59070494398475],[120.46544561162594],[31.673698127269745],[82.21506718546152],[73.04341420531273],[41.987717524170876],[175.3429390490055],[32.69328661262989],[40.73412399739026],[95.04502303898335],[112.14596815407275],[43.88487059623003],[34.71356853842735],[152.40391455590725],[]
17,"[248.29895943403247, 46.409052796661854]",[],[86.98735684156418],[43.55102889239788],[73.98447021842003],[3.884424641728401],[21.0243153385818],[57.31896869838238],[56.723370403051376],[172.3855871707201],[43.864610977470875],[80.05156237632036],[48.26849661767483],[29.56538423895836],[78.99831160902977],[16.24864973127842],[91.11851248890162],[31.53465948998928],[35.29965505003929]

In [ ]:
''' Fantasy Tables from Different Sources

    Creates class Source which makes tables and htmls from 2 sources: FPL and Understat. Depending on source
    getting data from inputFPL.py or inputUnderstat.py
    
    Sources:    f'{folder}in/Table_'+source+'.csv'
                f'{folder}in/Fixtures.csv'
                f'{folder}in/Teams.csv'
                f'{folder}in/Players.csv'
                f'{folder}in/Team_played_fixtures.csv'
                f'{folder}in/Team_upcoming_fixtures.csv'
                f'{folder}in/Team_opponent_team.csv'
                'in/Player_opponent_team.txt'
                'in/Player_played_fixtures.txt'
                'in/Player_upcoming_fixtures.txt'
                f'{folder}_fixtures.txt'
                f'{folder}_fixtures.txt'
                
                'index.html'
                f'html/{source}/{name}.html'
                f'html/{source}/css/{name}.css'
                name in {Team_xG, Team_xA, Team_Opponent_xG, Team_xG_Ad, Team_xA_Ad, Team_Opponent_xG_Ad,
                Player_xG, PLayer_xA, Player_xG_Ad, Player_xA_Ad}
    
    Write:      f'out/' + source + '/' + name + '.csv')
                f'{folder}mid/{self.source}/Team_oppxG_coeff.txt'
                f'{folder}mid/{self.source}/Team_oppdefence_coeff.txt'
                f'{folder}mid/{self.source}/Player_oppxG_coeff.txt'
                f'{folder}mid/{self.source}/Player_oppdefence_coeff.txt'
                f'{folder}mid/{self.source}/Team_xxG.txt'
                f'{folder}mid/{self.source}/Team_xOxG.txt'
                f'{folder}mid/{self.source}/Player_xxG.txt'
                f'{folder}mid/{source}/{name}.txt'

'''




from time import time
import constti
from Brr_functions import toint, noZ, no_lists, to_lists
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
import os

class Source:
    def __init__(self, source, ma_num=0, year=''):
        '''
            Initialization function
            source = FPL or Understat
            ma_num = numbers in Moving Average. If 0 then no MA and calculations are faster
            year = '' then current, otherwize year of history "2019-2020" for example
        '''
        self.source = source
        print(f'Start Creating {self.source} Tables:')
        start_module = time()
        start = time()
        self.ma_num = ma_num # Number of matches for the moving average
        
#1. Reading nessesry data from files.
        
        #finding folder with data for year entered
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        
        #Catching empty data at the start of the season. Avoiding mistake with reading empty file
        try:
            Table = pd.read_csv(Path(f'{folder}in/Table_'+source+'.csv')) # Main data from source containing rows for each player
        except:
            print('!!!!!!!!')
            Table = pd.DataFrame()
            self.Table = Table
            return
        if len(Table)<1:
            Table = pd.DataFrame()
            self.Table = Table
            return
    
        #in a game with columns 'element', 'round', 'fixture', 'threat', 'creativity', 'team', opponent_team'
        Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv')) # Table of rows for each fixture
        Teams = pd.read_csv(Path(f'{folder}in/Teams.csv')) # Table of rows as teams with columns 'id', 'Teams',
        #'TARGET COL', 'Matches'
        Players = pd.read_csv(Path(f'{folder}in/Players.csv')) # Table of rows as players with columns 'id', 'Name',
        #'Team', Team games', 'Played'
        del Players['web_name'] #This column is needed only for inputUnderstat.py
        
        
        Team_played_fixtures = pd.read_csv(Path(f'{folder}in/Team_played_fixtures.csv'))
        Team_played_fixtures = to_lists(Team_played_fixtures)
        Team_played_fixtures = Team_played_fixtures[Team_played_fixtures.columns[::-1]]
        
        Team_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Team_upcoming_fixtures.csv'))
        Team_opponent_team = pd.read_csv(Path(f'{folder}in/Team_opponent_team.csv'))
        Team_opponent_team = to_lists(Team_opponent_team)
        Team_opponent_team = Team_opponent_team[Team_opponent_team.columns[::-1]]
        

        #Reading Fxtures and Opponents for Teams and Players
        
        Team_played_fixtures = pd.read_csv(Path(f'{folder}in/Team_played_fixtures.csv'))
        Team_played_fixtures = to_lists(Team_played_fixtures)
        Team_played_fixtures = Team_played_fixtures[Team_played_fixtures.columns[::-1]]
        
        Team_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Team_upcoming_fixtures.csv'))
        Team_opponent_team = pd.read_csv(Path(f'{folder}in/Team_opponent_team.csv'))
        Team_opponent_team = to_lists(Team_opponent_team)
        Team_opponent_team = Team_opponent_team[Team_opponent_team.columns[::-1]]
        
        Player_opponent_team = pd.read_csv(Path(f'{folder}in/Player_opponent_team.csv'))
        Player_opponent_team = to_lists(Player_opponent_team[Player_opponent_team.columns[::-1]])
        
        #file names differ for the present and history
        if year=='':

            Player_played_fixtures = pd.read_csv(Path(f'{folder}in/Player_played_fixtures.csv'))
            Player_played_fixtures = to_lists(Player_played_fixtures[Player_played_fixtures.columns[::-1]])
            Player_upcoming_fixtures = pd.read_csv(Path(f'{folder}in/Player_upcoming_fixtures.csv'))
            Player_upcoming_fixtures = to_lists(Player_upcoming_fixtures[Player_upcoming_fixtures.columns[::-1]])
        else:
            with open(Path(f'{folder}in/Team_fixtures.txt'), 'r') as file:
                Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
                Team_played_fixtures = Team_played_fixtures.sort_index()
            with open(Path(f'{folder}in/Player_fixtures.txt'), 'r') as file:
                Player_played_fixtures = pd.DataFrame(json.loads(file.read()))
                Player_played_fixtures.index = pd.to_numeric(Player_played_fixtures.index)
                Player_played_fixtures = Player_played_fixtures.sort_index()
            Team_upcoming_fixtures = pd.DataFrame()
            Player_upcoming_fixtures = pd.DataFrame()
        
        print('\t 1. Reading files from ' + source +' is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

#2. Defenition of useful constants and funtions
        
        #Teams in Premier League
        team_number = len(Teams)

        #Calculating lastGW - last gameweek with at least one game played
        firstr = len(Fixtures)+1
        lastr = 0
        for i in range(len(Fixtures)):
            if Fixtures.at[i,'finished']==True:
                firstr = min(firstr, i)
                lastr = i
        if firstr < len(Fixtures)+1:
            lastGW = int(Fixtures.at[lastr,'event'])
        else: lastGW = 0
        if lastr == len(Fixtures):
            lastGW = int(Fixtures.at[lastr,'event'])

        print('\t 2. Constants and Functions are over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 3. Calculating team tables

        print('\t 3. Calculating team tables')

        #(1). Creating  a table with average threat and GW threats for teams

        Team_xG = Teams.copy()
        Team_xG.columns = ['id', 'Teams', 'xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['threat'].sum())


        Team_xG['xG av'] = [Table[Table['team']==i]['threat'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        Team_xG.sort_values('xG av', ascending = False, inplace = True)
        print('\t\t 3.1. Team_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2). Creating  a table with average creativity and GW creativities for teams

        Team_xA = Teams.copy()
        Team_xA.columns = ['id', 'Teams', 'xA av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xA['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                    Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['creativity'].sum())


        Team_xA['xA av'] = [Table[Table['team']==i]['creativity'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        
        print('\t\t 3.2. Team_xA is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()
        
        #(3). Creating  a table with average threat allowed by teams and GW threat allowed

        Team_Opponent_xG = Teams.copy()
        Team_Opponent_xG.columns = ['id', 'Teams', 'Opponent xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_Opponent_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_Opponent_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']== \
                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['opponent_team']==i+1)]['threat'].sum())


        Team_Opponent_xG['Opponent xG av'] = [Table[Table['opponent_team']==i]['threat'].sum()
                        for i in range(1,team_number+1)]/noZ(Teams['Matches'])

        threatAllowedAv = Team_Opponent_xG['Opponent xG av'].mean()
        
        print('\t\t 3.3. Team_Opponent_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        class_data = [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team,\
        Player_opponent_team, Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\

        #(4). Creating  a table with average adjusted threat and GW threats adj for teams

        Team_xG_Ad = adjustment(Team_xG, class_data)       
        print('\t\t 3.4. Team_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(5). Creating  a table with average adjusted creativity and GW creativities adj for teams
        
        Team_xA_Ad = adjustment(Team_xA, class_data)
        print('\t\t 3.5. Team_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(6). Creating  a table with average threat allowed adjusted by teams and GW threat allowed adjusted

        Team_Opponent_xG_Ad = adjustment(Team_Opponent_xG, class_data)
        print('\t\t 3.6. Team_Opponent_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()


        #(7) Total Team Table

        TableTeams = pd.DataFrame()
        TableTeams['id'] = Teams['id']
        TableTeams['Team'] = Teams['Teams']

        TableTeams['xG adjusted'] = Team_xG_Ad['xG av adj']
        TableTeams['xG'] = Team_xG['xG av']
        TableTeams['xA adjusted'] = Team_xA_Ad['xA av adj']
        TableTeams['xA'] = Team_xA['xA av']
        TableTeams['Opponent xG adjusted'] = Team_Opponent_xG_Ad['Opponent xG av adj']
        TableTeams['Opponent xG'] = Team_Opponent_xG['Opponent xG av']
        
        print('\t\t 3.7. TableTeams is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 4. Calculating pLayer tables
        
        print('\t 4. Calculating player tables')

        #(1) Players Threat

        Player_xG = Players.copy()
        #Player_xG['xG per fixture'] = np.zeros(len(Players))
        #Player_xG['xG per game'] = np.zeros(len(Players))
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per fixture',\
        [0.0 for i in Player_xG.itertuples()])
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per game',\
        [0.0 for i in Player_xG.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xG['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                        Player_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['element']==\
                        Player_xG.at[i,'id'])]['threat'].sum())
                    Player_xG.at[i,'xG per game'] = Player_xG.at[i,'xG per game'] +\
                        Player_xG.at[i,'GW'+str(j)][k]


        Player_xG['xG per fixture'] = Player_xG['xG per game']/noZ(Players['Team games'])
        Player_xG['xG per game'] = Player_xG['xG per game']/noZ(Players['Played'])
        
        print('\t\t 4.1. Player_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Players Creativity

        Player_xA = Players.copy()
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per fixture',\
        [0.0 for i in Player_xA.itertuples()])
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per game',\
        [0.0 for i in Player_xA.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xA['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                                Player_played_fixtures.at[i, 'GW'+str(j)][k])&\
                                                (Table['element']==Player_xA.at[i,'id'])]['creativity'].sum())
                    Player_xA.at[i,'xA per game'] = Player_xA.at[i,'xA per game'] +\
                        Player_xA.at[i,'GW'+str(j)][k]


        Player_xA['xA per fixture'] = Player_xA['xA per game']/noZ(Players['Team games'])
        Player_xA['xA per game'] = Player_xA['xA per game']/noZ(Players['Played'])
        
        print('\t\t 4.2. Player_xA is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(3) Players Threat Adjusted
        
        Player_xG_Ad = adjustment(Player_xG, class_data)
        print('\t\t 4.3. Player_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        #(4) PLayers Creativity Adjusted
        
        Player_xA_Ad = adjustment(Player_xA, class_data)    
        print('\t\t 4.4. Player_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
# 5. Creating future tables and opponent tables

        #(1) Calculating futures
        print('\t 5. Creating future tables and opponent tables.')

        Team_oppxG_coeff = no_lists(Team_opponent_team)
        Team_oppdefence_coeff = no_lists(Team_opponent_team)
        Player_oppxG_coeff = no_lists(Player_opponent_team)
        Player_oppdefence_coeff = no_lists(Player_opponent_team)
        
        #Columns with np.nan automatically become float that's why int() is needed
        Team_oppxG_coeff = Team_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[int(x)-1,'xG av adj'] \
        if not np.isnan(x) else np.nan)/threatAllowedAv

        Team_oppdefence_coeff = Team_oppdefence_coeff.applymap(lambda x: \
        Team_Opponent_xG_Ad.at[int(x)-1,'Opponent xG av adj'] if not np.isnan(x) else np.nan)/threatAllowedAv

        Player_oppxG_coeff = Player_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[int(x)-1,'xG av adj'] \
        if not np.isnan(x) else np.nan)/threatAllowedAv

        Player_oppdefence_coeff = Player_oppdefence_coeff.applymap(lambda x: \
        Team_Opponent_xG_Ad.at[int(x)-1,'Opponent xG av adj'] if not np.isnan(x) else np.nan)/threatAllowedAv

        Team_xxG = Team_oppdefence_coeff.mul(Team_xG_Ad['xG av adj'], axis=0)
        Team_xOxG = Team_oppxG_coeff.mul(Team_Opponent_xG_Ad['Opponent xG av adj'], axis=0)
        Player_xxG = Player_oppdefence_coeff.mul(Player_xG_Ad['xG per game adj'], axis=0)
        
        #Writing pure numbers(lists of numbers) tables to mid folder for stats calculations
        Team_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppxG_coeff.txt'))
        Team_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Team_oppdefence_coeff.txt'))
        Player_oppxG_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppxG_coeff.txt'))
        Player_oppdefence_coeff.to_json(Path(f'{folder}mid/{self.source}/Player_oppdefence_coeff.txt'))
        Team_xxG.to_json(Path(f'{folder}mid/{self.source}/Team_xxG.txt'))
        Team_xOxG.to_json(Path(f'{folder}mid/{self.source}/Team_xOxG.txt'))
        Player_xxG.to_json(Path(f'{folder}mid/{self.source}/Player_xxG.txt'))
        
        print('\t\t 5.1. Calculating futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Visualizing futures
        
        #Adding some words for tables to be readable (lists still)
        Display_Team_xxG = Team_xxG.copy()
        Display_Team_xxG['sum'] = Display_Team_xxG.sum(axis=1)
        Display_Team_xxG['Teams'] =  Teams['Teams']
        Display_Team_xxG = Display_Team_xxG[Display_Team_xxG.columns[::-1]].sort_values('sum', ascending=False)
        del Display_Team_xxG['sum']
        for i in range(1,lastGW+1):
            del Display_Team_xxG[f'GW{i}']
        Display_Team_xxG

        Display_Player_xxG = Player_xxG.copy()
        Display_Player_xxG['sum'] = Display_Player_xxG.sum(axis=1)
        Display_Player_xxG['name'] =  Players['Name']
        Display_Player_xxG = Display_Player_xxG[Display_Player_xxG.columns[::-1]].sort_values('sum', ascending=False)
        del Display_Player_xxG['sum']
        for i in range(1,lastGW+1):
            del Display_Player_xxG[f'GW{i}']
        Display_Player_xxG

        Display_Team_xOxG = Team_xOxG.copy()
        Display_Team_xOxG['sum'] = Display_Team_xOxG.sum(axis=1)
        Display_Team_xOxG['Teams'] = Teams['Teams']
        Display_Team_xOxG = Display_Team_xOxG[Display_Team_xOxG.columns[::-1]].sort_values('sum', ascending=True)
        del Display_Team_xOxG['sum']
        for i in range(1,lastGW+1):
            del Display_Team_xOxG[f'GW{i}']
        Display_Team_xOxG
        
        print('\t\t 5.2. Visualizing futures.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
# 6. Writing tables to files (and variables to class.variables)
        
        # Useful variables for debugging
        self.Table = Table
        self.Fixtures = Fixtures
        self.Teams = Teams
        self.Players = Players
        self.lastGW = lastGW
        
        self.threatAllowedAv = threatAllowedAv
        self.Team_played_fixtures = Team_played_fixtures
        self.Team_opponent_team = Team_opponent_team
        self.Player_played_fixtures = Player_played_fixtures
        self.Player_opponent_team = Player_opponent_team
        
        #Save before modifying while writing into files
        self.TxG = Team_xG.copy()
        self.TxA = Team_xA.copy()
        self.TOxG = Team_Opponent_xG.copy()
        self.TxGA = Team_xG_Ad.copy()
        self.TxAA = Team_xA_Ad.copy()
        self.TOxGA = Team_Opponent_xG_Ad.copy()
        self.TaTe = TableTeams.copy() 
        self.PxG = Player_xG.copy()
        self.PxA = Player_xA.copy()
        self.PxGA = Player_xG_Ad.copy()
        self.PxAA = Player_xA_Ad.copy()
        
        self.Team_xG =\
            write_table(Team_xG, 'Team_xG', 'xG av', self.source, self.ma_num, folder)
        self.Team_xA = (write_table
            (Team_xA, 'Team_xA', 'xA av', self.source, self.ma_num, folder))
        self.Team_Opponent_xG =\
            write_table(Team_Opponent_xG, 'Team_Opponent_xG', 'Opponent xG av', self.source, self.ma_num, folder)
        self.Team_xG_Ad =\
            write_table(Team_xG_Ad, 'Team_xG_Ad', 'xG av adj', self.source, self.ma_num, folder)
        self.Team_xA_Ad =\
            write_table(Team_xA_Ad, 'Team_xA_Ad', 'xA av adj', self.source, self.ma_num, folder)
        self.Team_Opponent_xG_Ad =\
            write_table(Team_Opponent_xG_Ad, 'Team_Opponent_xG_Ad', 'Opponent xG av adj', self.source, self.ma_num, folder)
        self.TableTeams =\
            write_table(TableTeams, 'TableTeams', 'xG adjusted', self.source, self.ma_num, folder)
        
        self.Player_xG =\
            write_table(Player_xG, 'Player_xG', 'xG per fixture', self.source, self.ma_num, folder)
        self.Player_xA =\
            write_table(Player_xA, 'Player_xA', 'xA per fixture', self.source, self.ma_num, folder)
        self.Player_xG_Ad =\
            write_table(Player_xG_Ad, 'Player_xG_Ad', 'xG per fixture adj', self.source, self.ma_num, folder)
        self.Player_xA_Ad =\
            write_table(Player_xA_Ad, 'Player_xA_Ad', 'xA per fixture adj', self.source, self.ma_num, folder)
        
        print('\t 6. Writing to files is over.\t It takes ' + str(time() - start) + ' sec')
        print(f'{self.source} is created./t It takes {time() - start_module} sec')
        start = time()

# 7. Tests for each element of the class
    
    def test2FPL(self, folder=''):
        '''
            Checks if all names in the source can be found in fantasy.premierleague.com (FPL)
            Subfunction of test()
        '''
        FPL = pd.read_csv(f'{folder}in/Table_FPL.csv')
        Table_Source = pd.read_csv(f'{folder}in/Table_'+self.source+'.csv')
        Mistakes = pd.DataFrame()
        No_Names = pd.DataFrame()
        if self.source == 'FPL':
            return Mistakes, No_Names
        for i in Table_Source.index:
            if Table_Source.at[i,'element'] < 1000000:
                FPLmin = FPL[(FPL['element'] == Table_Source.at[i,'element'])&\
                            (FPL['fixture'] == Table_Source.at[i,'fixture'])]['minutes'].sum()
                if abs(Table_Source.at[i,'minutes'] - FPLmin) > 10:
                    Mistakes = Mistakes.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'element'],\
                        Table_Source.at[i,'fixture'], Table_Source.at[i,'minutes'], FPLmin]], columns = ['player',\
                        'element', 'fixture', 'minutes', 'FPL_minutes']), ignore_index=True)
            else:
                No_Names = No_Names.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'team_name'], Table_Source.at[i,'fixture']]],\
                                                         columns = ['player', 'team_name', 'fixture']), ignore_index=True)
                #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        display(Mistakes)
        display(No_Names)
        return Mistakes, No_Names
        
    def test(self, year=''):
        '''
            Tests that all tables are correct (no duplicated columns or rows)
            Uses test2FPL() to compare names
        '''
        if year=='': folder = ''
        else: folder = f'history/{year}/'
        if self.Table.empty:
            print(f'Nothing to test. {self.source} table is empty.')
            return
        start = time()
        
        constti.DRDC(self.Team_xG)
        constti.DRDC(self.Team_xA)
        constti.DRDC(self.Team_Opponent_xG)
        constti.DRDC(self.Team_xG_Ad)
        constti.DRDC(self.Team_xA_Ad)
        constti.DRDC(self.Team_Opponent_xG_Ad)
        constti.DRDC(self.TableTeams)
        constti.DRDC(self.Player_xG)
        constti.DRDC(self.Player_xA)
        constti.DRDC(self.Player_xG_Ad)
        constti.DRDC(self.Player_xA_Ad)
        
        self.test2FPL(folder='')
        
        print(f'\t {self.source} Testing is over.\t It takes {time() - start} sec\n\n')

# 7. Useful not class functions

def html_table_name(table_name):
    '''
    Converts the name of the table into the name of the Tale in html file
    '''
    return table_name.replace('Team_', 'Teams Ranking Based on Team ').replace('Player_', 'Players Ranking Based on Player ')\
    .replace('Ad', 'Adjusted').replace('_', ' ').replace('TableTeams', 'Teams Ranking')



def write_table(df, name, key_col, source, ma_num, folder):
    '''
        Writing final tables to files and returning table itself and MA variant also
        df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
        source - Understat or FPL, ma_num - number for MA(currently unused just calculated)
    '''
    
    #print(f'folder = {folder}')
    df.to_json(Path(f'{folder}mid/{source}/{name}.txt')) #writing table to "mid" folder for advanced calculations
    def table2string(table):
        '''
        Converts table to view suitable for html. All number columns are actually strings with 1 digit after .
        '''
        df = table.copy()
        for j in df.columns:
            if ('GW' in j)|(' av' in j)|('xG' in j)|('xA' in j):
                df[j] = [str(int(df.at[i,j]*10)/10) if not np.isnan(df.at[i,j]) else '' for i in df.index]

        return df
    
    #Removes redundant columns
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    
    # Sort decreasing for attack an increasing for defence
    if 'Opponent' in name:
        df.sort_values(key_col, ascending = True, inplace = True)
    else:
        df.sort_values(key_col, ascending = False, inplace = True)
    
    # Removes lists in celss which are needed for double gameweeks
    df.index = np.arange(1, len(df) + 1)
    df = no_lists(df)
    
    # If moving average number is 0 no calculation needed. Use it to fasten the debug!
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    
    #Writes result to file
    df.to_csv(Path(f'{folder}out/' + source + '/' + name + '.csv'))
    
    
    # Add table created as table of stringe to existing html file replacing table tag with a new one
    #Also adding a new css
    if folder == '':
        dfString = table2string(df)
        
        dfStringStyler = dfString.style.apply(color_table, axis=None)#.render().replace('\n', '')#.format(digit_dict)
        dfStringStyler.set_table_attributes('class="DataTable"')
        html_table = dfStringStyler.render().replace('\n', '')
        BS_table = BeautifulSoup(html_table, 'html.parser')
        css = str(BS_table('style')[0])
        html_ = str(BS_table('table')[0])

        #Getting right paths for different tables
        if source=='FPL' and name=='TableTeams':
            html_path = Path(f'{folder}index.html')
            css_path = Path(f'{folder}html/FPL/css/TableTeams.css')
        else:
            html_path = Path(f'{folder}html/{source}/{name}.html')
            css_path = Path(f'{folder}html/{source}/css/{name}.css')

        #Making css for coloring butons

        css = ('#' + source + '-button {\n background-color: #82f5cf;\n}\n' +
               '#' + name + ' {\n background-color: lightgrey;\n}\n' + 
               css)

        #Rewriting html and css
        with open(f'{folder}index.html', 'r', encoding="utf-8") as file:
            old_file = file.read()
        tag_to_replace1 = str(BeautifulSoup(old_file, 'html.parser')('table', attrs={"class":"DataTable"})[0])
        tag_to_replace2 = str(BeautifulSoup(old_file, 'html.parser')('h2', attrs={"id":"DataTitle"})[0])
        new_file = old_file.replace(tag_to_replace1, html_)
        new_file = new_file.replace(tag_to_replace2, f'<h2 id="DataTitle"> {html_table_name(name)} </h2>')

        #Making links right

        if not(source=='FPL' and name=='TableTeams'):
            new_file = new_file.replace('html/FPL/', '')
            new_file = new_file.replace('"out/FPL/TableTeams.csv"', f'"../../out/{source}/{name}.csv"')#Change download button
            new_file = new_file.replace(f'TableTeams', name)
            if name != 'TableTeams': #changes links for buttons FPL and Understat
                new_file = new_file.replace('class="header-form" action="index.html"',\
                f'class="header-form" action="../FPL/{name}.html"')
            else:
                new_file = new_file.replace('form action="index.html"', f'form action="../../index.html"')
            new_file = new_file.replace('html/', '../')
            new_file = new_file.replace('"index.html"', '"../../index.html"')

        #Creating .html and special files for the Table
        with open(html_path, 'w', encoding="utf-8") as file:
            file.write(new_file)
        with open(css_path, 'w', encoding="utf-8") as file:
            file.write(css)
    
    return df

def color_table(df):
    '''
        Makes colored tables
    '''
    def table_type(df):
        if df.columns[2]=='xG': return 'TableTeams'
        elif 'Opponent' in df.columns[1]: return 'Defence'
        elif df.columns[0]=='Teams': return 'Team'
        else: return 'Player'
    def color_Team_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Player_xG(val):
        if val=='': color = 'white'
        elif float(val)>50: color = '#09bb9f'
        elif float(val)>25: color = '#82f5cf'
        elif float(val)>10: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Defence(val):
        if val=='': color = 'white'
        elif float(val)<120: color = '#09bb9f'
        elif float(val)<150: color = '#82f5cf'
        elif float(val)<180: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    
    def color_table_row(row, x):
        '''
            function for style.apply by rows where x is a table type
            Subfunction of color_table_row
        '''
        if x=='Team':
            return [color_Team_xG(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='Player':
            return [color_Player_xG(i) if not (row.name  in ['Team games', 'Played', 'Name', 'Team'])\
                    else 'Background-color: white' for i in row]
        elif x=='Defence':
            return [color_Defence(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='TableTeams':
            return [color_Team_xG(i) if row.name in ['xG adjusted', 'xG', 'xA', 'xA adjusted']\
                   else 'Background-color: white' if row.name in ['Team'] else color_Defence(i) for i in row]
        
    return df.apply(color_table_row, x=table_type(df), axis=0)


# Returns the table with d mean average for table Out_T
# If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
def MA(Out_T, d):
    '''
        Returns the table with d mean average for table Out_T.
        If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
        Filling the column with averages. Subfunction for MA.
        Adds d - averages for j-th GW_column (not GWj but j-th in order) of table T.
    '''
    def d_av(T, j, GW_columns, d):
        T.insert(T.columns.get_loc(GW_columns[-1]), f'{GW_columns[j]} {str(d)} - average', [0.0 for i in T.itertuples()])
        for i in T.index:
            u = 0
            k = 0
            while (u < d)&(j-k>=0):
                if not np.isnan(T.at[i, GW_columns[j-k]]):#!!!'':
                    T.at[i, f'{GW_columns[j]} {str(d)} - average'] += T.at[i, GW_columns[j-k]]
                    u+=1
                    k+=1
                else: k+=1
            if u==d:
                T.at[i, f'{GW_columns[j]} {str(d)} - average'] = T.at[i, f'{GW_columns[j]} {str(d)} - average']/d
            else:
                T.loc[i, f'{GW_columns[j]} {str(d)} - average'] = ''
        return None
    
    T = Out_T.copy()
    
    #Creating the list of GW_columns for the table T
    GW_columns = []
    gw_col=0
        
    for col in T.columns:
        if 'GW' in col:
            GW_columns.append(col)
            gw_col+=1
    GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)] #makes the opposite order of the list
    
    #returning colored MA table if it is TableTeams
    if GW_columns == []: return T
    
    #Add averages for GW_columns using d_av function defined above returning colored MA table if it is not TableTeams
    # Add MA columns only id d not larger than GW played
    if d<=gw_col:
        for j in range(gw_col-1, d-2, -1):
            d_av(T, j, GW_columns, d)

    return T
    
    
######################################For Debugging
# lastGW = 43
# team_number = 20
# Fixtures = Understat.Fixtures
# Table = Understat.Table
# Players = Understat.Players
# Teams = Understat.Teams
# threatAllowedAv = Understat.threatAllowedAv
# Team_Opponent_xG = Understat.TD
# Team_played_fixtures = Understat.Team_played_fixtures
# Team_opponent_team = Understat.Team_opponent_team
# Player_opponent_team = Understat.Player_opponent_team
# Player_played_fixtures = Understat.Player_played_fixtures
# TeamThreat = Understat.TT
# Player_xA = Understat.PC






def adjustment(df, class_data):
    '''
        Creating adjusted tables from unadjusted
        df - table to transform
        class_data - list of needed data from source class
    '''
    [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team, Player_opponent_team,\
     Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\
    = class_data
    if len(df)==len(Teams):
        dfAd = Teams.copy()
        for i in df.columns:
            if ' av' in i:
                key_par = i[:-3]
        av  = 'av'
        dfAd.columns = ['id', 'Teams', f'{key_par} av adj', 'Matches']
        the_fixtures = Team_played_fixtures
        the_opponent_team = Team_opponent_team
    else:
        dfAd = Players.copy()
        for i in df.columns:
            if 'per fixture' in i:
                key_par = i[:-12]
        av = 'per game'
        
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per fixture adj',\
        [0.0 for i in dfAd.itertuples()])
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per game adj',\
        [0.0 for i in dfAd.itertuples()])
        
        
        the_fixtures = Player_played_fixtures
        the_opponent_team = Player_opponent_team
        
    if 'Opponent' in key_par:#key_par[-7:] == 'allowed':
        Weighting_table = Team_xG
        col = 'xG av'
    else:
        Weighting_table = Team_Opponent_xG
        col = 'Opponent xG av'
        
    for j in range(lastGW,0,-1):
        dfAd[f'GW{j}'] = [[] for _ in range(len(df))]
        for i in range(len(df)):
             for k in range(len(the_fixtures.at[i, 'GW'+str(j)])):
                dfAd.at[i,f'GW{j}'].append(df.at[i,f'GW{j}'][k]\
                *threatAllowedAv/ Weighting_table.at[int(the_opponent_team.at[i,f'GW{j}'][k])-1, col])

                dfAd.at[i,f'{key_par} {av} adj'] += dfAd.at[i,f'GW{j}'][k]

    
    if len(df) == len(Teams): dfAd[f'{key_par} av adj'] = dfAd[f'{key_par} av adj']/noZ(dfAd['Matches'])
    else:
        dfAd[f'{key_par} per fixture adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Team games'])
        dfAd[f'{key_par} per game adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Played'])
    
    
    return dfAd

        
if __name__ == '__main__':
    year = ''
    Understat = Source('Understat', ma_num=7, year=year)
    Understat.test(year)
    FPL = Source('FPL', ma_num=7, year=year)
    FPL.test(year)
    #display(MA(Understat.TeamThreatAd, 8))
    pass