In [1]:
from time import time
import constti
from Brr_functions import toint, noZ, no_lists
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
import os

class Source:
    def __init__(self, source, ma_num=0):
        self.source = source
        print(f'Start Creating {self.source} Tables:')
        start_module = time()
        start = time()
        self.ma_num = ma_num # Number of matches for the moving average
        
#1. Reading nessesry data from files.
        
        try:
            Table = pd.read_csv(Path('in/Table_'+source+'.csv')) # Main data from source containing rows for each player
        except:
            print('!!!!!!!!')
            Table = pd.DataFrame()
            self.Table = Table
            return
        if len(Table)<1:
            Table = pd.DataFrame()
            self.Table = Table
            return
        #in a game with columns 'element', 'round', 'fixture', 'threat', 'creativity', 'team', opponent_team'
        Fixtures = pd.read_csv(Path('in/Fixtures.csv')) # Table of rows for each fixture
        Teams = pd.read_csv(Path('in/Teams.csv')) # Table of rows as teams with columns 'id', 'Teams',
        #'TARGET COL', 'Matches'
        Players = pd.read_csv(Path('in/Players.csv')) # Table of rows as players with columns 'id', 'Name',
        #'Team', Team games', 'Played'
        del Players['web_name'] #This column is needed only for inputUnderstat.py
        
        #Reading Fxtures and Opponents for Teams and Players
        with open(Path('in/Team_played_fixtures.txt'), 'r') as file:
            Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
            Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
            Team_played_fixtures = Team_played_fixtures.sort_index()
        with open(Path('in/Team_opponent_team.txt'), 'r') as file:
            Team_opponent_team = pd.DataFrame(json.loads(file.read()))
            Team_opponent_team.index = pd.to_numeric(Team_opponent_team.index)
            Team_opponent_team = Team_opponent_team.sort_index()
        with open(Path('in/Player_played_fixtures.txt'), 'r') as file:
            Player_played_fixtures = pd.DataFrame(json.loads(file.read()))
            Player_played_fixtures.index = pd.to_numeric(Player_played_fixtures.index)
            Player_played_fixtures = Player_played_fixtures.sort_index()
        with open(Path('in/Player_opponent_team.txt'), 'r') as file:
            Player_opponent_team = pd.DataFrame(json.loads(file.read()))
            Player_opponent_team.index = pd.to_numeric(Player_opponent_team.index)
            Player_opponent_team = Player_opponent_team.sort_index()
            
        with open(Path('in/Team_upcoming_fixtures.txt'), 'r') as file:
            Team_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
            Team_upcoming_fixtures.index = pd.to_numeric(Team_upcoming_fixtures.index)
            Team_upcoming_fixtures = Team_upcoming_fixtures.sort_index()
        with open(Path('in/Player_upcoming_fixtures.txt'), 'r') as file:
            Player_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
            Player_upcoming_fixtures.index = pd.to_numeric(Player_upcoming_fixtures.index)
            Player_upcoming_fixtures = Player_upcoming_fixtures.sort_index()
        
        print('\t 1. Reading files from ' + source +' is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

#2. Defenition of useful constants and funtions
        
        #Teams in Premier League
        team_number = len(Teams)

        #Calculating lastGW - last gameweek with at least one game played
        firstr = len(Fixtures)+1
        lastr = 0
        for i in range(len(Fixtures)):
            if Fixtures.at[i,'finished']==True:
                firstr = min(firstr, i)
                lastr = i
        if firstr < len(Fixtures)+1:
            lastGW = int(Fixtures.at[lastr,'event'])
        else: lastGW = 0
        if lastr == len(Fixtures):
            lastGW = int(Fixtures.at[lastr,'event'])

        print('\t 2. Constants and Functions are over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 3. Calculating team tables

        print('\t 3. Calculating team tables')

        #(1). Creating  a table with average threat and GW threats for teams

        Team_xG = Teams.copy()
        Team_xG.columns = ['id', 'Teams', 'xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['threat'].sum())


        Team_xG['xG av'] = [Table[Table['team']==i]['threat'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        Team_xG.sort_values('xG av', ascending = False, inplace = True)

        print('\t\t 3.1. Team_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2). Creating  a table with average creativity and GW creativities for teams

        Team_xA = Teams.copy()
        Team_xA.columns = ['id', 'Teams', 'xA av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_xA['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                    Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['team']==i+1)]['creativity'].sum())


        Team_xA['xA av'] = [Table[Table['team']==i]['creativity'].sum() for i in range(1,team_number+1)] \
            /noZ(Teams['Matches'])
        
        print('\t\t 3.2. Team_xA is over.\t It takes ' + str(time() - start)+ ' sec')
        start = time()
        
        #(3). Creating  a table with average threat allowed by teams and GW threat allowed

        Team_Opponent_xG = Teams.copy()
        Team_Opponent_xG.columns = ['id', 'Teams', 'Opponent xG av', 'Matches']

        for j in range(lastGW,0,-1):
            Team_Opponent_xG['GW'+str(j)] = [[] for _ in range(team_number)]
            for i in range(team_number):
                for k in range(len(Team_played_fixtures.at[i, 'GW'+str(j)])):
                    Team_Opponent_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']== \
                        Team_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['opponent_team']==i+1)]['threat'].sum())


        Team_Opponent_xG['Opponent xG av'] = [Table[Table['opponent_team']==i]['threat'].sum()
                        for i in range(1,team_number+1)]/noZ(Teams['Matches'])

        threatAllowedAv = Team_Opponent_xG['Opponent xG av'].mean()
        
        print('\t\t 3.3. Team_Opponent_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        class_data = [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team,\
        Player_opponent_team, Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\

        #(4). Creating  a table with average adjusted threat and GW threats adj for teams

        Team_xG_Ad = adjustment(Team_xG, class_data)       
        print('\t\t 3.4. Team_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(5). Creating  a table with average adjusted creativity and GW creativities adj for teams
        
        Team_xA_Ad = adjustment(Team_xA, class_data)
        print('\t\t 3.5. Team_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(6). Creating  a table with average threat allowed adjusted by teams and GW threat allowed adjusted

        Team_Opponent_xG_Ad = adjustment(Team_Opponent_xG, class_data)
        print('\t\t 3.6. Team_Opponent_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()


        #(7) Total Team Table

        TableTeams = pd.DataFrame()
        TableTeams['id'] = Teams['id']
        TableTeams['Team'] = Teams['Teams']

        TableTeams['xG adjusted'] = Team_xG_Ad['xG av adj']
        TableTeams['xG'] = Team_xG['xG av']
        TableTeams['xA adjusted'] = Team_xA_Ad['xA av adj']
        TableTeams['xA'] = Team_xA['xA av']
        TableTeams['Opponent xG adjusted'] = Team_Opponent_xG_Ad['Opponent xG av adj']
        TableTeams['Opponent xG'] = Team_Opponent_xG['Opponent xG av']
        
        print('\t\t 3.7. TableTeams is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 4. Calculating pLayer tables
        
        print('\t 4. Calculating player tables')

        #(1) Players Threat

        Player_xG = Players.copy()
        #Player_xG['xG per fixture'] = np.zeros(len(Players))
        #Player_xG['xG per game'] = np.zeros(len(Players))
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per fixture',\
        [0.0 for i in Player_xG.itertuples()])
        Player_xG.insert(Player_xG.columns.get_loc('Team games'), 'xG per game',\
        [0.0 for i in Player_xG.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xG['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xG.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                        Player_played_fixtures.at[i, 'GW'+str(j)][k])&(Table['element']==\
                        Player_xG.at[i,'id'])]['threat'].sum())
                    Player_xG.at[i,'xG per game'] = Player_xG.at[i,'xG per game'] +\
                        Player_xG.at[i,'GW'+str(j)][k]


        Player_xG['xG per fixture'] = Player_xG['xG per game']/noZ(Players['Team games'])
        Player_xG['xG per game'] = Player_xG['xG per game']/noZ(Players['Played'])
        
        print('\t\t 4.1. Player_xG is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(2) Players Creativity

        Player_xA = Players.copy()
        #Player_xA['xA per fixture'] = np.zeros(len(Players))
        #Player_xA['xA per game'] = np.zeros(len(Players))
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per fixture',\
        [0.0 for i in Player_xA.itertuples()])
        Player_xA.insert(Player_xA.columns.get_loc('Team games'), 'xA per game',\
        [0.0 for i in Player_xA.itertuples()])

        for j in range(lastGW,0,-1):
            Player_xA['GW'+str(j)] = [[] for _ in range(len(Players))]
            for i in range(len(Players)):
                for k in range(len(Player_played_fixtures.at[i, 'GW'+str(j)])):
                    Player_xA.at[i,'GW'+str(j)].append(Table[(Table['fixture']==\
                                                Player_played_fixtures.at[i, 'GW'+str(j)][k])&\
                                                (Table['element']==Player_xA.at[i,'id'])]['creativity'].sum())
                    Player_xA.at[i,'xA per game'] = Player_xA.at[i,'xA per game'] +\
                        Player_xA.at[i,'GW'+str(j)][k]


        Player_xA['xA per fixture'] = Player_xA['xA per game']/noZ(Players['Team games'])
        Player_xA['xA per game'] = Player_xA['xA per game']/noZ(Players['Played'])
        
        print('\t\t 4.2. Player_xA is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()
        
        #(3) Players Threat Adjusted
        
        Player_xG_Ad = adjustment(Player_xG, class_data)
        print('\t\t 4.3. Player_xG_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

        #(4) PLayers Creativity Adjusted
        
        Player_xA_Ad = adjustment(Player_xA, class_data)    
        print('\t\t 4.4. Player_xA_Ad is over.\t It takes ' + str(time() - start) + ' sec')
        start = time()

# 5. Writing tables to files (and variables to class.variables)
        
        # Useful variables for debugging
        self.Table = Table
        self.Fixtures = Fixtures
        self.Teams = Teams
        self.Players = Players
        self.lastGW = lastGW
        
        self.threatAllowedAv = threatAllowedAv
        self.Team_played_fixtures = Team_played_fixtures
        self.Team_opponent_team = Team_opponent_team
        self.Player_played_fixtures = Player_played_fixtures
        self.Player_opponent_team = Player_opponent_team
        
        #Save before modifying while writing into files
        self.TxG = Team_xG.copy()
        self.TxA = Team_xA.copy()
        self.TOxG = Team_Opponent_xG.copy()
        self.TxGA = Team_xG_Ad.copy()
        self.TxAA = Team_xA_Ad.copy()
        self.TOxGA = Team_Opponent_xG_Ad.copy()
        self.TaTe = TableTeams.copy() 
        self.PxG = Player_xG.copy()
        self.PxA = Player_xA.copy()
        self.PxGA = Player_xG_Ad.copy()
        self.PxAA = Player_xA_Ad.copy()
        
        self.Team_xG =\
            write_table(Team_xG, 'Team_xG', 'xG av', self.source, self.ma_num)
        self.Team_xA = (write_table
            (Team_xA, 'Team_xA', 'xA av', self.source, self.ma_num))
        self.Team_Opponent_xG =\
            write_table(Team_Opponent_xG, 'Team_Opponent_xG', 'Opponent xG av', self.source, self.ma_num)
        self.Team_xG_Ad =\
            write_table(Team_xG_Ad, 'Team_xG_Ad', 'xG av adj', self.source, self.ma_num)
        self.Team_xA_Ad =\
            write_table(Team_xA_Ad, 'Team_xA_Ad', 'xA av adj', self.source, self.ma_num)
        self.Team_Opponent_xG_Ad =\
            write_table(Team_Opponent_xG_Ad, 'Team_Opponent_xG_Ad', 'Opponent xG av adj', self.source, self.ma_num)
        self.TableTeams =\
            write_table(TableTeams, 'TableTeams', 'xG adjusted', self.source, self.ma_num)
        
        self.Player_xG =\
            write_table(Player_xG, 'Player_xG', 'xG per fixture', self.source, self.ma_num)
        self.Player_xA =\
            write_table(Player_xA, 'Player_xA', 'xA per fixture', self.source, self.ma_num)
        self.Player_xG_Ad =\
            write_table(Player_xG_Ad, 'Player_xG_Ad', 'xG per fixture adj', self.source, self.ma_num)
        self.Player_xA_Ad =\
            write_table(Player_xA_Ad, 'Player_xA_Ad', 'xA per fixture adj', self.source, self.ma_num)
        
        print('\t 5. Writing to files is over.\t It takes ' + str(time() - start) + ' sec')
        print(f'{self.source} is created./t It takes {time() - start_module} sec\n')
        start = time()

# 6. Tests for each element of the class
    
    # Checks if all names in the source can be found in fantasy.premierleague.com (FPL)
    def test2FPL(self):
        FPL = pd.read_csv('in/Table_FPL.csv')
        Table_Source = pd.read_csv('in/Table_'+self.source+'.csv')
        Mistakes = pd.DataFrame()
        No_Names = pd.DataFrame()
        if self.source == 'FPL':
            return Mistakes, No_Names
        for i in Table_Source.index:
            if Table_Source.at[i,'element'] < 1000000:
                FPLmin = FPL[(FPL['element'] == Table_Source.at[i,'element'])&\
                            (FPL['fixture'] == Table_Source.at[i,'fixture'])]['minutes'].sum()
                if abs(Table_Source.at[i,'minutes'] - FPLmin) > 10:
                    Mistakes = Mistakes.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'element'],\
                        Table_Source.at[i,'fixture'], Table_Source.at[i,'minutes'], FPLmin]], columns = ['player',\
                        'element', 'fixture', 'minutes', 'FPL_minutes']), ignore_index=True)
            else:
                No_Names = No_Names.append(pd.DataFrame([[Table_Source.at[i,'player'], Table_Source.at[i,'team_name'], Table_Source.at[i,'fixture']]],\
                                                         columns = ['player', 'team_name', 'fixture']), ignore_index=True)
                #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        display(Mistakes)
        display(No_Names)
        return Mistakes, No_Names
        
    def test(self):
        if self.Table.empty:
            print(f'Nothing to test. {self.source} table is empty.')
            return
        start = time()
        
        constti.DRDC(self.Team_xG)
        constti.DRDC(self.Team_xA)
        constti.DRDC(self.Team_Opponent_xG)
        constti.DRDC(self.Team_xG_Ad)
        constti.DRDC(self.Team_xA_Ad)
        constti.DRDC(self.Team_Opponent_xG_Ad)
        constti.DRDC(self.TableTeams)
        constti.DRDC(self.Player_xG)
        constti.DRDC(self.Player_xA)
        constti.DRDC(self.Player_xG_Ad)
        constti.DRDC(self.Player_xA_Ad)
        
        self.test2FPL()
        
        print(f'\t {self.source} Testing is over.\t It takes {time() - start} sec')

# 7. Useful not class functions

def html_table_name(table_name):
    '''
    Converts the name of the table into the name of the Tale in html file
    '''
    return table_name.replace('Team_', 'Teams Ranking Based on Team ').replace('Player_', 'Players Ranking Based on Player ')\
    .replace('Ad', 'Adjusted').replace('_', ' ').replace('TableTeams', 'Teams Ranking')

# Writing final tables to files and returning table itself and MA variant also
# df - Table to make final table out of it, name - the name of the table, key_col - column to sort,
# source - Understat or FPL, ma_num - number for MA(currently unused just calculated)
def write_table(df, name, key_col, source, ma_num):
    
    def table2string(table):
        '''
        Converts table to view suitable for html. All number columns are actually strings with 1 digit after .
        '''
        df = table.copy()
        for j in df.columns:
            if ('GW' in j)|(' av' in j)|('xG' in j)|('xA' in j):
                df[j] = [str(int(df.at[i,j]*10)/10) if df.at[i,j] != None else '' for i in df.index]

        return df
    
    #Removes redundant columns
    del df['id']
    if 'Team number' in df.columns:
        del df['Team number']
    
    # Sort decreasing for attack an increasing for defence
    if 'Opponent' in name:
        df.sort_values(key_col, ascending = True, inplace = True)
    else:
        df.sort_values(key_col, ascending = False, inplace = True)
    
    # Removes lists in celss which are needed for double gameweeks
    df.index = np.arange(1, len(df) + 1)
    df = no_lists(df)
    
    # If moving average number is 0 no calculation needed. Use it to fasten the debug!
    if ma_num == 0:
        df_ma = df
    else:
        df_ma = MA(df, ma_num)
    
    #Writes result to file
    df.to_csv(Path('out/' + source + '/' + name + '.csv'))
    
    dfString = table2string(df)
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    # Add table to existing html file replacing table tag with a new one
    #Also adding a new css
#     digit_dict = {}
#     for i in df.columns:
#         if 'GW' in i:
#             digit_dict[i] = "{:.2f}"
#     print(str(name) + str(digit_dict))
    html_table = dfString.style.apply(color_table, axis=None).render().replace('\n', '')#.format(digit_dict)
    BS_table = BeautifulSoup(html_table, 'html.parser')
    css = str(BS_table('style')[0])
    html_ = str(BS_table('table')[0])
    
    #Getting right paths for different tables
    if source=='FPL' and name=='TableTeams':
        html_path = Path('index.html')
        css_path = Path(f'html/FPL/css/TableTeams.css')
    else:
        html_path = Path(f'html/{source}/{name}.html')
        css_path = Path(f'html/{source}/css/{name}.css')
        
    #Making css for coloring butons
    
    css = ('#' + source + '-button {\n background-color: #82f5cf;\n}\n' +
           '#' + name + ' {\n background-color: lightgrey;\n}\n' + 
           css)
        
    #Rewriting html and css
    with open('index.html', 'r', encoding="utf-8") as file:
        old_file = file.read()
    tag_to_replace1 = str(BeautifulSoup(old_file, 'html.parser')('table')[0])
    tag_to_replace2 = str(BeautifulSoup(old_file, 'html.parser')('h2')[0])
    new_file = old_file.replace(tag_to_replace1, html_)
    new_file = new_file.replace(tag_to_replace2, f'<h2> {html_table_name(name)} </h2>')
    
    #Making links right
        
    if not(source=='FPL' and name=='TableTeams'):
        new_file = new_file.replace('html/FPL/', '')
        new_file = new_file.replace(f'TableTeams', name)
        if name != 'TableTeams':
            new_file = new_file.replace('form action="index.html"', f'form action="../FPL/{name}.html"')
        else:
            new_file = new_file.replace('form action="index.html"', f'form action="../../index.html"')
        new_file = new_file.replace('html/', '../')
        new_file = new_file.replace('"index.html"', '"../../index.html"')
    
    #Creating .html and special files for the Table
    with open(html_path, 'w', encoding="utf-8") as file:
        file.write(new_file)
    with open(css_path, 'w', encoding="utf-8") as file:
        file.write(css)
    
    return df


#Makes colored tables
def color_table(df):
    def table_type(df):
        if df.columns[2]=='xG': return 'TableTeams'
        elif 'Opponent' in df.columns[1]: return 'Defence'
        elif df.columns[0]=='Teams': return 'Team'
        else: return 'Player'
    def color_Team_xG(val):
        if val=='': color = 'white'
        elif float(val)>200: color = '#09bb9f'
        elif float(val)>140: color = '#82f5cf'
        elif float(val)>120: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Player_xG(val):
        if val=='': color = 'white'
        elif float(val)>50: color = '#09bb9f'
        elif float(val)>25: color = '#82f5cf'
        elif float(val)>10: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    def color_Defence(val):
        if val=='': color = 'white'
        elif float(val)<120: color = '#09bb9f'
        elif float(val)<150: color = '#82f5cf'
        elif float(val)<180: color = '#c4c4c4'
        else: color = '#15607a'
        return f'Background-color: {color}'
    
    #function for style.apply by rows where x is a table type
    def color_table_row(row, x):
        if x=='Team':
            return [color_Team_xG(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='Player':
            return [color_Player_xG(i) if not (row.name  in ['Team games', 'Played', 'Name', 'Team'])\
                    else 'Background-color: white' for i in row]
        elif x=='Defence':
            return [color_Defence(i) if not(row.name in ['Matches', 'Teams']) else 'Background-color: white' for i in row]
        elif x=='TableTeams':
            return [color_Team_xG(i) if row.name in ['xG adjusted', 'xG', 'xA', 'xA adjusted']\
                   else 'Background-color: white' if row.name in ['Team'] else color_Defence(i) for i in row]
        
    return df.apply(color_table_row, x=table_type(df), axis=0)


# Returns the table with d mean average for table Out_T
# If less than d matches played returns zero. If no match played in gameweeek previous gameweek taken.
def MA(Out_T, d):
    
    # Filling the column with averages. Subfunction for MA
    #Adds d - averages for j-th GW_column (not GWj but j-th in order) of table T
    def d_av(T, j, GW_columns, d):
        T.insert(T.columns.get_loc(GW_columns[-1]), f'{GW_columns[j]} {str(d)} - average', [0.0 for i in T.itertuples()])
        for i in T.index:
            u = 0
            k = 0
            while (u < d)&(j-k>=0):
                if T.at[i, GW_columns[j-k]] != None:#!!!'':
                    T.at[i, f'{GW_columns[j]} {str(d)} - average'] += T.at[i, GW_columns[j-k]]
                    u+=1
                    k+=1
                else: k+=1
            if u==d:
                T.at[i, f'{GW_columns[j]} {str(d)} - average'] = T.at[i, f'{GW_columns[j]} {str(d)} - average']/d
            else:
                T.loc[i, f'{GW_columns[j]} {str(d)} - average'] = ''
        return None
    
    T = Out_T.copy()
    
    #Creating the list of GW_columns for the table T
    GW_columns = []
    gw_col=0
        
    for col in T.columns:
        if 'GW' in col:
            GW_columns.append(col)
            gw_col+=1
    GW_columns = [GW_columns[i] for i in range(len(GW_columns)-1, -1, -1)] #makes the opposite order of the list
    
    #returning colored MA table if it is TableTeams
    if GW_columns == []: return T
    
    #Add averages for GW_columns using d_av function defined above returning colored MA table if it is not TableTeams
    # Add MA columns only id d not larger than GW played
    if d<=gw_col:
        for j in range(gw_col-1, d-2, -1):
            d_av(T, j, GW_columns, d)

    return T
    
    
######################################For Debugging
# lastGW = 43
# team_number = 20
# Fixtures = Understat.Fixtures
# Table = Understat.Table
# Players = Understat.Players
# Teams = Understat.Teams
# threatAllowedAv = Understat.threatAllowedAv
# Team_Opponent_xG = Understat.TD
# Team_played_fixtures = Understat.Team_played_fixtures
# Team_opponent_team = Understat.Team_opponent_team
# Player_opponent_team = Understat.Player_opponent_team
# Player_played_fixtures = Understat.Player_played_fixtures
# TeamThreat = Understat.TT
# Player_xA = Understat.PC






def adjustment(df, class_data):
    [Teams, Players, Team_played_fixtures, Player_played_fixtures, Team_opponent_team, Player_opponent_team,\
     Team_xG, Team_Opponent_xG, threatAllowedAv, lastGW]\
    = class_data
    if len(df)==len(Teams):
        dfAd = Teams.copy()
        for i in df.columns:
            if ' av' in i:
                key_par = i[:-3]
        av  = 'av'
        dfAd.columns = ['id', 'Teams', f'{key_par} av adj', 'Matches']
        the_fixtures = Team_played_fixtures
        the_opponent_team = Team_opponent_team
    else:
        dfAd = Players.copy()
        for i in df.columns:
            if 'per fixture' in i:
                key_par = i[:-12]
        av = 'per game'
        
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per fixture adj',\
        [0.0 for i in dfAd.itertuples()])
        dfAd.insert(dfAd.columns.get_loc('Team games'), f'{key_par} per game adj',\
        [0.0 for i in dfAd.itertuples()])
        
        
        the_fixtures = Player_played_fixtures
        the_opponent_team = Player_opponent_team
    if 'Opponent' in key_par:#key_par[-7:] == 'allowed':
        Weighting_table = Team_xG
        col = 'xG av'
    else:
        Weighting_table = Team_Opponent_xG
        col = 'Opponent xG av'
        
    for j in range(lastGW,0,-1):
        dfAd[f'GW{j} adj'] = [[] for _ in range(len(df))]
        for i in range(len(df)):
             for k in range(len(the_fixtures.at[i, 'GW'+str(j)])):
                dfAd.at[i,f'GW{j} adj'].append(df.at[i,f'GW{j}'][k]\
                *threatAllowedAv/ Weighting_table.at[the_opponent_team.at[i,f'GW{j}'][k]-1, col])

                dfAd.at[i,f'{key_par} {av} adj'] += dfAd.at[i,f'GW{j} adj'][k]

    if len(df) == len(Teams): dfAd[f'{key_par} av adj'] = dfAd[f'{key_par} av adj']/noZ(dfAd['Matches'])
    else:
        dfAd[f'{key_par} per fixture adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Team games'])
        dfAd[f'{key_par} per game adj'] = dfAd[f'{key_par} per game adj']/noZ(dfAd['Played'])
    
    
    return dfAd

        
if __name__ == '__main__':
    Understat = Source('Understat', ma_num=7)
    Understat.test()
    FPL = Source('FPL', ma_num=7)
    FPL.test()
    #display(MA(Understat.TeamThreatAd, 8))
    pass

Start Creating Understat Tables:
	 1. Reading files from Understat is over.	 It takes 1.7441270351409912 sec
	 2. Constants and Functions are over.	 It takes 0.07395052909851074 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 1.0145487785339355 sec
		 3.2. Team_xA is over.	 It takes 0.4607203006744385 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.45972609519958496 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.07588958740234375 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.032979726791381836 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.0299837589263916 sec
		 3.7. TableTeams is over.	 It takes 0.037519216537475586 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 11.746756792068481 sec
		 4.2. Player_xA is over.	 It takes 11.485920667648315 sec
		 4.3. Player_xG_Ad is over.	 It takes 1.011375904083252 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.8304872512817383 sec
	 5. Writing to files is over.	 It takes 68.21984624862671 sec
Understat is created./t It takes 97.22683453559875 sec

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

	 Understat Testing is over.	 It takes 6.265135049819946 sec
Start Creating FPL Tables:
	 1. Reading files from FPL is over.	 It takes 0.3008155822753906 sec
	 2. Constants and Functions are over.	 It takes 0.014989852905273438 sec
	 3. Calculating team tables
		 3.1. Team_xG is over.	 It takes 0.4857027530670166 sec
		 3.2. Team_xA is over.	 It takes 0.5176794528961182 sec
		 3.3. Team_Opponent_xG is over.	 It takes 0.46471261978149414 sec
		 3.4. Team_xG_Ad is over.	 It takes 0.02897953987121582 sec
		 3.5. Team_xA_Ad is over.	 It takes 0.027982711791992188 sec
		 3.6. Team_Opponent_xG_Ad is over.	 It takes 0.047971487045288086 sec
		 3.7. TableTeams is over.	 It takes 0.0069959163665771484 sec
	 4. Calculating player tables
		 4.1. Player_xG is over.	 It takes 11.608840942382812 sec
		 4.2. Player_xA is over.	 It takes 14.683947324752808 sec
		 4.3. Player_xG_Ad is over.	 It takes 0.9424185752868652 sec
		 4.4. Player_xA_Ad is over.	 It takes 0.7341914176940918 sec
	 5. Writing to files is over.	 It takes 76.7552375793457 sec
FPL is created./t It takes 106.62646484375 sec

	 FPL Testing is over.	 It takes 0.76651930809021 sec

In [2]:
with open(Path('in/Team_played_fixtures.txt'), 'r') as file:
    Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
    Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
    Team_played_fixtures = Team_played_fixtures.sort_index()
with open(Path('in/Team_opponent_team.txt'), 'r') as file:
    Team_opponent_team = pd.DataFrame(json.loads(file.read()))
    Team_opponent_team.index = pd.to_numeric(Team_opponent_team.index)
    Team_opponent_team = Team_opponent_team.sort_index()
with open(Path('in/Player_played_fixtures.txt'), 'r') as file:
    Player_played_fixtures = pd.DataFrame(json.loads(file.read()))
    Player_played_fixtures.index = pd.to_numeric(Player_played_fixtures.index)
    Player_played_fixtures = Player_played_fixtures.sort_index()
with open(Path('in/Player_opponent_team.txt'), 'r') as file:
    Player_opponent_team = pd.DataFrame(json.loads(file.read()))
    Player_opponent_team.index = pd.to_numeric(Player_opponent_team.index)
    Player_opponent_team = Player_opponent_team.sort_index()

with open(Path('in/Team_upcoming_fixtures.txt'), 'r') as file:
    Team_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
    Team_upcoming_fixtures.index = pd.to_numeric(Team_upcoming_fixtures.index)
    Team_upcoming_fixtures = Team_upcoming_fixtures.sort_index()
with open(Path('in/Player_upcoming_fixtures.txt'), 'r') as file:
    Player_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
    Player_upcoming_fixtures.index = pd.to_numeric(Player_upcoming_fixtures.index)
    Player_upcoming_fixtures = Player_upcoming_fixtures.sort_index()
team_number = 20
Team_opponent_xG_Ad = FPL.TOxGA
Team_xG = FPL.TxG
Team_xG_Ad = FPL.TxGA
Player_xG_Ad = FPL.PxGA
threatAllowedAv = FPL.threatAllowedAv
lastGW = FPL.lastGW

Team_oppxG_coeff = no_lists(Team_opponent_team)
Team_oppdefence_coeff = no_lists(Team_opponent_team)
Player_oppxG_coeff = no_lists(Player_opponent_team)
Player_oppdefence_coeff = no_lists(Player_opponent_team)

Team_oppxG_coeff = Team_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[x-1,'xG av adj'] if x!=None else None)/threatAllowedAv

Team_oppdefence_coeff = Team_oppdefence_coeff.applymap(lambda x: Team_opponent_xG_Ad.at[x-1,'Opponent xG av adj'] \
if x!=None else None)/threatAllowedAv

Player_oppxG_coeff = Player_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[x-1,'xG av adj'] \
if x!=None else None)/threatAllowedAv

Player_oppdefence_coeff = Player_oppdefence_coeff.applymap(lambda x: Team_opponent_xG_Ad.at[x-1,'Opponent xG av adj'] \
if x!=None else None)/threatAllowedAv

Team_xxG = Team_oppdefence_coeff.mul(Team_xG_Ad['xG av adj'], axis=0)
Team_xOxG = Team_oppxG_coeff.mul(Team_opponent_xG_Ad['Opponent xG av adj'], axis=0)
Player_xxG = Player_oppdefence_coeff.mul(Player_xG_Ad['xG per game adj'], axis=0)

Team_xxG

Display_Team_xxG = Team_xxG.copy()
Display_Team_xxG['sum'] = Display_Team_xxG.sum(axis=1)
Display_Team_xxG['Teams'] =  FPL.Teams['Teams']
Display_Team_xxG = Display_Team_xxG[Display_Team_xxG.columns[::-1]].sort_values('sum', ascending=False)
del Display_Team_xxG['sum']
for i in range(1,lastGW+1):
    del Display_Team_xxG[f'GW{i}']
Display_Team_xxG

Display_Player_xxG = Player_xxG.copy()
Display_Player_xxG['sum'] = Display_Player_xxG.sum(axis=1)
Display_Player_xxG['name'] =  FPL.Players['Name']
Display_Player_xxG = Display_Player_xxG[Display_Player_xxG.columns[::-1]].sort_values('sum', ascending=False)
del Display_Player_xxG['sum']
for i in range(1,lastGW+1):
    del Display_Player_xxG[f'GW{i}']
Display_Player_xxG

Display_Team_xOxG = Team_xOxG.copy()
Display_Team_xOxG['sum'] = Display_Team_xOxG.sum(axis=1)
Display_Team_xOxG['Teams'] =  FPL.Teams['Teams']
Display_Team_xOxG = Display_Team_xOxG[Display_Team_xOxG.columns[::-1]].sort_values('sum', ascending=True)
del Display_Team_xOxG['sum']
for i in range(1,lastGW+1):
    del Display_Team_xOxG[f'GW{i}']
Display_Team_xOxG

,Teams,GW9,GW10,GW11,GW12,GW13,GW14,GW15,GW16,GW17,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
2,Brighton,144.791970,145.681524,83.283341,83.401177,77.788685,68.899937,98.422375,81.526079,67.698893,...,66.409398,102.469537,104.383256,114.391630,68.899937,112.315763,67.698893,98.422375,109.859384,81.526079
10,Liverpool,99.193638,117.942768,80.518043,92.518390,142.575382,96.954881,81.060813,78.984375,99.053489,...,136.052300,96.963480,172.209108,133.583356,78.984375,121.872695,99.053489,81.060813,80.194719,96.954881
11,Man City,148.303533,83.416646,96.235437,126.769089,84.317537,103.033092,82.157675,129.136626,141.518378,...,83.752960,103.178872,138.950241,179.127833,103.033092,100.850170,141.518378,82.157675,122.681272,129.136626
4,Chelsea,84.684323,152.864408,143.223468,133.108048,86.328669,125.506817,103.960899,184.636667,140.091129,...,185.771013,86.910609,103.951681,126.454168,125.506817,99.195028,140.091129,103.960899,106.351998,184.636667
0,Arsenal,149.271947,89.974420,159.320034,89.613124,110.686747,138.729342,152.030853,131.794462,90.580936,...,130.807103,193.616320,91.570653,103.384139,138.729342,88.260631,90.580936,152.030853,108.341670,131.794462
15,Southampton,95.361593,144.340001,139.685589,97.053400,114.838757,154.749441,109.574212,138.639113,205.209000,...,168.859241,94.978665,96.004424,114.828573,154.749441,117.480046,205.209000,109.574212,158.209530,138.639113
12,Man Utd,102.192314,124.875447,147.574988,164.723695,103.308901,168.406801,125.052131,101.508050,217.101784,...,122.229759,148.688915,179.742931,101.100440,168.406801,218.435585,217.101784,125.052131,116.636732,101.508050
16,Spurs,174.068428,181.249616,129.175277,129.163822,230.827380,132.146306,107.266576,123.253504,177.960476,...,131.959599,105.223415,162.359469,165.391691,123.253504,109.169589,177.960476,107.266576,229.417913,132.146306
1,Aston Villa,167.685285,166.429044,112.296138,114.476633,114.016947,115.248318,137.845730,193.432536,173.272664,...,116.507559,131.538143,246.342732,185.768656,115.248318,176.508701,173.272664,137.845730,202.706737,193.432536
8,Leicester,231.163638,123.433054,109.328622,157.352889,165.632626,190.216397,162.595986,129.351982,105.376699,...,106.991476,174.322002,156.174055,108.146972,129.351982,132.151831,105.376699,162.595986,181.513652,190.216397
18,West Ham,111.727110,234.792497,166.163071,182.129564,132.189749,185.495759,160.804950,135.051022,169.266330,...,132.201472,109.779515,135.242103,107.688488,185.495759,109.338690,169.266330,160.804950,110.519537,135.051022
19,Wolves,133.754894,130.932691,233.967759,232.539116,183.715495,108.289331,192.523809,164.568350,159.261652,...,176.436608,158.068518,124.930354,110.654828,108.289331,109.458844,159.261652,192.523809,167.641826,164.568350
6,Everton,132.976496,191.999089,115.263708,195.547696,142.570816,139.365414,117.781555,187.800012,168.248924,...,116.508544,139.353056,169.518902,204.923309,139.365414,247.515803,168.248924,117.781555,115.728420,187.800012
5,Crystal Palace,120.432853,118.615211,121.733515,214.113350,175.794257,260.204808,258.615958,148.964582,123.063615,...,183.022978,186.441112,204.317276,148.754113,148.964582,196.222137,123.063615,258.615958,145.615430,260.204808
14,Sheffield Utd,175.997534,121.874279,149.136835,148.926122,183.234613,177.326000,186.656700,120.572113,145.770882,...,258.915005,200.841499,145.783810,121.058228,177.326000,214.360937,145.770882,186.656700,118.752370,120.572113
9,Leeds,159.851041,204.667910,224.291679,192.980201,130.211235,200.915614,132.206572,133.634389,235.045434,...,152.523001,135.094523,215.405146,285.642870,200.915614,194.436856,235.045434,132.206572,163.296567,133.634389
3,Burnley,169.223460,228.055048,216.687257,169.238468,300.570952,140.534871,233.154199,143.028096,161.480081,...,173.130949,172.886336,137.858032,212.714603,140.534871,204.313174,161.480081,233.154199,302.417560,143.028096
17,West Brom,207.729613,139.676217,165.257690,134.627314,222.710553,293.527039,295.330371,227.690205,165.272346,...,211.609167,231.898471,168.834726,169.073607,293.527039,137.241421,165.272346,295.330371,199.525073,227.690205
7,Fulham,219.566961,175.431804,231.085827,306.436593,208.591124,139.690121,175.183940,252.155853,141.830711,...,236.252744,304.565444,142.402535,171.487593,252.155853,240.619266,141.830711,175.183940,215.541511,139.690121
13,Newcastle,259.256753,184.754009,328.155969,154.466800,254.552017,176.299979,248.984889,330.172050,189.020110,...,224.747829,271.686923,152.816399,223.064096,330.172050,184.770394,189.020110,248.984889,156.154555,176.299979

In [99]:
Display_Team_xxG
Display_Team_xOxG
Display_Player_xxG.sort_values('GW9',ascending=False)
X = no_lists(Team_xG)
X = X[X.columns[4:-1]]
X

    GW8  GW7  GW6  GW5  GW4  GW3  GW2
10  126  146  237  279  264  268  227
1   307  343  154  140  268  191  213
16  221   90  169  145  311  365  164
4   286  202   87  223  207  287   73
11   76  232  195  193  248  147  186
9   102  138  324  178  245  181  147
2   284  108   77  245  176  206  139
12  142  109  148  367   63  123  206
6    81  198   95  118  184  145  313
18  182   77   56  195  193  179  156
8   109  176   58  151   70  123  270
15  204   75  142  177  156   59  175
7   167  177  160  156  104  174  143
5   155  176  276   29   51  139  167
0   125   59  171  120  127   68  137
19   74  161  119  102  165  128   92
3    40   27  122  118  133  124  180
14   79   51  164  119   70  182   56
13   46  158   68  106  139   86   43
17  128  111   78  173   66  105   83

In [14]:
import sklearn
from sklearn.linear_model import LinearRegression
df = no_lists(Team_xG.sort_index())#sort_index doesn't matter as it adds column to suited index anyway


X = df[df.columns[5:-1]].copy()
X['opp_def'] = Team_oppdefence_coeff['GW8']*threatAllowedAv
Y = df['GW8']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

X = df[df.columns[5:-1]].copy()
X['sum'] = X.sum(axis=1)/6
X['opp_def'] = Team_oppdefence_coeff['GW8']*threatAllowedAv
X = X[X.columns[-2:]]
display(X)
Y = df['GW8']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

0.6742185083627833

array([ 0.46492072, -0.15713099,  0.19109522, -0.00488417,  0.37232487,
       -0.10430374,  1.42004889])

           sum     opp_def
0   113.666667  159.939263
1   218.166667  125.706374
2   158.500000  196.346129
3   117.333333   94.584465
4   179.833333  169.134637
5   139.666667  185.455077
6   175.500000  141.820407
7   152.333333  153.376757
8   141.333333  151.904750
9   202.166667  168.939286
10  236.833333  117.014157
11  200.166667  112.494542
12  169.333333  161.688179
13  100.000000  133.232980
14  107.000000  120.612769
15  130.666667  214.365871
16  207.333333  191.744736
17  102.666667  149.865843
18  142.666667  198.955506
19  127.833333  150.084160

0.4728502864413089

array([0.81738501, 1.38830958])

In [9]:
df = no_lists(Team_xG.sort_index())#sort_index doesn't matter as it adds column to suited index anyway
X = df[df.columns[4:-2]].copy()
X['opp_def'] = Team_oppdefence_coeff['GW9']*threatAllowedAv

reg.predict(X)

array([193.04614999, 140.31795111, 208.31195288, 122.14189341,
       276.87179708, 188.88247341, 168.59736094, 138.38365923,
        14.91117372, 146.1958438 , 171.59570334, 133.58397477,
       166.85779862,  31.65819952,  92.91813575, 185.53368172,
       172.64329514,  79.70496498, 184.19591323,  77.19098575])

In [10]:
Display_Team_xxG.sort_index()

,Teams,GW9,GW10,GW11,GW12,GW13,GW14,GW15,GW16,GW17,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,Arsenal,159.851041,130.932691,129.175277,169.238468,114.838757,139.365414,103.960899,81.526079,165.272346,...,132.201472,96.963480,145.783810,171.487593,139.365414,184.770394,165.272346,103.960899,145.615430,81.526079
1,Aston Villa,144.791970,234.792497,328.155969,232.539116,300.570952,293.527039,258.615958,184.636667,217.101784,...,258.915005,304.565444,172.209108,179.127833,293.527039,247.515803,217.101784,258.615958,229.417913,184.636667
2,Brighton,167.685285,117.942768,139.685589,157.352889,208.591124,177.326000,160.804950,131.794462,159.261652,...,224.747829,148.688915,169.518902,126.454168,177.326000,194.436856,159.261652,160.804950,122.681272,131.794462
3,Burnley,120.432853,83.416646,115.263708,89.613124,114.016947,108.289331,132.206572,120.572113,141.830711,...,106.991476,94.978665,152.816399,101.100440,108.289331,109.338690,141.830711,132.206572,80.194719,120.572113
4,Chelsea,259.256753,181.249616,224.291679,195.547696,183.715495,185.495759,152.030853,193.432536,141.518378,...,136.052300,231.898471,204.317276,114.391630,185.495759,240.619266,141.518378,152.030853,181.513652,193.432536
5,Crystal Palace,169.223460,184.754009,165.257690,129.163822,132.189749,96.954881,137.845730,129.351982,145.770882,...,122.229759,139.353056,103.951681,114.828573,129.351982,100.850170,145.770882,137.845730,108.341670,96.954881
6,Everton,219.566961,204.667910,216.687257,133.108048,165.632626,138.729342,186.656700,129.136626,169.266330,...,211.609167,186.441112,104.383256,165.391691,138.729342,176.508701,169.266330,186.656700,167.641826,129.136626
7,Fulham,132.976496,123.433054,96.235437,92.518390,77.788685,176.299979,109.574212,123.253504,161.480081,...,152.523001,131.538143,124.930354,103.384139,123.253504,99.195028,161.480081,109.574212,116.636732,176.299979
8,Leicester,99.193638,175.431804,149.136835,83.401177,142.570816,132.146306,125.052131,148.964582,189.020110,...,173.130949,103.178872,135.242103,169.073607,148.964582,117.480046,189.020110,125.052131,106.351998,132.146306
9,Leeds,149.271947,191.999089,143.223468,182.129564,254.552017,168.406801,233.154199,227.690205,177.960476,...,236.252744,200.841499,138.950241,133.583356,168.406801,112.315763,177.960476,233.154199,158.209530,227.690205
10,Liverpool,231.163638,145.681524,233.967759,306.436593,230.827380,260.204808,295.330371,330.172050,205.209000,...,185.771013,193.616320,246.342732,285.642870,330.172050,218.435585,205.209000,295.330371,302.417560,260.204808
11,Man City,174.068428,228.055048,231.085827,164.723695,222.710553,154.749441,248.984889,187.800012,140.091129,...,176.436608,174.322002,215.405146,185.768656,154.749441,196.222137,140.091129,248.984889,109.859384,187.800012
12,Man Utd,207.729613,144.340001,166.163071,126.769089,183.234613,200.915614,162.595986,164.568350,173.272664,...,183.022978,102.469537,162.359469,212.714603,200.915614,121.872695,173.272664,162.595986,215.541511,164.568350
13,Newcastle,84.684323,118.615211,112.296138,134.627314,130.211235,139.690121,82.157675,78.984375,105.376699,...,66.409398,105.223415,137.858032,107.688488,78.984375,88.260631,105.376699,82.157675,118.752370,139.690121
14,Sheffield Utd,111.727110,139.676217,109.328622,97.053400,103.308901,68.899937,117.781555,143.028096,123.063615,...,116.507559,135.094523,91.570653,110.654828,68.899937,109.169589,123.063615,117.781555,156.154555,143.028096
15,Southampton,133.754894,124.875447,83.283341,148.926122,110.686747,103.033092,175.183940,135.051022,99.053489,...,131.959599,172.886336,168.834726,148.754113,103.033092,132.151831,99.053489,175.183940,163.296567,135.051022
16,Spurs,148.303533,152.864408,159.320034,214.113350,142.575382,190.216397,192.523809,252.155853,235.045434,...,168.859241,271.686923,179.742931,204.923309,252.155853,214.360937,235.045434,192.523809,202.706737,190.216397
17,West Brom,102.192314,121.874279,121.733515,154.466800,84.317537,115.248318,81.060813,133.634389,90.580936,...,116.508544,86.910609,96.004424,108.146972,115.248318,109.458844,90.580936,81.060813,110.519537,133.634389
18,West Ham,175.997534,166.429044,147.574988,192.980201,175.794257,125.506817,98.422375,138.639113,168.248924,...,130.807103,158.068518,156.174055,223.064096,125.506817,204.313174,168.248924,98.422375,199.525073,138.639113
19,Wolves,95.361593,89.974420,80.518043,114.476633,86.328669,140.534871,107.266576,101.508050,67.698893,...,83.752960,109.779515,142.402535,121.058228,140.534871,137.241421,67.698893,107.266576,115.728420,101.508050

In [93]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3
>>> reg = LinearRegression().fit(X, y)
>>> reg.score(X, y)

1.0

In [71]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3
>>> reg = LinearRegression().fit(X, y)
>>> reg.score(X, y)
1.0
>>> reg.coef_
array([1., 2.])
>>> reg.intercept_
3.0000...
>>> reg.predict(np.array([[3, 5]]))
array([16.])

SyntaxError: invalid syntax (<ipython-input-71-0e4031466e69>, line 12)

In [3]:
start = time()

Team_oppxG_coeff = no_lists(Team_opponent_team)
Team_oppdefence_coeff = no_lists(Team_opponent_team)
Player_oppxG_coeff = no_lists(Player_opponent_team)
Player_oppdefence_coeff = no_lists(Player_opponent_team)

Team_oppxG_coeff = Team_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[x-1,'xG av adj'] if x!=None else None)/threatAllowedAv

Team_oppdefence_coeff = Team_oppdefence_coeff.applymap(lambda x: Team_opponent_xG_Ad.at[x-1,'Opponent xG av adj'] \
if x!=None else None)/threatAllowedAv

Player_oppxG_coeff = Player_oppxG_coeff.applymap(lambda x: Team_xG_Ad.at[x-1,'xG av adj'] \
if x!=None else None)/threatAllowedAv

Player_oppdefence_coeff = Player_oppdefence_coeff.applymap(lambda x: Team_opponent_xG_Ad.at[x-1,'Opponent xG av adj'] \
if x!=None else None)/threatAllowedAv

Team_xxG = Team_oppdefence_coeff.mul(Team_xG_Ad['xG av adj'], axis=0)
Team_xOxG = Team_oppxG_coeff.mul(Team_opponent_xG_Ad['Opponent xG av adj'], axis=0)
Player_xxG = Player_oppdefence_coeff.mul(Player_xG_Ad['xG per game adj'], axis=0)
    
print(f'{time() - start}')


Team_xxG
#Player_oppdefence_coeff

4.3616485595703125

,GW38,GW37,GW36,GW35,GW34,GW33,GW32,GW31,GW30,GW29,...,GW10,GW9,GW8,GW7,GW6,GW5,GW4,GW3,GW2,GW1
0,81.526079,145.615430,103.960899,165.272346,184.770394,139.365414,171.487593,145.783810,96.963480,132.201472,...,130.932691,159.851041,137.857955,122.240599,129.363453,100.859114,145.783810,96.963480,132.201472,171.487593
1,184.636667,229.417913,258.615958,217.101784,247.515803,293.527039,179.127833,172.209108,304.565444,258.915005,...,234.792497,144.791970,192.434069,203.955962,283.898691,229.752118,172.209108,304.565444,258.915005,NaN
2,131.794462,122.681272,160.804950,159.261652,194.436856,177.326000,126.454168,169.518902,148.688915,224.747829,...,117.942768,167.685285,205.855372,157.123998,201.031129,177.121189,169.518902,148.688915,224.747829,126.454168
3,120.572113,80.194719,132.206572,141.830711,109.338690,108.289331,101.100440,152.816399,94.978665,106.991476,...,83.416646,120.432853,67.427046,85.982012,106.835842,136.690322,152.816399,94.978665,106.991476,NaN
4,193.432536,181.513652,152.030853,141.518378,240.619266,185.495759,114.391630,204.317276,231.898471,136.052300,...,181.249616,259.256753,204.553535,237.463453,171.519366,161.133625,204.317276,231.898471,136.052300,114.391630
5,96.954881,108.341670,137.845730,145.770882,100.850170,129.351982,114.828573,103.951681,139.353056,122.229759,...,184.754009,169.223460,159.836865,130.921081,171.472386,81.518849,103.951681,139.353056,122.229759,114.828573
6,129.136626,167.641826,186.656700,169.266330,176.508701,138.729342,165.391691,104.383256,186.441112,211.609167,...,204.667910,219.566961,156.512763,236.573814,147.035692,124.148787,104.383256,186.441112,211.609167,165.391691
7,176.299979,116.636732,109.574212,161.480081,99.195028,123.253504,103.384139,124.930354,131.538143,152.523001,...,123.433054,132.976496,126.140970,157.695778,138.939993,139.100654,124.930354,131.538143,152.523001,103.384139
8,132.146306,106.351998,125.052131,189.020110,117.480046,148.964582,169.073607,135.242103,103.178872,173.130949,...,175.431804,99.193638,133.944141,163.527612,110.843356,141.028686,135.242103,103.178872,173.130949,169.073607
9,227.690205,158.209530,233.154199,177.960476,112.315763,168.406801,133.583356,138.950241,200.841499,236.252744,...,191.999089,149.271947,200.609527,178.219720,189.922313,180.381607,138.950241,200.841499,236.252744,133.583356
10,260.204808,302.417560,295.330371,205.209000,218.435585,330.172050,285.642870,246.342732,193.616320,185.771013,...,145.681524,231.163638,180.228334,236.234983,260.505692,249.036458,246.342732,193.616320,185.771013,285.642870
11,187.800012,109.859384,248.984889,140.091129,196.222137,154.749441,185.768656,215.405146,174.322002,176.436608,...,228.055048,174.068428,130.661849,196.449036,178.146337,146.007325,215.405146,174.322002,176.436608,NaN
12,164.568350,215.541511,162.595986,173.272664,121.872695,200.915614,212.714603,162.359469,102.469537,183.022978,...,144.340001,207.729613,175.167378,136.185936,130.667701,232.236568,162.359469,102.469537,183.022978,NaN
13,139.690121,118.752370,82.157675,105.376699,88.260631,78.984375,107.688488,137.858032,105.223415,66.409398,...,118.615211,84.684323,93.545193,113.524082,106.654967,99.574575,137.858032,105.223415,66.409398,107.688488
14,143.028096,156.154555,117.781555,123.063615,109.169589,68.899937,110.654828,91.570653,135.094523,116.507559,...,139.676217,111.727110,87.860223,85.238818,81.946511,144.928894,91.570653,135.094523,116.507559,110.654828
15,135.051022,163.296567,175.183940,99.053489,132.151831,103.033092,148.754113,168.834726,172.886336,131.959599,...,124.875447,133.754894,188.753047,140.829429,142.369380,106.201736,168.834726,172.886336,131.959599,148.754113
16,190.216397,202.706737,192.523809,235.045434,214.360937,252.155853,204.923309,179.742931,271.686923,168.859241,...,152.864408,148.303533,243.016936,119.876183,248.848734,194.389428,179.742931,271.686923,168.859241,204.923309
17,133.634389,110.519537,81.060813,90.580936,109.458844,115.248318,108.146972,96.004424,86.910609,116.508544,...,121.874279,102.192314,107.989658,143.362468,68.155251,141.482214,96.004424,86.910609,116.508544,108.146972
18,138.639113,199.525073,98.422375,168.248924,204.313174,125.506817,223.064096,156.174055,158.068518,130.807103,...,166.429044,175.997534,207.028431,117.059181,121.762186,155.946879,156.174055,158.068518,130.807103,223.064096
19,101.508050,115.728420,107.266576,67.698893,137.241421,140.534871,121.058228,142.402535,109.779515,83.752960,...,89.974420,95.361593,107.422837,120.918406,153.432514,132.739594,142.402535,109.779515,83.752960,121.058228

In [21]:
with open(Path('in/Team_upcoming_fixtures.txt'), 'r') as file:
    Team_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
    Team_upcoming_fixtures.index = pd.to_numeric(Team_upcoming_fixtures.index)
    Team_upcoming_fixtures = Team_upcoming_fixtures.sort_index()
with open(Path('in/Player_upcoming_fixtures.txt'), 'r') as file:
    Player_upcoming_fixtures = pd.DataFrame(json.loads(file.read()))
    Player_upcoming_fixtures.index = pd.to_numeric(Player_upcoming_fixtures.index)
    Player_upcoming_fixtures = Player_upcoming_fixtures.sort_index()
with open(Path('in/Team_played_fixtures.txt'), 'r') as file:
    Team_played_fixtures = pd.DataFrame(json.loads(file.read()))
    Team_played_fixtures.index = pd.to_numeric(Team_played_fixtures.index)
    Team_played_fixtures = Team_played_fixtures.sort_index()
Team_upcoming_fixtures
team_number
Player_xG_Ad

,id,Name,Team number,Team,xG per fixture adj,xG per game adj,Team games,Played,GW8 adj,GW7 adj,GW6 adj,GW5 adj,GW4 adj,GW3 adj,GW2 adj,GW1 adj
0,1,Mesut Ozil,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
1,2,Sokratis Papastathopoulos,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
2,3,David Luiz Moreira Marinho,1,Arsenal,3.445691,5.513106,8,5,[0.0],[0.0],[2.226646130150173],[25.33888376383764],[0.0],[0.0],[0.0],[0.0]
3,4,Pierre-Emerick Aubameyang,1,Arsenal,17.931944,17.931944,8,8,[7.419931565440547],[27.718952802359883],[13.35987678090104],[2.667250922509225],[24.091935931858163],[5.2616924476797085],[15.91346624266145],[47.02244754542717]
4,5,Cedric Soares,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
5,6,Alexandre Lacazette,1,Arsenal,25.511111,29.155555,8,7,[3.7099657827202734],[2.132227138643068],[51.21286099345399],[0.0],[0.0],[72.34827115559598],[32.88783023483366],[41.797731151490815]
6,7,Shkodran Mustafi,1,Arsenal,0.000000,0.000000,8,2,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
7,8,Bernd Leno,1,Arsenal,0.000000,0.000000,8,8,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
8,9,Granit Xhaka,1,Arsenal,3.399136,4.532182,8,6,[0.0],[0.0],[8.906584520600692],[0.0],[0.0],[0.0],[0.0],[18.28650737877723]
9,10,Pablo Mari,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
10,11,Hector Bellerin,1,Arsenal,6.277773,6.277773,8,8,[11.12989734816082],[4.264454277286136],[23.379784366576818],[0.0],[3.2122581242477546],[2.6308462238398542],[2.1217954990215264],[3.483144262624234]
11,13,Calum Chambers,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
12,14,Sead Kolasinac,1,Arsenal,0.530449,4.243591,8,1,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[4.243590998043053],[0.0]
13,15,Ainsley Maitland-Niles,1,Arsenal,0.928677,1.857353,8,4,[0.0],[0.0],[0.0],[0.0],[0.0],[3.9462693357597813],[0.0],[3.483144262624234]
14,16,Rob Holding,1,Arsenal,0.463746,0.741993,8,5,[3.7099657827202734],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
15,17,Kieran Tierney,1,Arsenal,4.312317,4.928362,8,7,[9.274914456800683],[2.132227138643068],[6.67993839045052],[14.669880073800737],[0.0],[0.0],[0.0],[1.741572131312117]
16,18,Nicolas Pepe,1,Arsenal,10.723620,12.255565,8,7,[19.477320359281435],[0.0],[0.0],[37.34151291512915],[15.258226090176835],[0.0],[8.487181996086106],[5.224716393936352]
17,19,Lucas Torreira,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
18,20,Joseph Willock,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
19,21,Reiss Nelson,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
20,22,Edward Nketiah,1,Arsenal,7.803465,7.803465,8,8,[22.25979469632164],[0.0],[0.0],[0.0],[15.258226090176835],[2.6308462238398542],[22.278852739726023],[0.0]
21,23,Emile Smith Rowe,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
22,24,Bukayo Saka,1,Arsenal,25.031515,33.375353,8,6,[5.56494867408041],[11.727249262536873],[57.8927993839045],[50.67776752767528],[42.56242014628275],[0.0],[31.8269324853229],[0.0]
23,25,Matteo Guendouzi,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
24,26,Gabriel Teodoro Martinelli Silva,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
25,27,William Saliba,1,Arsenal,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
26,478,Willian Borges Da Silva,1,Arsenal,6.590977,7.532545,8,7,[11.12989734816082],[4.264454277286136],[0.0],[0.0],[0.0],[0.0],[4.243590998043053],[33.08987049493023]
27,494,Gabriel Magalhaes,1,Arsenal,11.328402,12.946745,8,7,[3.7099657827202734],[0.0],[26.71975356180208],[29.339760147601474],[0.0],[0.0],[2.1217954990215264],[28.735940166649932]
28,501,Daniel Ceballos Fernandez,1,Arsenal,3.203574,3.661227,8,7,[0.9274914456800684],[0.0],[0.0],[0.0],[0.0],[0.0],[21.21795499021526],[3.483144262624234]
29,526,Mohamed Naser El Sayed Elneny,1,Arsenal,2.738091,4.380946,8,5,[0.9274914456800684],[1.066113569321534],[0.0],[0.0],[1.6061290621238773],[2.6308462238398542],[0.0],[15.674149181809055]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,453,John Ruddy,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
571,454,Joao Filipe Iria Santos Moutinho,20,Wolves,1.193510,1.364011,8,7,[0.0],[0.0],[0.0],[0.0],[0.0],[9.54807974559687],[0.0],[0.0]
572,455,Rui Pedro dos Santos Patricio,20,Wolves,0.000000,0.000000,8,8,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
573,456,Ryan Bennett,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
574,458,Willy Boly,20,Wolves,3.307920,3.307920,8,8,[0.0],[5.454711246200608],[0.0],[0.0],[15.674149181809055],[0.0],[5.33450184501845],[0.0]
575,459,Conor Coady,20,Wolves,0.000000,0.000000,8,8,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
576,460,Raul Jimenez,20,Wolves,26.885031,26.885031,8,8,[4.453292260300346],[11.81854103343465],[20.00899653979239],[17.644549237170597],[28.735940166649932],[49.86219422700587],[44.009640221402215],[38.54709749097306]
577,461,Romain Saiss,20,Wolves,6.307738,8.410317,8,6,[0.0],[0.0],[0.0],[1.6040499306518723],[15.674149181809055],[0.0],[2.667250922509225],[30.51645218035367]
578,462,Jonathan Castro Otto,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
579,463,Leo Bonatini,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
580,464,Leander Dendoncker,20,Wolves,6.895082,7.880094,8,7,[6.67993839045052],[13.63677811550152],[1.429214038556599],[3.2080998613037446],[26.994368035337818],[0.0],[0.0],[3.2122581242477546]
581,465,Adama Traore,20,Wolves,5.061989,5.061989,8,8,[2.226646130150173],[19.091489361702127],[2.858428077113198],[0.0],[0.0],[0.0],[2.667250922509225],[13.652097028052957]
582,466,Ruben Diogo da Silva Neves,20,Wolves,14.606748,14.606748,8,8,[17.813169041201384],[17.27325227963526],[1.429214038556599],[20.85264909847434],[7.837074590904527],[16.97436399217221],[34.674261992619925],[0.0]
583,467,Oskar Buur,20,Wolves,0.000000,0.000000,8,1,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
584,469,Daniel Castelo Podence,20,Wolves,11.888560,13.586925,8,7,[2.226646130150173],[40.001215805471126],[24.296638655462182],[19.24859916782247],[0.0],[0.0],[9.335378228782288],[0.0]
585,470,Max Kilman,20,Wolves,0.783941,1.254306,8,5,[4.453292260300346],[1.8182370820668692],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
586,471,Ruben Goncalo Silva Nascimento Vinagre,20,Wolves,0.000000,0.000000,8,2,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
587,472,Matija Sarkic,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
588,473,Morgan Gibbs-White,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
589,474,Pedro Lomba Neto,20,Wolves,18.532061,18.532061,8,8,[30.05972275702734],[5.454711246200608],[26.44045971329708],[19.24859916782247],[31.34829836361811],[8.487181996086106],[24.005258302583027],[3.2122581242477546]
590,475,Bruno Andre Cavaco Jordao,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
591,476,Leonardo Campana,20,Wolves,0.000000,0.000000,8,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
592,504,Fabio Silva,20,Wolves,6.088430,12.176860,8,4,[4.453292260300346],[1.8182370820668692],[0.0],[0.0],[0.0],[42.43590998043052],[0.0],[0.0]
593,505,Fernando Marcal,20,Wolves,0.893259,1.429214,8,5,[0.0],[0.0],[7.146070192782995],[0.0],[0.0],[0.0],[0.0],[0.0]
594,515,Vitor Ferreira,20,Wolves,0.000000,0.000000,8,2,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]
595,545,Ki-Jana Hoever,20,Wolves,0.353633,1.060898,6,2,[0.0],[0.0],[0.0],[0.0],[0.0],[2.1217954990215264],[],[]
596,546,Nelson Cabral Semedo,20,Wolves,5.667500,5.667500,6,6,[3.33996919522526],[5.454711246200608],[1.429214038556599],[0.0],[17.41572131312117],[6.365386497064579],[],[]
597,553,Meritan Shabani,20,Wolves,0.000000,0.000000,6,0,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[],[]
598,563,Rayan Ait Nouri,20,Wolves,7.806535,15.613069,4,2,[6.67993839045052],[24.546200607902737],[0.0],[0.0],[],[],[],[]
599,581,Owen Otasowie,20,Wolves,0.000000,0.000000,4,0,[0.0],[0.0],[0.0],[0.0],[],[],[],[]